// Code generated by dagnabit (0.5.0+d72c8c7); DO NOT EDIT.

package trellis

import (
	"strings"

	"code.linenisgreat.com/purse-first/libs/dewey/pkgs/errors"
)

// A Literal is the GROUND projection of one espalier box interior — the
// `[id !type tag… k=v…]` an organize document (RFC 0015) or `list -format
// espalier` renders for one object (native tags design G9/G13). It is what
// a trellis Group parse becomes once every term is checked against the
// groundness bar: an object id first, at most one type, `=`-only field
// atoms with a single scalar value, and bare or quoted identifiers as tags.
// Nothing else — no sigils, negation, digests, subpaths, value lists, or
// non-`=` operators — survives ParseLiteral, so a Literal is always exactly
// re-spellable by WriteLiteral and never carries query semantics.
type Literal struct {
	// ID is the object reference, decoded (a quoted `"one/uno.zettel"` id
	// arrives unquoted here; WriteLiteral re-quotes it as needed).
	ID string
	// Type is the `!type` term's name; empty when the box carries none
	// (organize's spelling 2, where the envelope distributes the type).
	Type string
	// Tags are the bare / quoted identifier terms after the id, decoded, in
	// box order. Bare is ALWAYS a tag (G9) — a tag literally named `status`
	// is the tag `status`; a field is only ever addressed with an operator.
	Tags []string
	// Atoms are the `name=value` field predicates, in box order.
	Atoms []Atom
}

// An Atom is one ground `name=value` field of a Literal, both sides decoded.
type Atom struct {
	Name  string
	Value string
}

// ParseLiteral parses a box INTERIOR (the text between `[` and `]`, brackets
// excluded) as a trellis Group and projects it to a Literal, rejecting with
// a bad request NAMING THE OFFENDING TERM anything outside the ground subset
// (see Literal). The first term must be the object id (a bare or quoted
// identifier); an empty interior is an error. A SyntaxError offset is
// relative to the bracketed form (one past the interior's own offset).
func ParseLiteral(interior string) (Literal, error) {
	lit, rest, err := ParseLiteralPrefix("[" + interior + "]")
	if err != nil {
		return Literal{}, err
	}
	if strings.TrimSpace(rest) != "" {
		return Literal{}, errors.BadRequestf("box literal %q: unexpected trailing input %q", interior, rest)
	}
	return lit, nil
}

// ParseLiteralPrefix parses the LEADING `[…]` group of src (after optional
// whitespace) with the real trellis parser — so quoted content, escapes
// (`\"`), and nested brackets are read by the one lexer, never re-scanned by
// a caller — projects it to a Literal, and returns the unparsed remainder
// (an organize box's description trailer, untrimmed). The projection is
// ParseLiteral's; a src that does not open with a group is a bad request
// wrapping the *SyntaxError.
func ParseLiteralPrefix(src string) (Literal, string, error) {
	p := &parser{src: []rune(src)}
	p.skipSPOpt()
	start := p.pos
	group, ok := p.parseGroup()
	if !ok {
		return Literal{}, "", errors.BadRequestf(
			"box literal: %w", p.syntaxError("expected a `[…]` group"),
		)
	}
	interior := string(p.src[start+1 : p.pos-1])
	lit, err := projectLiteral(group, interior)
	if err != nil {
		return Literal{}, "", err
	}
	return lit, string(p.src[p.pos:]), nil
}

// projectLiteral applies the groundness bar to a parsed Group; interior is
// the group's source text, quoted in diagnostics.
func projectLiteral(group Group, interior string) (Literal, error) {
	alts, ok := group.Body.(Alternatives)
	if !ok {
		return Literal{}, errors.BadRequestf(
			"box literal %q: %s is not ground (a box holds an id, a type, tags, "+
				"and name=value atoms; not a subpath or version subpath)",
			interior, groupBodyString(group.Body),
		)
	}
	if len(alts.Alts) != 1 {
		return Literal{}, errors.BadRequestf(
			"box literal %q: OR-alternatives (`,`) are not ground", interior,
		)
	}

	var lit Literal
	for i, term := range alts.Alts[0].Terms {
		if term.Negate || term.Exact {
			return Literal{}, notGround(interior, term, "a `^`/`=` prefix is a query decoration")
		}
		if i == 0 {
			id, ok := plainIdent(term.Basic)
			if !ok {
				return Literal{}, notGround(interior, term, "the first term must be the object id")
			}
			lit.ID = id
			continue
		}
		switch b := term.Basic.(type) {
		case TypeBasicTerm:
			if b.Sigil != nil {
				return Literal{}, notGround(interior, term, "a sigil is a version-set scope")
			}
			if lit.Type != "" {
				return Literal{}, notGround(interior, term, "a box carries at most one `!type`")
			}
			lit.Type = b.Type.Name
		case FieldPredBasicTerm:
			atom, why := groundAtom(b.FieldPred)
			if why != "" {
				return Literal{}, notGround(interior, term, why)
			}
			lit.Atoms = append(lit.Atoms, atom)
		default:
			tag, ok := plainIdent(term.Basic)
			if !ok {
				return Literal{}, notGround(interior, term, "not an id, `!type`, tag, or name=value atom")
			}
			lit.Tags = append(lit.Tags, tag)
		}
	}
	return lit, nil
}

// plainIdent projects a sigil-free bare or quoted identifier term to its
// decoded text — the shape an object id and a tag share.
func plainIdent(b BasicTerm) (string, bool) {
	switch b := b.(type) {
	case IdentBasicTerm:
		if b.Sigil == nil {
			return b.Ident.Name, true
		}
	case QuotedRefBasicTerm:
		if b.Sigil == nil {
			return b.Ref.Value, true
		}
	}
	return "", false
}

// groundAtom checks a field predicate against the atom bar — `=` with one
// scalar (bare or quoted) value — returning the reason it fails when it does.
func groundAtom(fp FieldPred) (Atom, string) {
	if fp.Op != FieldOpEq {
		return Atom{}, "only `=` is ground (`" + fp.Op.String() + "` is a query operator)"
	}
	if fp.List {
		return Atom{}, "a value list is not ground"
	}
	switch v := fp.Values[0].(type) {
	case Bareword:
		return Atom{Name: fp.Field.Name, Value: v.Name}, ""
	case StringValue:
		return Atom{Name: fp.Field.Name, Value: v.Value}, ""
	default:
		return Atom{}, "the value must be a plain or quoted scalar"
	}
}

func notGround(interior string, term Term, why string) error {
	return errors.BadRequestf(
		"box literal %q: term `%s` is not ground: %s", interior, termString(term), why,
	)
}

// WriteLiteral renders lit as a box interior WITHOUT the enclosing brackets
// (the caller writes those, alongside whatever trails the box): the id, then
// `!type`, then each tag, then each `name=value` atom, single-space
// separated. Every slot is spelled through QuoteIfNeeded, so the output
// re-parses (ParseLiteral) to the same Literal.
func WriteLiteral(b *strings.Builder, lit Literal) {
	b.WriteString(QuoteIfNeeded(lit.ID))
	if lit.Type != "" {
		b.WriteString(" !")
		b.WriteString(lit.Type)
	}
	for _, tag := range lit.Tags {
		b.WriteByte(' ')
		b.WriteString(QuoteIfNeeded(tag))
	}
	for _, atom := range lit.Atoms {
		b.WriteByte(' ')
		b.WriteString(QuoteIfNeeded(atom.Name))
		b.WriteByte('=')
		b.WriteString(QuoteIfNeeded(atom.Value))
	}
}

// QuoteIfNeeded spells s so the lexer reads it back as exactly one
// identifier-shaped token with content s: bare when s already lexes as a
// single Ident (every rune passes IsIdentRuneAt — so a reserved rune,
// whitespace, or a term-final sigil forces quoting), else as a doddish
// String (double quotes; backslash escapes for `"`, `\`, and the control
// runes decodeEscape reverses). The empty string is quoted (`""`) so it
// survives as a token at all. This is the ONE quoting rule for box ids,
// tags, atom names/values, and organize's heading values (design G9).
func QuoteIfNeeded(s string) string {
	if isBareIdent(s) {
		return s
	}
	return quoteString(s)
}

func isBareIdent(s string) bool {
	if s == "" {
		return false
	}
	rs := []rune(s)
	for i := range rs {
		if !IsIdentRuneAt(rs, i) {
			return false
		}
	}
	return true
}

// quoteString is decodeEscape's writer half: the doddish String spelling of s.
// The writer always emits double quotes; the reader (parseString) also
// accepts a single-quoted String, which round-trips back to this form.
func quoteString(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '"':
			b.WriteString(`\"`)
		case '\\':
			b.WriteString(`\\`)
		case '\n':
			b.WriteString(`\n`)
		case '\t':
			b.WriteString(`\t`)
		case '\r':
			b.WriteString(`\r`)
		case '\a':
			b.WriteString(`\a`)
		case '\b':
			b.WriteString(`\b`)
		case '\f':
			b.WriteString(`\f`)
		case '\v':
			b.WriteString(`\v`)
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('"')
	return b.String()
}

// ParseTerm parses src as exactly ONE trellis term — a single step of a
// single term, with no leading combinator — the shape organize's envelope
// fields (`_base` → DigestTerm, `_type` → TypeTerm) and heading values
// (`=value`, `tag`, `"_ inbox"`) take. Anything wider is a bad request.
func ParseTerm(src string) (Term, error) {
	q, err := Parse(src)
	if err != nil {
		// BadRequestf formats via fmt.Errorf, so %w keeps the *SyntaxError
		// reachable through errors.As.
		return Term{}, errors.BadRequestf("%w", err)
	}
	if q.Path.Leading != nil || len(q.Path.Steps) != 1 || len(q.Path.Steps[0].Terms) != 1 {
		return Term{}, errors.BadRequestf("trellis: %q is not a single term", src)
	}
	return q.Path.Steps[0].Terms[0], nil
}

// ---- diagnostics: spelling a term back for an error message ---------------

// termString re-spells a parsed Term in its grammar form, for diagnostics
// (ParseLiteral names the offending term). DIAGNOSTIC-ONLY: this is not a
// canonical printer and is not a Query.String() — nested groups are elided
// to `[…]` (the message points at the term, not at its interior) and no
// spelling here is promised to re-parse.
func termString(t Term) string {
	var b strings.Builder
	if t.Negate {
		b.WriteByte('^')
	}
	if t.Exact {
		b.WriteByte('=')
	}
	switch bt := t.Basic.(type) {
	case GroupBasicTerm:
		b.WriteString("[…]")
	case QualifierBasicTerm:
		b.WriteString(bt.String())
	case FieldPredBasicTerm:
		fp := bt.FieldPred
		b.WriteString(fieldNameString(fp.Field))
		b.WriteString(fp.Op.String())
		if fp.List {
			b.WriteByte('[')
		}
		for i, v := range fp.Values {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(valueString(v))
		}
		if fp.List {
			b.WriteByte(']')
		}
	case TypeBasicTerm:
		b.WriteString("!" + bt.Type.Name + sigilString(bt.Sigil))
	case DigestBasicTerm:
		b.WriteString("@" + bt.Digest.Digest + sigilString(bt.Sigil))
	case MarklBasicTerm:
		b.WriteString(marklString(bt.Markl) + sigilString(bt.Sigil))
	case QuotedRefBasicTerm:
		b.WriteString(quoteString(bt.Ref.Value) + sigilString(bt.Sigil))
	case IdentBasicTerm:
		b.WriteString(bt.Ident.Name + sigilString(bt.Sigil))
	case SigilBasicTerm:
		b.WriteString(bt.Sigil.Runes)
	}
	return b.String()
}

func groupBodyString(body GroupBody) string {
	switch body.(type) {
	case SubPath:
		return "a subpath"
	case VersionSub:
		return "a version subpath"
	default:
		return "the group body"
	}
}

func fieldNameString(f FieldName) string {
	if f.Quoted {
		return quoteString(f.Name)
	}
	return f.Name
}

func valueString(v Value) string {
	switch v := v.(type) {
	case Qualifier:
		return v.String()
	case MarklTerm:
		return marklString(v)
	case StringValue:
		return quoteString(v.Value)
	case DigestTerm:
		return "@" + v.Digest
	case Bareword:
		return v.Name
	default:
		return "?"
	}
}

func marklString(m MarklTerm) string {
	if m.PurposeQuoted {
		return quoteString(m.Purpose) + "@" + m.Digest
	}
	return m.Purpose + "@" + m.Digest
}

func sigilString(s *Sigil) string {
	if s == nil {
		return ""
	}
	return s.Runes
}
