// Code generated by dagnabit (0.5.0+dirty); DO NOT EDIT.

package traversal_serve

import internal "code.linenisgreat.com/cutting-garden/internal/traversal_serve"

// FacetCountsParams is the facets.counts request payload
// (FacetCounter.FacetCounts). An absent/empty Filter matches
// everything (RFC 0012 §6).
type FacetCountsParams = internal.FacetCountsParams

// FacetCountsResult is the facets.counts response. OK false means "I
// do not summarize this node; fall back to the framework fold over
// nodes.list" (RFC 0012 §4–§5). Every dimension key in Summary MUST be
// declared in the initialize facets block.
type FacetCountsResult = internal.FacetCountsResult

// FacetDimensionView is the wire form of
// cutting_garden_plugins.FacetDimension (RFC 0013 §Wire encodings):
// Values present ≙ a CLOSED domain (RFC 0012 §2);
// revalidate_after_seconds (absent ≙ 0) marks a VOLATILE dimension
// (RFC 0012 §11.3) — the additive-field precedent of RFC 0013
// §Compatibility.
type FacetDimensionView = internal.FacetDimensionView

// FacetValueView is the wire form of cutting_garden_plugins.FacetValue
// (RFC 0013 §Wire encodings): Order is omitted when 0 ("no hint").
type FacetValueView = internal.FacetValueView

// FacetVersionParams is the facets.version request payload
// (FacetVersioner.FacetVersion).
type FacetVersionParams = internal.FacetVersionParams

// FacetVersionResult is the facets.version response: the RFC 0012 §11
// change token. OK false means no token — the host's cache falls back
// to its TTL.
type FacetVersionResult = internal.FacetVersionResult

// Handler serves a peer's incoming JSON-RPC requests and notifications,
// one at a time in arrival order (a plugin MAY process pipelined
// requests sequentially — RFC 0013 §Framing). result is marshaled as
// the JSON-RPC response; a returned *RPCError is sent with its code and
// message verbatim, any other error becomes a -32603 internal error
// (RFC 0013 §Errors). For a notification (shutdown) the return values
// are discarded — there is no response to carry them.
type Handler = internal.Handler

// HandlerFunc adapts a function to Handler.
type HandlerFunc = internal.HandlerFunc

// Handshake is the parsed announce line — everything the host needs to
// dial the plugin's rendezvous socket.
type Handshake = internal.Handshake

// InitializeParams is the host→plugin initialize request payload
// (RFC 0013 §Handshake).
type InitializeParams = internal.InitializeParams

// InitializeResult is the plugin's initialize response. All three
// declaration blocks (node_types, facets, bodies) ride here because
// their in-process contracts are stable for the plugin's lifetime —
// there are no types.list / facets.describe round trips.
type InitializeResult = internal.InitializeResult

// LabelsResolveParams is the labels.resolve request payload
// (FacetLabeler.ResolveFacetLabels): one labelled dimension and the
// value keys to name.
type LabelsResolveParams = internal.LabelsResolveParams

// LabelsResolveResult is the labels.resolve response. A key absent
// from Labels (or an empty label) means "no label" and the host falls
// back to the key; the whole method is presentation-only and non-fatal
// (RFC 0012 §7).
type LabelsResolveResult = internal.LabelsResolveResult

// LeafReadParams is the leaf.read request payload (LeafReader.ReadLeaf).
type LeafReadParams = internal.LeafReadParams

// LeafReadResult is the leaf.read response. OK false (all other fields
// absent) means "not a fetchable leaf — fall back to the child
// listing", NOT an error; a JSON-RPC error is reserved for unexpected
// failures, exactly as the Go contract reserves non-nil err.
type LeafReadResult = internal.LeafReadResult

// NodeCreateChildParams is the node.create_child request payload
// (ContainerCreator, cutting-garden#143): create a node of Type under
// the Container URI, the source assigning the created node's identity.
type NodeCreateChildParams = internal.NodeCreateChildParams

// NodeCreateChildResult reports the URI the source assigned. MUST be
// non-empty and credential-free.
type NodeCreateChildResult = internal.NodeCreateChildResult

// NodeCreateParams is the node.create request payload
// (NodeMutator, FDR 0020): strict create, no upsert — an existing URI
// is an error. Type MUST be a declared node_types tag. The result is
// empty.
type NodeCreateParams = internal.NodeCreateParams

// NodeDeleteParams is the node.delete request payload. The result is
// empty.
type NodeDeleteParams = internal.NodeDeleteParams

// NodePatchParams is the node.patch request payload: a partial-field
// update of an existing node (NodeMutator.PatchNode — only the fields
// named in the body change; the body format is plugin-defined). An
// empty body is a bad-request error.
type NodePatchParams = internal.NodePatchParams

// NodePatchResult reports which field keys the plugin ACTUALLY applied
// (NodeMutator.PatchNode's applied, cutting-garden#182). Applied is a
// POINTER so the three states the Go contract distinguishes survive the
// wire: a present list (possibly empty) is authoritative, and an OMITTED
// key means "this plugin does not report applied fields" — the state a
// peer written against RFC 0013 before this field existed lands in. A
// plain []string would collapse that absence into an empty list and
// report every such peer's successful patch as a no-op, which is the
// very false signal #182 exists to remove.
type NodePatchResult = internal.NodePatchResult

// NodePutParams is the node.put request payload: full-replace an
// existing leaf's body (NodeMutator.PutNode — the body represents the
// complete desired state). A non-existent URI is an error. The result
// is empty.
type NodePutParams = internal.NodePutParams

// NodeTypeBodyView is the wire form of
// cutting_garden_plugins.NodeTypeBody, carried in the initialize
// bodies block. Example is any JSON value (the domain field is
// JSON-marshalable by contract); absent when the plugin offers no
// structured form.
type NodeTypeBodyView = internal.NodeTypeBodyView

// NodeTypeFacetsView is the wire form of
// cutting_garden_plugins.NodeTypeFacets: one node type's declared
// facet dimensions, carried in the initialize facets block.
type NodeTypeFacetsView = internal.NodeTypeFacetsView

// NodeTypeView is the wire form of cutting_garden_plugins.NodeType
// (RFC 0013 §Wire encodings). An absent mime_type on a leaf means
// unspecified — the HOST applies the octet-stream default via
// NodeType.BodyMimeType; the plugin never sends the default.
type NodeTypeView = internal.NodeTypeView

// NodeView is the wire form of cutting_garden_plugins.Node (RFC 0013
// §Wire encodings): the URI as an RFC 3986 string, Facets omitted when
// the node contributes nothing.
type NodeView = internal.NodeView

// NodesListParams is the nodes.list request payload: the URI whose
// immediate children to enumerate (RootLister.ListRoots — one level,
// lazy). The plugin fails a URI whose scheme it did not advertise with
// CodeInvalidParams.
type NodesListParams = internal.NodesListParams

// NodesListResult is the nodes.list response: the immediate children
// of the requested URI. A leaf (or empty container) returns an empty
// list.
type NodesListResult = internal.NodesListResult

// Peer is one side of an RFC 0013 session: a JSON-RPC peer over a byte
// stream, framing exactly one message per newline-terminated line
// (§Framing). Unlike capture_serve's datagram peer there is no fd
// passing and no message-size datagram truncation — the transport is
// any io.ReadWriteCloser (an AF_UNIX SOCK_STREAM conn in production,
// net.Pipe in tests). The read loop correlates responses to pending
// Calls by id — never by arrival order — while the serve loop
// dispatches requests to the Handler sequentially.
type Peer = internal.Peer

// PeerOption configures NewPeer.
type PeerOption = internal.PeerOption

// PluginInfo identifies the plugin binary; diagnostic only.
type PluginInfo = internal.PluginInfo

// PluginSpec is what the adapter needs to launch its plugin — the
// runtime projection of a [[traversal_plugins]] stanza (RFC 0013 §Host
// integration). The config decode that produces it (tommy codegen, the
// raw config_section extraction) arrives with the registration wiring;
// this struct stays tommy-free so the adapter carries no codegen
// dependency.
type PluginSpec = internal.PluginSpec

// PluginStanza is one `[[plugins]]` stanza of the cutting-garden config:
// the declaration that a wire plugin binary serves some schemes via a
// spawned command, and which wire protocol(s) it speaks (Protocols).
// This is the cutting-garden#146 slice 2 generalization of the
// RFC 0013-only `[[traversal_plugins]]` stanza into ONE stanza shape
// covering both RFC 0008 (capture) and RFC 0013 (traversal) — a single
// config entry per plugin binary, from which the host launches
// capture-serve and/or traversal-serve sessions as needed.
// `[[traversal_plugins]]` remains a compatibility alias decoded into
// this same type (cgconfig.ConfigV0.TraversalPlugins): an entry there
// that omits protocols — the shape every existing config has, since
// the key did not exist before this generalization — defaults to
// Protocols = [ProtocolTraversal] via EffectiveProtocols, so existing
// configs keep working unmodified. (An entry that explicitly sets
// protocols under the legacy table is honored as written; the default
// only fills the gap left by an absent key.)
//
// Command's interpretation depends on which table decoded the stanza:
// a [[traversal_plugins]] (legacy alias) entry's Command is the full
// argv verbatim, unchanged from RFC 0013's original convention (e.g.
// ["fj-cg", "traversal-serve"]) — the plugin-launching code appends
// nothing. A [[plugins]] (general) entry's Command is instead the BASE
// binary invocation WITHOUT a subcommand (e.g. ["chrest"]); the host
// appends the protocol-specific subcommand itself — "traversal-serve"
// for ProtocolTraversal, "capture-serve" (attempted first) or
// "capture-batch" (the RFC 0008 §Migration v1 fallback) for
// ProtocolCapture. This lets one [[plugins]] Command work for either or
// both protocols without the caller having to know which subcommand
// name to embed.
//
// The aggregator (cgconfig.ConfigV0) embeds slices of these at the top
// level; tommy's generated codec for those fields delegates to this
// type's generated DecodePluginStanzaInto.
type PluginStanza = internal.PluginStanza
type PluginStanzaDocument = internal.PluginStanzaDocument

// PredicateView is the wire form of
// cutting_garden_plugins.FacetPredicate: one equality constraint of a
// facets.counts filter.
type PredicateView = internal.PredicateView

// RPCError is a JSON-RPC error crossing the peer in either direction: a
// Handler returns *RPCError to pin its error response's wire code and
// message, and Call surfaces a received error response as *RPCError so
// callers can branch on the RFC 0013 §Errors codes
// (CodeUnsupportedVersion, CodeInvalidParams, …) via errors.As or
// CodeOf.
type RPCError = internal.RPCError

// RootsListResult is the roots.list response: the plugin's top-level
// entry points (RootProvider.Roots), possibly empty. Each MUST be
// credential-free. The request carries empty params.
type RootsListResult = internal.RootsListResult

// ServeConfig configures Serve, the plugin side of an RFC 0013 session.
type ServeConfig = internal.ServeConfig

// Session is a launched traversal plugin: the initialized JSON-RPC
// peer plus the child process whose lifecycle Close manages. The host
// is the sole request initiator in v1, so the peer carries no handler;
// drive the session with Call.
type Session = internal.Session

// WirePlugin adapts a launched session into the full capability
// surface. It implements EVERY optional interface; unadvertised
// capabilities return the contract's decline value (ok=false / empty
// roots / nil declarations) WITHOUT a wire call, so type-assertion
// probing over-matches harmlessly — the decline paths are exactly the
// "plugin omits the interface" fallbacks. Mutations on a plugin that
// did not advertise mutate return an error (writes never silently
// decline).
type WirePlugin = internal.WirePlugin

// AnnounceLine renders the single stdout line a plugin prints once its
// rendezvous socket is listening (newline included).
var AnnounceLine = internal.AnnounceLine

// CodeOf extracts the JSON-RPC error code from err's chain; ok is false
// when no *RPCError is present (a transport-level failure rather than a
// wire error response).
var CodeOf = internal.CodeOf

// CookieFromEnv reads the launch cookie a plugin must echo on its
// announce line. Absence means the process was not launched by a host:
// the caller MUST exit non-zero without touching stdout.
var CookieFromEnv = internal.CookieFromEnv
var DecodePluginStanza = internal.DecodePluginStanza
var DecodePluginStanzaInto = internal.DecodePluginStanzaInto
var EncodePluginStanzaFrom = internal.EncodePluginStanzaFrom

// FacetDimensionViewFrom projects a declared dimension onto the wire.
// RevalidateAfter is truncated to whole seconds (the wire unit).
var FacetDimensionViewFrom = internal.FacetDimensionViewFrom

// FacetFilterFrom is the inverse of PredicateViewsFrom: an absent or
// empty wire filter becomes the empty FacetFilter, whose Matches
// accepts everything.
var FacetFilterFrom = internal.FacetFilterFrom

// FacetValueViewFrom projects one facet value onto the wire.
var FacetValueViewFrom = internal.FacetValueViewFrom

// Launch spawns argv as a traversal plugin and completes the RFC 0013
// bring-up: export a fresh cookie, read the announce line from the
// child's stdout under announceTimeout, validate the version token,
// dial, and initialize (passing configTOML through, validating the
// schema echo). Any failure — the subcommand missing (immediate exit,
// stdout EOF), stdout pollution, a cookie/version/schema mismatch, or a
// deadline — kills the child, reaps it, and returns an error: with no
// fallback protocol, every Launch error means "plugin unavailable". The
// child's stderr passes through for diagnostics; its stdin is held open
// (EOF on it is a shutdown signal, sent by Close).
var Launch = internal.Launch

// ListenRendezvous binds a fresh unix stream rendezvous socket in a new
// 0700 temp directory at a path short enough for sun_path. It prefers
// $XDG_RUNTIME_DIR (user-private tmpfs) and falls back to /tmp; a base
// whose paths would overflow sun_path is skipped (never bind inside a
// deeply-nested worktree tmp). cleanup closes the listener and removes
// the directory (unlinking the socket).
var ListenRendezvous = internal.ListenRendezvous

// NewPeer wraps rw as an RFC 0013 peer and starts its read and serve
// loops. Close the peer (or just close rw) to stop both.
var NewPeer = internal.NewPeer

// NewWirePlugin returns the adapter for spec. It does NOT spawn — the
// session is lazy (the first call that needs the wire launches it), so
// registration stays cheap and offline.
var NewWirePlugin = internal.NewWirePlugin

// NodeTypeBodyViewFrom projects one writable type's body description
// onto the wire.
var NodeTypeBodyViewFrom = internal.NodeTypeBodyViewFrom

// NodeTypeFacetsViewFrom projects one type's facet declaration onto
// the wire.
var NodeTypeFacetsViewFrom = internal.NodeTypeFacetsViewFrom

// NodeTypeViewFrom projects a declared NodeType onto the wire. A leaf
// declared with the explicit octet-stream default is normalized to
// unspecified, enforcing the plugin-never-sends-the-default rule.
var NodeTypeViewFrom = internal.NodeTypeViewFrom

// NodeViewFrom projects a Node onto the wire.
var NodeViewFrom = internal.NodeViewFrom

// PredicateViewsFrom projects a FacetFilter onto the wire. The empty
// filter (nil or zero-length) projects to nil, which marshals as an
// absent filter — both mean matches-everything (RFC 0012 §6).
var PredicateViewsFrom = internal.PredicateViewsFrom

// SectionTOML extracts one named top-level section from the raw config
// file bytes, WRAPPER-STRIPPED per RFC 0013 §initialize: the returned
// text's keys are section-relative — `[fj]` scalars become top-level
// keys, `[[fj.roots]]` becomes `[[roots]]`, `[fj.sub.x]` becomes
// `[sub.x]` — so the plugin never sees its own section name, mirroring
// what the in-process config decoder hands a linked plugin. An absent
// section returns ("", nil).
//
// The extraction is line-based over TOML's header grammar (headers are
// single physical lines), with quote-aware scanning so quoted keys
// containing '.', ']', or '#' cannot confuse it. section MUST be a bare
// TOML key (PluginStanza.Validate enforces the same grammar); a
// top-level `[[section]]` array-of-tables cannot be represented
// wrapper-stripped and is rejected — a plugin wanting repeated tables
// uses a sub-array (`[[section.roots]]`).
var SectionTOML = internal.SectionTOML

// Serve runs one RFC 0013 session over rw. It builds the initialize
// declaration once from cfg.Plugin, then serves the §Method set until
// the session ends. Returns nil for a graceful end — the shutdown
// notification (after the request queue drains) or stream EOF after
// shutdown — and the terminal reason otherwise: ctx cancellation, EOF
// before shutdown (host death is cancellation, §Session lifecycle), or
// a stream error.
var Serve = internal.Serve

// ValidateStanzas enforces the cross-stanza invariants the aggregated
// config's Validate delegates here: unique names, unique schemes —
// across BOTH the general []PluginStanza slice (the `[[plugins]]`
// table) and the legacy slice (the `[[traversal_plugins]]`
// compatibility alias, cutting-garden#146 decision 2). A name or scheme
// may not be claimed twice regardless of which table declared it.
// (Scheme clashes against LINKED plugins surface at registration, which
// consults the live registry.)
var ValidateStanzas = internal.ValidateStanzas

// WithHandler makes the peer serve incoming requests — the plugin role.
// Without it the peer is client-only (the host role: the sole request
// initiator in v1) and answers any incoming request with
// CodeMethodNotFound.
var WithHandler = internal.WithHandler

// CapContainerCreate gates node.create_child — server-assigned
// identity creation (ContainerCreator, cutting-garden#143). An
// additive capability token under RFC 0013 §Compatibility.
const CapContainerCreate = internal.CapContainerCreate
const CapFacetCounts = internal.CapFacetCounts
const CapFacetLabels = internal.CapFacetLabels
const CapFacetVersion = internal.CapFacetVersion
const CapLeafRead = internal.CapLeafRead
const CapMutate = internal.CapMutate
const CapRoots = internal.CapRoots
const CodeInternalError = internal.CodeInternalError
const CodeInvalidConfig = internal.CodeInvalidConfig
const CodeInvalidParams = internal.CodeInvalidParams
const CodeMethodNotFound = internal.CodeMethodNotFound
const CodeUnsupportedVersion = internal.CodeUnsupportedVersion

// CookieEnv is the magic-cookie environment variable (RFC 0013
// §Launch and rendezvous). A plugin invoked without it MUST exit
// non-zero without printing to stdout — the guard against
// accidental direct invocation.
const CookieEnv = internal.CookieEnv

// HandshakeNetwork is the announce line's network field: the
// rendezvous socket is AF_UNIX SOCK_STREAM ("unix") — a byte
// stream, unlike RFC 0008's SEQPACKET, because NDJSON framing
// needs no datagram boundaries and streams work on every platform
// (including darwin, where SEQPACKET does not exist).
const HandshakeNetwork = internal.HandshakeNetwork

// HandshakeSubprotocol terminates the announce line, naming the
// protocol spoken over the dialed socket.
const HandshakeSubprotocol = internal.HandshakeSubprotocol
const MethodFacetCounts = internal.MethodFacetCounts
const MethodFacetVersion = internal.MethodFacetVersion
const MethodInitialize = internal.MethodInitialize
const MethodLabelsResolve = internal.MethodLabelsResolve
const MethodLeafRead = internal.MethodLeafRead
const MethodNodeCreate = internal.MethodNodeCreate
const MethodNodeCreateChild = internal.MethodNodeCreateChild
const MethodNodeDelete = internal.MethodNodeDelete
const MethodNodePatch = internal.MethodNodePatch
const MethodNodePut = internal.MethodNodePut
const MethodNodesList = internal.MethodNodesList
const MethodRootsList = internal.MethodRootsList
const MethodShutdown = internal.MethodShutdown

// ProtocolCapture declares the plugin speaks the RFC 0008 capture
// transport (a capture-serve session, with the RFC 0008 §Migration
// v1 capture-batch fallback).
const ProtocolCapture = internal.ProtocolCapture

// ProtocolTraversal declares the plugin speaks the RFC 0013
// traversal transport (a traversal-serve session).
const ProtocolTraversal = internal.ProtocolTraversal

// SchemaV1 is the protocol version token negotiated by initialize
// (RFC 0013 §Handshake).
const SchemaV1 = internal.SchemaV1
