// Code generated by dagnabit (0.5.0+182545a); DO NOT EDIT.

package cutting_garden_plugins

import internal "code.linenisgreat.com/cutting-garden/internal/cutting_garden_plugins"

// AtomicBulkMutator marks a BulkMutator whose backend CAN honor BulkAtomic
// for at least some request shapes — the Go-side signal the server
// type-asserts to advertise the bulk-atomic capability token (RFC 0017
// §Atomicity). It is probed by type assertion exactly as BulkMutator and
// NodeMutator (RFC 0009's growth-by-new-interfaces policy).
//
// A BulkMutator WITHOUT this marker MUST reject every atomic request (the
// reject-never-downgrade floor). WITH it, the plugin advertises bulk-atomic
// but MAY still reject a SPECIFIC request it cannot transact, returning
// ErrBulkAtomicUnsupported — the marker is a "can, for some shapes" claim,
// not "can, for all". BulkAtomicCapable gates the advertisement on runtime
// state (a backend whose transaction support depends on the account or
// server); a plugin that can always transact simply returns true, and one
// that computes it once may cache it — the server calls it when building
// the initialize capability list, not per request.
type AtomicBulkMutator = internal.AtomicBulkMutator

// BodyDescriber is the OPTIONAL capability a write-capable plugin implements
// to describe the create/update payloads of its writable node types, for the
// mcp server's `describe_node_types` schema tool. It is probed by type
// assertion exactly as NodeMutator / RootLister are; a plugin that omits it
// contributes types (from RootLister.Types) without payload detail.
//
// A type is reported "writable" by the schema tool iff DescribeBodies
// returns an entry for its tag — so a plugin lists exactly the types its
// NodeMutator can currently create (e.g. caldav describes its object leaf
// but not its calendar container, which awaits MKCALENDAR).
type BodyDescriber = internal.BodyDescriber

// BoxAtom is one rendered field atom in an organize espalier box interior — a
// friendly, editable presentation of (part of) a node's field. Name is the
// atom's key as it appears in the box (e.g. "date_start"); Value is its
// rendered form (e.g. "2026-08-15"). A plugin MAY split one substrate field
// into several atoms (a caldav DTSTART → date_start + time_start).
type BoxAtom = internal.BoxAtom

// BulkAtomicity selects how a BulkMutate call is expected to complete
// (RFC 0017 §Atomicity semantics). The zero value is NOT a valid request
// value — a caller MUST set one of the two constants; a plugin receiving
// neither MUST reject the request as a bad request. The best-effort
// DEFAULT for a caller that omits it lives at the tool/parameter layer,
// never in this Go zero value.
type BulkAtomicity = internal.BulkAtomicity

// BulkFailure records one targeted node's failure inside a best-effort
// result.
type BulkFailure = internal.BulkFailure

// BulkMutator is the OPTIONAL bulk write capability (RFC 0017). Probed by
// type assertion exactly as NodeMutator. It deliberately does NOT embed
// NodeMutator: the two are independent narrow capabilities (RFC 0009's
// growth-by-new-interfaces policy), with BulkMutator's per-op semantics
// defined as NodeMutator's verbatim regardless of whether NodeMutator is
// also implemented.
type BulkMutator = internal.BulkMutator

// BulkOp is one mutation, addressed exactly as a NodeMutator call is. Its
// per-verb Body/Type meaning is NodeMutator's verbatim (FDR 0020) — this
// type batches those semantics, it does not redefine them.
type BulkOp = internal.BulkOp

// BulkOpKind is the mutation verb of one op — the same four verbs
// NodeMutator defines, applied per targeted node.
type BulkOpKind = internal.BulkOpKind

// BulkRequest is one bulk-mutate call. EXACTLY ONE of Ops or Sweep MUST be
// set (both, or neither, is a bad request); Ops, when set, MUST be
// non-empty.
type BulkRequest = internal.BulkRequest

// BulkResult is a BulkMutate call's outcome; its shape differs by
// Atomicity (RFC 0017 §Atomicity semantics). AppliedNodes is named for
// its unit (NODES) to avoid colliding with PatchNode's field-level applied
// (#182/#184).
type BulkResult = internal.BulkResult

// BulkSweep selects a node set by predicate — a container Root plus a
// FacetFilter (RFC 0012 §6, reused verbatim) — and applies one Op
// template to every match. The plugin owns the enumeration: the framework
// MUST NOT resolve the match set and hand over a URI list (RFC 0017
// §Selection), which is what lets a plugin that expresses "match and
// apply" as one backend operation genuinely promise bulk-atomic.
type BulkSweep = internal.BulkSweep

// CapturePlugin walks one capture root into the destination store,
// emitting entries and live stream events. Plugins MAY support only
// capture or only restore.
type CapturePlugin = internal.CapturePlugin

// CaptureRootRequest is what a CapturePlugin needs to walk one
// capture root: the source URL (already parsed; may be schemeless)
// and the destination blob store. Context is the command's cancelable
// context; plugins MUST observe it on long-running I/O (large file
// copies, etc.) so SIGINT/SIGTERM unwinds promptly.
type CaptureRootRequest = internal.CaptureRootRequest

// CaptureRootResult is what a CapturePlugin produces from one root:
// the entries to be folded into the receipt and a count of per-entry
// failures the stream already reported.
type CaptureRootResult = internal.CaptureRootResult

// Codec is a reversible M<->N bridge between a node type's STORED substrate fields
// and the PRESENTATION fields the renderer shows (FDR 0025). Format projects the
// stored fields onto presentation fields (a caldav DTSTART -> date_start +
// time_start; a lowercase status -> canonical-cased status; CATEGORIES -> tags);
// Parse inverts an edit back onto the stored fields, preserving the parts the
// presentation did not carry (a date edit keeps the clock and TZID). The two are
// reversible: for the fields a codec owns, Parse(Format(stored), stored) restores
// the stored values.
//
// A codec may be M<->N: it reads several stored fields and produces several
// presentation fields. The identity case (one stored field <-> one presentation
// field, value unchanged) is IdentityCodec below.
type Codec = internal.Codec

// ContainerCreator is the OPTIONAL capability for sources that assign a
// created node's identity server-side (a feed subscription's server-chosen
// feed id, a forge's issue number, a zettel pool's next id): create a child
// under container, returning the URI the source chose. It is probed by type
// assertion exactly as NodeMutator is, and complements — never replaces —
// CreateNode's caller-names-the-URI form; a plugin implements one, the
// other, or both, per node type, and declares which types are
// server-assigned via NodeTypeBody.ServerAssignedIdentity (cutting-garden#143).
//
// The container param is fully generic: any container node URI, including —
// under the roots-as-nodes direction (FDR 0022) — a root itself. Returning
// the resulting URI follows the shared convention that identity-affecting
// operations report the node's post-operation address.
type ContainerCreator = internal.ContainerCreator

// DateGranularity is a bucket coarseness for a FacetDate dimension: the
// --group-by qualifier spelling ("date_due=(month)") and the config default.
type DateGranularity = internal.DateGranularity

// DiffPlugin enumerates the current state at a location and returns
// entries in the same shape a CapturePlugin would produce, suitable
// for comparison against a receipt. Plugins MAY support diff without
// supporting capture or restore (e.g. a read-only HTTP listing
// plugin) or vice versa.
type DiffPlugin = internal.DiffPlugin

// DiffScanRequest is what a DiffPlugin needs to enumerate the
// current state at Dir and return entries that can be compared
// against ReceiptEntries. The plugin computes blob-ids using
// BlobStore (typically a discard-store wrapping the receipt's
// source store, so only the hash family matters). ReceiptEntries
// is provided so the plugin can run its own pre-walk validation
// (path sanitization etc.) before any I/O — diff is read-only and
// atomic.
type DiffScanRequest = internal.DiffScanRequest

// EnrichedLister is the OPTIONAL capability a plugin implements to serve a
// container's children ENRICHED — Facets and Fields populated — and
// optionally narrowed by filter, in ONE data-bearing fetch
// (cutting-garden#160). It is the efficient path for a plugin whose base
// ListRoots is deliberately metadata-only (caldav's hrefs-only listing,
// kept cheap for the bare/opt-out case): caldav's ListEnriched instead
// issues the single calendar-data REPORT foldCalendarFacets already uses
// for FacetCounts, projecting each object's parsed fields onto its Node
// rather than folding them into a histogram.
//
// Probed by type assertion exactly as FacetCounter is — the same
// capability-probe-with-honest-fallback shape (RFC 0012 §4–§5). A plugin
// without this capability is enriched host-side instead, from whatever
// Facets its plain ListRoots already populates (file, git, ytdlp all do);
// filtering then falls back to FacetFilter.Matches over those same Facets.
type EnrichedLister = internal.EnrichedLister

// FacetContainerBreakdown is one immediate child container's contribution
// to a FacetResult's Summary: how many of the matching nodes live under it.
// See RFC 0012 §13.
type FacetContainerBreakdown = internal.FacetContainerBreakdown

// FacetCounter is the OPTIONAL capability that returns a node's hoisted facet
// summary in one operation, without the framework walking the subtree — the
// PREFERRED path, size-agnostic (an atomic listing, an in-memory index, or a
// backend GROUP BY). A plugin that can only walk its tree lazily omits it and
// the framework folds Node.Facets over ListRoots instead. See RFC 0012 §4–§5.
type FacetCounter = internal.FacetCounter

// FacetDescriber is the OPTIONAL capability that declares a plugin's facet
// schema, symmetric with BodyDescriber. Probed by type assertion on an
// already-resolved plugin. See RFC 0012 §2.
type FacetDescriber = internal.FacetDescriber

// FacetDimension declares one aggregation axis of a node type. See RFC 0012 §2.
type FacetDimension = internal.FacetDimension

// FacetFilter is a set of predicates, AND-composed. The empty filter matches
// everything; a node matches the filter iff it matches EVERY predicate. See
// RFC 0012 §6.
type FacetFilter = internal.FacetFilter

// FacetHistogram is one dimension's aggregate: a count per value Key.
// See RFC 0012 §3.
type FacetHistogram = internal.FacetHistogram

// FacetKind classifies a dimension's VALUE SHAPE. Cardinality (one vs. many
// values per node) is the separate FacetDimension.Multi flag. See RFC 0012 §2.
type FacetKind = internal.FacetKind

// FacetLabeler is the OPTIONAL capability that resolves a labelled dimension's
// opaque value keys to human display names, in batch and presentation-only.
// See RFC 0012 §7.
type FacetLabeler = internal.FacetLabeler

// FacetPredicate is one equality constraint: a node matches when its
// Facets[Dimension] contains a FacetValue whose Key == Value. See RFC 0012 §6.
type FacetPredicate = internal.FacetPredicate

// FacetResult is a hoisted summary plus whether it covers the whole subtree.
// See RFC 0012 §5.
type FacetResult = internal.FacetResult

// FacetSummary is the aggregate of all dimensions over a node set, keyed by
// FacetDimension.Key. See RFC 0012 §3. The commutative, associative merge that
// hoists leaf summaries into a container summary (RFC 0012 §3–§4.2) arrives
// with the framework-fold consumer; the one-shot FacetCounter path builds its
// summary directly, so no merge helper is published yet.
type FacetSummary = internal.FacetSummary

// FacetValue is one node's membership in one bucket of one dimension — the
// unit a plugin attaches to Node.Facets and the framework counts. See
// RFC 0012 §1.
type FacetValue = internal.FacetValue

// FacetVersioner is the OPTIONAL capability that cheaply reports whether a
// node's subtree may have changed, so the framework's summary memoization
// (RFC 0012 §11) recomputes only when something moved instead of on every
// read. Probed by type assertion, like the other facet capabilities.
type FacetVersioner = internal.FacetVersioner

// FacetWrite declares how editing ONE facet dimension of a node type maps to a
// substrate write. It is layered onto the READ-side FacetDimension of the same
// (Tag, DimensionKey) — it never re-declares the dimension's shape — so the two
// schemas cannot drift (RFC 0012 §Write mapping). It is metadata only: the
// framework has no concept of domain transitions (FDR 0023), so the plugin's
// own write path owns whatever computation the substrate needs (timezone,
// clock-time preservation, id allocation); this record only DESCRIBES it.
type FacetWrite = internal.FacetWrite

// FacetWriteApplier is the capability that BUILDS the substrate patch for one
// facet-bucket move — the write-side execution counterpart of
// FacetWriteDescriber's declaration. It owns any bucket->value COMPLETION the
// substrate needs: a passthrough dimension (a status enum) writes the target
// bucket verbatim into the mapped field, while a date dimension splices the
// target period into the object's existing date, preserving day-of-month, clock
// time, and time zone (FDR 0023 "reschedule by move"). Because the plugin returns
// the finished patch body, the organize apply engine needs no knowledge of the
// substrate's patch shape or of any domain transition — the framework stays free
// of caldav's (or any plugin's) JSON layout (RFC 0009 no-inversion).
//
// Probed by type assertion on an already-resolved plugin, exactly like
// FacetWriteDescriber. A plugin that declares writable facets (FacetWriteDescriber
// with a non-none Mode) MUST also implement this — the apply engine rejects a
// writable-but-applier-less plugin loudly rather than guessing the patch shape.
type FacetWriteApplier = internal.FacetWriteApplier

// FacetWriteDescriber is the OPTIONAL capability that declares how a plugin's
// facet dimensions map to WRITES — the write-side extension of FacetDescriber's
// read-side schema (RFC 0012 §Write mapping, FDR 0023's organize mapping
// capability). Probed by type assertion on an already-resolved plugin, exactly
// like FacetDescriber. A plugin that serves no writable facets simply does not
// implement it.
type FacetWriteDescriber = internal.FacetWriteDescriber

// FacetWriteMode is the cardinality of writes a facet dimension supports — the
// write-side counterpart to FacetDimension.Multi (RFC 0012 §Write mapping,
// FDR 0023's organize mapping capability). It says how EDITING a node's
// membership in this dimension maps to a substrate write.
type FacetWriteMode = internal.FacetWriteMode

// FieldEdit is one changed box atom the framework asks a plugin to write: the
// atom's Name as it appears in the espalier box (e.g. "location", "priority", or
// a split "date_start"), and its new rendered Value. The description trailer is
// delivered as a FieldEdit too, named for the node type's declared Trailer field.
// The plugin maps each Name to a substrate property — recombining split atoms
// (date_start + time_start -> one DTSTART) and preserving parts the atoms do not
// carry (a DTSTART's timezone) — so the framework never learns the substrate's
// shape (RFC 0009 no-inversion).
type FieldEdit = internal.FieldEdit

// FieldKind classifies a unified field's value shape. It unifies FacetKind
// (categorical / numeric-bucket / labelled) with the presentation notions the codec
// model adds (date, tag, free text), so one enum spans both former surfaces.
type FieldKind = internal.FieldKind

// FieldPresenter is the OPTIONAL capability a plugin implements to present a
// node's detail fields as organize espalier box-interior atoms (FDR 0023,
// cutting-garden#47). The framework never parses substrate values — a caldav
// DTSTART is an iCalendar date-time carrying a timezone — so the plugin owns
// the transform: it can split one substrate field into several friendly atoms
// (DTSTART → date_start + time_start), format values ergonomically, and omit
// atoms that do not apply (an all-day event has no time_start). Probed by type
// assertion like the other capabilities.
//
// This is the RENDER direction only (read-side, cutting-garden#47). The inverse
// — parsing edited atoms back into a substrate write while preserving the parts
// the atoms do not carry (a DTSTART's timezone) — is the write-side follow-up
// and is deliberately NOT part of this capability yet.
type FieldPresenter = internal.FieldPresenter

// FieldValue is one declared bucket/enum value of a unified field — the
// presentation-layer counterpart of FacetValue (RFC 0012 §1). Order renders
// urgency-/chronology-first (descending); zero for an unordered categorical value.
type FieldValue = internal.FieldValue

// FieldWriteApplier is the capability that BUILDS the substrate patch for a batch
// of an object's changed box atoms (and/or its description trailer) — the
// write-side execution counterpart of the ListingField.Writable declaration, and
// the field-edit sibling of FacetWriteApplier (which handles bucket moves). The
// organize apply engine collects one node's changed WRITABLE atoms plus any
// trailer edit and hands them over together, because a plugin may need the whole
// batch to write correctly (a caldav date_start and time_start recombine into a
// single DTSTART property). The plugin returns the finished PatchNode body, so the
// framework stays free of the substrate's JSON layout (RFC 0009).
//
// Probed by type assertion on an already-resolved plugin, exactly like
// FacetWriteApplier. A plugin that declares any writable listing field
// (ListingField.Writable) MUST also implement this — the apply engine rejects a
// writable-but-applier-less plugin loudly rather than guessing the patch shape.
type FieldWriteApplier = internal.FieldWriteApplier

// IdentityCodec is the reusable 1<->1 passthrough codec: one stored field maps to
// one presentation field, value unchanged (FDR 0025). It reproduces a plain box
// atom / listing field (a caldav location, status, or summary) — the common case
// where no transformation is needed. Non-string stored values are rendered with
// their canonical string form on Format; Parse writes the edited string back
// verbatim (a plugin needing a typed write, e.g. an integer priority, uses a typed
// codec instead).
type IdentityCodec = internal.IdentityCodec

// LeafContent is one leaf node's fetched content, returned by ReadLeaf. It
// carries two views of the same object: a structured, JSON-marshalable
// projection a client reads (the parsed fields), and the verbatim source
// bytes (the content-addressable original).
type LeafContent = internal.LeafContent

// LeafReader is the OPTIONAL capability a RootLister implements to fetch a
// single leaf node's content on demand — the per-object body-fetch backing
// MCP resources/read (cutting-garden#85). It is probed by type assertion on
// an already-resolved plugin, exactly as RootProvider is; a plugin whose
// scheme has no individually-fetchable objects omits it, and consumers fall
// back to the structure-only listing.
//
// ReadLeaf is consulted only after ListRoots reports a node has no children
// (a leaf or an empty container), so it never has to re-derive that a
// populated container is not a leaf. It is read-only: it never mutates the
// source and never writes to a blob store.
type LeafReader = internal.LeafReader

// ListingField describes one key a node type may carry in Node.Fields — the
// listing-projection counterpart of FacetDimension: a human-readable value
// (a summary, a due date, a status string) rather than a bucketed facet
// membership. See cutting-garden#160.
type ListingField = internal.ListingField

// ListingFieldsDescriber is the OPTIONAL capability that declares a
// plugin's listing-field schema, symmetric with FacetDescriber — the
// discoverability half of enriched listings (cutting-garden#160): a
// consumer learns via describe_node_types which Node.Fields keys a node
// type may carry, without having to infer them from an example listing.
// Probed by type assertion on an already-resolved plugin, exactly as the
// other schema-describing capabilities.
type ListingFieldsDescriber = internal.ListingFieldsDescriber

// MembershipWriteApplier is the full-set sibling of FacetWriteApplier for a
// MULTI-VALUED (write:many) tag dimension. Where BuildFacetWritePatch moves a node
// into a SINGLE bucket — routing through a per-bucket Parse that would discard a
// full-set-replace codec's other values — this carries the COMPLETE membership set
// the interpreter's Complete already resolved, so the codec's full-set Parse
// persists exactly that set. It is a SEPARATE optional interface, not a method on
// FacetWriteApplier, so declaring it does not force every existing single-bucket
// applier to grow a method.
//
// Probed by type assertion on an already-resolved plugin, exactly like
// FacetWriteApplier. A plugin returns the finished patch body, so the organize
// apply engine stays free of the substrate's patch shape (RFC 0009 no-inversion).
type MembershipWriteApplier = internal.MembershipWriteApplier

// Node is one addressable point in a RootLister plugin's capturable
// tree, as returned by ListRoots.
type Node = internal.Node

// NodeMutator is the OPTIONAL write capability: create, replace, patch, or
// delete a single addressable node in a plugin's tree — the write-side
// sibling of RootLister (FDR 0014/0020). It is probed by type assertion on an
// already-resolved plugin, exactly as RootLister / LeafReader / RootProvider
// are; a plugin whose scheme has no meaningful write surface simply omits it.
//
// Node addressing reuses the RootLister URI space verbatim: a mutation
// targets the same *url.URL a ListRoots / resources/read walk surfaces, so
// the read and write axes share one address space. CUD is NOT receipt-based —
// it mutates one live node, with no blob store and no capture receipt
// (capturing the post-mutation state is a separate `capture` invocation).
type NodeMutator = internal.NodeMutator

// NodeType is one entry in a RootLister plugin's declared type list. It
// is the unit of self-description for the traversal tree: a Node names
// its type by Tag, and a consumer resolves that Tag against the
// plugin's Types() to learn whether the node can be descended, which
// format version it speaks, and what its bytes are.
//
// Tag is a hyphenated, horizontally-versioned identifier in the
// madder/dodder scheme (e.g. "cutting_garden-caldav-calendar-v1"). The
// declared list is the plugin's backwards-compatibility surface: a
// format change adds a "-v2" entry while the "-v1" entry stays
// readable, so a consumer built against -v1 keeps working when -v2
// nodes appear beside it (see amarbel-llc/cutting-garden#79).
//
// The shape deliberately grows toward dodder's type definitions
// (dodder FDR 0010; the `!toml-type-v2` blob with binary /
// file-extension / mime-type / formatter fields), one field at a time
// as a consumer needs it — MimeType is the first.
type NodeType = internal.NodeType

// NodeTypeBody describes the create/update payload one writable node type
// accepts — the schema-discovery surface behind the mcp server's
// describe_node_types tool, so an agent can construct a valid body without
// guessing or reading an existing node first.
type NodeTypeBody = internal.NodeTypeBody

// NodeTypeFacetWrites binds a set of FacetWrites to one node type — the
// write-side counterpart of NodeTypeFacets.
type NodeTypeFacetWrites = internal.NodeTypeFacetWrites

// NodeTypeFacets binds a set of facet dimensions to one node type. See
// RFC 0012 §2.
type NodeTypeFacets = internal.NodeTypeFacets

// NodeTypeListingFields binds a set of declared listing fields to one node
// type — the listing-projection schema, symmetric with NodeTypeFacets. See
// cutting-garden#160.
type NodeTypeListingFields = internal.NodeTypeListingFields

// NodeTypeUnifiedFields binds a node type to the codecs producing its unified
// fields (FDR 0025) — the unified counterpart of NodeTypeFacets /
// NodeTypeListingFields. Every presentation field a node type carries comes from
// exactly one codec in Codecs (an identity codec for a plain passthrough field, a
// split codec for a date, a band codec for a banded priority), so the full field
// set is the concatenation of each codec's Fields().
type NodeTypeUnifiedFields = internal.NodeTypeUnifiedFields

// NopReporter is the no-op Stream.
type NopReporter = internal.NopReporter

// Plugin is the cross-cutting identity every capture or restore
// backend must declare. Schemes returns the URI schemes a plugin
// handles; the empty string registers the plugin as the schemeless
// default and SHOULD only be claimed by one plugin per binary.
type Plugin = internal.Plugin

// ProtocolCapturePlugin is the opt-in interface a capture plugin
// implements to emit an RFC 0002 receipt merkle tree instead of (or in
// addition to) the EntryV1 stream of CapturePlugin.CaptureRoot. When the
// orchestrator resolves a capture plugin that also satisfies this
// interface, it routes the root through CaptureProtocol and records the
// returned receipt id directly — the per-root capture produces its own
// self-contained receipt rather than folding EntryV1 records into a
// shared store-group receipt.
type ProtocolCapturePlugin = internal.ProtocolCapturePlugin

// ProtocolCaptureRequest is what a ProtocolCapturePlugin needs to
// materialize one capture as a Capture Plugin Protocol (RFC 0002) merkle
// tree: the parsed source, the destination blob store (the protocol
// "writer" sink), and the command's cancelable context. RawArg is the
// original CLI argument, for diagnostics.
type ProtocolCaptureRequest = internal.ProtocolCaptureRequest

// ProtocolCaptureResult is the orchestrator-visible output of one
// protocol capture: the root receipt's markl id and the number of
// payload objects stored (for the sink's per-receipt summary).
type ProtocolCaptureResult = internal.ProtocolCaptureResult

// ProtocolDiffPlugin compares an RFC 0002 receipt against a live source.
type ProtocolDiffPlugin = internal.ProtocolDiffPlugin

// ProtocolDiffRequest is what a ProtocolDiffPlugin needs to compare a
// captured receipt against a live source: the store holding the
// receipt, the receipt id, and the parsed comparison source.
type ProtocolDiffRequest = internal.ProtocolDiffRequest

// ProtocolDiffResult carries the human-readable difference lines (empty
// when the receipt and source agree).
type ProtocolDiffResult = internal.ProtocolDiffResult

// ProtocolRestorePlugin reconstructs a capture from its receipt merkle
// tree. ProtocolKind returns the receipt kind it handles (e.g. "git").
type ProtocolRestorePlugin = internal.ProtocolRestorePlugin

// ProtocolRestoreRequest is what a ProtocolRestorePlugin needs to
// rebuild a capture from its RFC 0002 receipt: the store holding the
// receipt (and its referenced blobs), the receipt's markl id, and the
// parsed destination. Routing is by receipt *kind*, not dest scheme —
// the receipt knows how it was captured.
type ProtocolRestoreRequest = internal.ProtocolRestoreRequest
type ReportPlan = internal.ReportPlan
type ReportProgress = internal.ReportProgress

// Reporter is the unified capture-events stream. The historical name is
// kept as an alias so request structs and plugin call sites read
// unchanged; new code should say capture_events.Stream. See
// internal/capture_events for the contract and semantics.
type Reporter = internal.Reporter

// ResolvedNodeType is the outcome of URI→type resolution (RFC 0018 §4):
// the node type whose declared URITemplate matched a URI, together with
// the variable bindings that match captured.
type ResolvedNodeType = internal.ResolvedNodeType

// RestorePlugin materializes a receipt's entries to the destination.
type RestorePlugin = internal.RestorePlugin

// RestoreRequest is what a RestorePlugin needs to materialize a
// previously-captured tree: the receipt's parsed entries, the source
// blob store, and the destination URL (already parsed; may be
// schemeless). Context is the command's cancelable context.
type RestoreRequest = internal.RestoreRequest

// RootLabeler is the OPTIONAL capability a RootProvider implements to
// supply a friendlier display label for one or more of its OWN top-level
// roots than the framework's default URL-derived label (the last path
// segment, else the host) — e.g. a caldav account configured directly at
// a single calendar collection, whose path segment is an opaque UID
// rather than a human name (cutting-garden#120). It is probed alongside
// RootProvider by the shared root-aggregation path
// (command_components.AggregateRootLabels), the one place that still
// holds the plugin reference before Roots()'s per-plugin URLs are
// flattened into one list.
type RootLabeler = internal.RootLabeler

// RootLister is the OPTIONAL traversal capability a Plugin implements
// when its scheme has meaningful sub-structure a user may want to
// discover, address, diff, or restore independently (a CalDAV
// endpoint's calendars, a yt-dlp channel's videos, a Drive folder's
// files). It is probed by type assertion on an already-resolved plugin,
// exactly as the orchestrator probes ProtocolCapturePlugin — there is
// no separate registry. Plugins without sub-structure (the file plugin)
// omit it, and consumers fall back to today's one-arg-one-root model.
//
// ListRoots is read-only and lazy: it returns the immediate children of
// one node, and a consumer descends a container by calling again with
// that container's URI. This hierarchical, one-level-per-call shape is
// the shape MCP `resources/list` consumes, it bounds work on large
// trees, and it lets a consumer stop at whatever depth it cares about.
//
// It is the single source of traversal truth for a plugin: capture,
// the `list` discovery command, the planned `health` command (#80), and
// a future MCP traversal server all walk the same enumeration rather
// than re-deriving the tree independently. See FDR 0014.
type RootLister = internal.RootLister

// RootProvider is the OPTIONAL capability of a RootLister that can
// enumerate its own top-level roots with no input node — the entry points
// a no-argument `mcp` / `list` surfaces (RFC 0007). It is probed by type
// assertion exactly as RootLister is.
//
// The source of the roots is plugin-defined and invisible to the caller:
// intrinsic ambient state (the file plugin's working directory),
// configured credentialed accounts (caldav), or configured preferred
// roots (a future web/yt-dlp plugin). A plugin that can enumerate none
// returns an empty slice — it then contributes nothing and does not appear
// in the aggregated listing.
type RootProvider = internal.RootProvider

// SourceValidator is the OPTIONAL narrow capability (RFC 0005 §Source
// validation) that lets a capture source be validated even when the
// resolved plugin does not (also) satisfy the full CapturePlugin
// interface — notably a plugin resolved via the scheme-registry fallback
// (RFC 0005 §Resolution) that implements only ProtocolCapturePlugin. Its
// signature is identical to CapturePlugin.ValidateSource, so every
// existing CapturePlugin already satisfies it with no changes. The
// orchestrator probes for this interface by type assertion and skips
// validation (not an error) when a resolved plugin implements neither
// it nor CapturePlugin.
type SourceValidator = internal.SourceValidator

// TagInterpreter governs the match/group/write-back semantics of one tag field
// (RFC 0019 §1). It is applied HOST-side over the raw tag strings a data plugin
// emits (RFC 0019 §2); a data plugin — linked or wire (RFC 0013) — never
// implements it. Every method is a pure function of its arguments: same inputs,
// same outputs, no side effects, no hidden state, no I/O.
//
// The contract is wire-shaped and this is normative (RFC 0019 §2): every
// method's arguments and results are plain values (strings, string slices,
// TagMembership, TagMembershipOp) precisely so a future RFC 0013-style JSON-RPC
// transport (RFC 0019 §8) can carry the exact method set unchanged. An
// implementation MUST keep this interface serializable — no method may take or
// return a callback, an iterator/Seq, a channel, a context.Context, or any
// interface whose behavior cannot be reduced to values on a wire.
type TagInterpreter = internal.TagInterpreter

// TagMembership is one node's placement in one grouping bucket, as computed by
// TagInterpreter.Buckets (RFC 0019 §1). It is a pure value pair, safe to
// serialize.
type TagMembership = internal.TagMembership

// TagMembershipOp selects the direction of a membership edit passed to
// TagInterpreter.Complete (RFC 0019 §1).
type TagMembershipOp = internal.TagMembershipOp

// URITemplate is a parsed, validated RFC 6570 Level 1 URI template
// (RFC 0018 §2) supporting bidirectional resolution: Expand fills the
// template's variables to mint a URI, and Match reverses a URI back to
// its variable bindings. A node type MAY declare one (NodeType.URITemplate)
// so the host can answer URI→type locally, without a round trip, and so a
// plugin can mint its own URIs consistently.
//
// The Level 1 subset — bare {name} expressions, no operators, prefixes, or
// explode — is the largest RFC 6570 subset that reverses unambiguously
// (RFC 0018 §2) and re-exports verbatim as a Model Context Protocol
// resource template (RFC 0018 §8). A {name} captures exactly one path
// segment or sub-segment: it never spans '/'. The value it captures is
// the maximal such run that still lets the remainder match — greedy, so a
// following literal delimiter binds at its LAST occurrence.
//
// The zero value is not usable; obtain a URITemplate only from
// ParseURITemplate.
type URITemplate = internal.URITemplate

// UnifiedDescriber is the OPTIONAL capability declaring a plugin's unified
// field-codec model (FDR 0025). Probed by type assertion like the other
// schema-describing capabilities. A plugin that implements it can have its legacy
// FacetDescriber / ListingFieldsDescriber / FieldPresenter / write surfaces DERIVED
// from the declaration (the following slices) rather than hand-written.
type UnifiedDescriber = internal.UnifiedDescriber

// UnifiedField describes one PRESENTATION field a codec produces (FDR 0025). It is
// the superset of FacetDimension (Key/Label/Kind/MultiValued/Values/TerminalValues)
// and ListingField (Writable, plus the inline/trailer presentation flags): the
// single declaration from which the renderer and the legacy-surface derivation
// helpers both read.
type UnifiedField = internal.UnifiedField

// ApplyBulkOp applies one op via nm's matching NodeMutator verb and records
// the outcome into result: AppliedNodes on success, PatchedNothing when a
// patch was ACCEPTED but landed no recognized field (#182), Failed
// otherwise. It never returns an error — a per-op failure is a BulkFailure,
// the best-effort contract (RFC 0017). This is the single dispatch loop
// caldav, the testpeer, and jira share (cutting-garden#197): its per-node
// result-collection — the #182 patchedNothing-vs-applied distinction most of
// all — lives here so a subtle bug cannot be fixed inconsistently across
// plugins.
var ApplyBulkOp = internal.ApplyBulkOp

// BestEffortBulkMutate is the whole best-effort BulkMutate for a plugin that
// is both a NodeMutator and an EnrichedLister — the common shape every
// current implementer takes (caldav, the testpeer, jira, newsblur are all
// best-effort-only). It REJECTS an atomic request with
// ErrBulkAtomicUnsupported (the reject-never-downgrade floor for a plugin
// that does not advertise bulk-atomic), and otherwise dispatches the
// changeset or the sweep best-effort. A plugin's whole BulkMutate collapses
// to one delegating line: `return BestEffortBulkMutate(ctx, p, p, req)`.
//
// A plugin that CAN transact atomically implements AtomicBulkMutator and its
// own atomic path instead, reusing BulkBestEffortOps/Sweep for its
// best-effort branch. A plugin without an EnrichedLister cannot use this
// (a sweep has no way to resolve its match set) and dispatches the pieces
// itself.
var BestEffortBulkMutate = internal.BestEffortBulkMutate

// BulkBestEffortOps applies an explicit changeset best-effort via nm,
// returning the partitioned result. It never errors: each op's failure is a
// BulkFailure entry, never a returned error.
var BulkBestEffortOps = internal.BulkBestEffortOps

// BulkBestEffortSweep resolves a sweep's match set via el.ListEnriched and
// applies the op template to each match best-effort (the op template's URI
// is ignored; each matched node's URI is filled in). On an el DECLINE
// (ok=false) it REFUSES with a bad request rather than proceeding: a
// mutation must never silently widen its scope from "matching" to "every
// child" — the write-safety contract caldav established (cutting-garden#191).
// A read may degrade a decline to an unfiltered listing; a write may not.
var BulkBestEffortSweep = internal.BulkBestEffortSweep

// DateBucketMatches reports whether a bucket key falls inside a (coarser or
// equal) date bucket: key equals the bucket, or extends it at a `-` boundary —
// "2026-08" contains "2026-08-15" but never a hypothetical "2026-081". This is
// the single hierarchy-containment definition shared by FacetPredicate.matches
// and the trellis evaluator's date-kind `=` predicate (cutting-garden#230), so
// the two filter surfaces cannot drift. Callers gate on ParseDateBucket first:
// a non-shape bucket value means exact semantics, not containment.
var DateBucketMatches = internal.DateBucketMatches

// DeriveFacetDimensions reproduces FacetDescriber's per-type dimension list from a
// node type's codecs: every GROUPABLE presentation field becomes a FacetDimension,
// in codec-then-field declaration order (the order describe_node_types renders).
var DeriveFacetDimensions = internal.DeriveFacetDimensions

// DeriveFacetWrites reproduces FacetWriteDescriber's per-type write mappings from
// a node type's codecs: every GROUPABLE field gets a FacetWrite — Mode none for a
// read-only field (declared, so an edit fails loudly rather than silently, per
// FDR 0023), else one/many from MultiValued. The write target is the field's
// Source (the stored field it attributes to), falling back to Key when the field
// is its own stored field — the same attribution rule PresentUnifiedAtoms uses
// for BoxAtom.Field. The pre-rendered bucket list is WriteValues, defaulting to
// the declared closed-domain Values' keys.
var DeriveFacetWrites = internal.DeriveFacetWrites

// DeriveNodeTypeFacetWrites is DeriveNodeTypeFacets' write-side sibling: a
// migrated plugin's DescribeFacetWrites is a one-line delegation to this.
var DeriveNodeTypeFacetWrites = internal.DeriveNodeTypeFacetWrites

// DeriveNodeTypeFacets reproduces a whole FacetDescriber result from a unified
// declaration (the UnifiedDescriber return shape): one NodeTypeFacets per set,
// its dimensions derived from the set's codecs. A migrated plugin's
// DescribeFacets is a one-line delegation to this.
var DeriveNodeTypeFacets = internal.DeriveNodeTypeFacets

// ErrAlreadyRegistered is returned by registry.Register when a
// scheme is already registered for the given direction (capture
// or restore).
var ErrAlreadyRegistered = internal.ErrAlreadyRegistered

// ErrBulkAtomicUnsupported is the sentinel a BulkMutator returns when
// it cannot honor BulkAtomic for a request — because it never supports
// atomic at all, or because THIS request's ops span something it
// cannot transact together (RFC 0017 §Atomicity). The plugin MUST
// reject, never downgrade to best-effort. The wire transport maps this
// sentinel to RFC 0017's -32003 (atomic-unsupported) code; a plugin
// returns it (or wraps it) so the reason is distinguishable from an
// ordinary failure.
var ErrBulkAtomicUnsupported = internal.ErrBulkAtomicUnsupported

// ErrUnknownScheme is returned by registry.Resolve when the
// scheme is not registered for the given direction.
var ErrUnknownScheme = internal.ErrUnknownScheme

// FindFacetDimension looks up key across every NodeTypeFacets in dims — a
// filter predicate names only a dimension key, not the node type that
// declares it, since a summarized subtree may fold several leaf types
// together (RFC 0012 §4.1). Exported so consumers resolving a dimension by
// key (organize's group-by spelling resolution) share this lookup instead of
// duplicating the loop.
var FindFacetDimension = internal.FindFacetDimension

// LookupTagInterpreter resolves a registered interpreter by name (RFC 0019 §3).
// ok is false for an unregistered name; a consumer MUST NOT fall back to a
// default on a miss (that decision belongs to selection, RFC 0019 §4) — a miss
// at a point that required a named interpreter is a bad request.
var LookupTagInterpreter = internal.LookupTagInterpreter

// MustRegisterCapture installs p in the default capture registry
// under every scheme p.Schemes() returns. Panics on duplicate
// registration; intended for plugin init() functions where a clash
// is a programming error.
var MustRegisterCapture = internal.MustRegisterCapture

// MustRegisterDiff is the diff-direction analogue of
// MustRegisterCapture.
var MustRegisterDiff = internal.MustRegisterDiff

// MustRegisterProtocolDiff is the diff-direction analogue of
// MustRegisterProtocolRestore.
var MustRegisterProtocolDiff = internal.MustRegisterProtocolDiff

// MustRegisterProtocolRestore installs p under p.ProtocolKind(). Panics
// on duplicate registration; intended for binding init() functions.
var MustRegisterProtocolRestore = internal.MustRegisterProtocolRestore

// MustRegisterRestore is the restore-direction analogue of
// MustRegisterCapture.
var MustRegisterRestore = internal.MustRegisterRestore

// MustRegisterScheme installs p in the default scheme registry under every
// scheme p.Schemes() returns. Panics on duplicate registration; intended
// for plugin init() functions where a clash is a programming error.
//
// A plugin that already registers via MustRegisterCapture / -Restore /
// -Diff is enumerated through those registries and need not also register
// here; MustRegisterScheme is the discovery path for a plugin that
// implements none of those directions (RFC 0005, RFC 0009 §3).
var MustRegisterScheme = internal.MustRegisterScheme

// NodeTypeFor resolves a Node.Type tag against the plugin's declared
// Types() — the one lookup every traversal consumer performs. ok is
// false for an unknown tag; the zero NodeType then behaves as a leaf of
// unspecified mimetype, so a consumer built against the declared list
// neither invents descendability nor fabricates a content type beyond
// the leaf default.
var NodeTypeFor = internal.NodeTypeFor

// ParseDateBucket classifies a value by its date-bucket shape — YYYY,
// YYYY-MM, or YYYY-MM-DD with in-range month/day — reporting the granularity
// it addresses. ok == false for any other shape: the loud-rejection gate for
// prefix filters and coarse bucket moves.
var ParseDateBucket = internal.ParseDateBucket

// ParseDateGranularity resolves a granularity spelling. Strict lowercase —
// a typo rejects loudly at the CLI/config layer.
var ParseDateGranularity = internal.ParseDateGranularity

// ParseFacetFilter parses "dim=val,dim2=val2" into an AND-composed
// FacetFilter (RFC 0012 §6) — the shared grammar behind `list --filter` and
// the mcp read_facets tool's optional filter parameter, so the two surfaces
// never drift. The empty string (after trimming) is no filter (nil, nil).
var ParseFacetFilter = internal.ParseFacetFilter

// ParseURITemplate validates s against the Level 1 subset (RFC 0018 §2)
// and returns the parsed, match-ready template. It rejects an operator or
// modifier inside an expression, two variables with no intervening
// literal, a duplicate variable name, and an unclosed '{'. An empty string
// parses to a variable-free template that matches only itself (a fixed
// URI, e.g. a singleton).
var ParseURITemplate = internal.ParseURITemplate

// ParseUnifiedBucketMove reproduces the stored-field updates half of a
// FacetWriteApplier from a node type's codecs: a facet-bucket move is routed to
// the codec owning the GROUPABLE field named by dimension, whose Parse completes
// the target bucket onto the substrate — a status bucket passing through
// verbatim, a priority band completing to its canonical stored value, a
// month/year bucket splicing into the object's current date. current carries the
// node's present stored values for that completion. The plugin wraps the returned
// storedUpdates in its substrate patch shape, exactly as with
// ParseUnifiedFieldEdits. Loud rejections (the FDR 0023 rule): a dimension no
// codec declares groupable, one declared read-only, and — for a CLOSED value
// domain (Values non-nil) — a target bucket outside the declared set (an open
// domain accepts any bucket; the codec's Parse still validates its shape).
var ParseUnifiedBucketMove = internal.ParseUnifiedBucketMove

// ParseUnifiedFieldEdits reproduces the stored-field updates half of a
// FieldWriteApplier from a node type's codecs: each edit is routed to the codec
// that owns its presentation field, and that codec's Parse inverts the batch onto
// the substrate fields — a split date_start + time_start recombining into one date
// property via its shared codec. current carries the node's present stored values so
// a partial edit preserves the untouched parts. The plugin wraps the returned
// storedUpdates in whatever substrate patch shape it needs (caldav: a
// {component, inner} body). An edit whose field no codec produces, or whose field
// is declared read-only (Writable false), is a bad request — the reject-unknown
// gate the legacy applier had, plus the same loud writability gate
// ParseUnifiedBucketMove applies on the move side, so a direct SDK caller cannot
// write through a read-only declaration even without the framework's own
// writability gate in front.
var ParseUnifiedFieldEdits = internal.ParseUnifiedFieldEdits

// ParseUnifiedMembershipWrite is ParseUnifiedBucketMove's multi-valued sibling:
// it routes a FULL-SET replacement of a groupable, writable, MULTI-VALUED tag
// dimension to the codec owning it, whose Parse persists the complete set. Unlike
// the single-bucket move, this carries every tag (the interpreter's Complete has
// already resolved the final set) — a per-bucket call would drop the others. An
// empty newTags is valid and clears the dimension. No closed-domain (Values) check:
// tags are an open domain, so any value is accepted (the codec's Parse still
// validates its shape). Loud rejections mirror ParseUnifiedBucketMove — a dimension
// no codec declares groupable, one declared read-only, and (this helper being the
// many case only) one declared single-valued, which must use ParseUnifiedBucketMove.
var ParseUnifiedMembershipWrite = internal.ParseUnifiedMembershipWrite

// PresentUnifiedAtoms reproduces FieldPresenter.PresentBoxAtoms from a node type's
// codecs: each codec formats the node's stored fields, and every INLINE (non-
// Trailer) presentation field it produces becomes a box atom, in codec-then-field
// declaration order. An atom carries its field's Source as BoxAtom.Field (empty =
// the atom is its own field), so a split date_start/time_start attributes to its
// parent stored field for the writability gate. It is a resilient read-side
// projection: a codec whose Format fails on a malformed value contributes no atoms
// (matching the legacy presenter, which simply skips an unparseable field) rather
// than aborting the whole box — so it has no error return.
var PresentUnifiedAtoms = internal.PresentUnifiedAtoms

// PresentUnifiedTags returns a node's presented tag set: the values of the
// type's DESIGNATED FieldTag field (exactly one per type, G6 v1 —
// ValidateUnifiedFieldSets enforces the declaration invariant), produced by the
// owning codec's Format in STORED order. Interpreter-normalized ordering
// (SortKey) is the FRAMEWORK's render-time job, not the codec's or this
// helper's. A type declaring no FieldTag field has no tag notion and presents
// nil, as does an untagged node (the codec omits the key). Resilient like
// PresentUnifiedAtoms: a Format failure on a malformed value contributes
// nothing rather than aborting. Wire plugins (RFC 0013) will instead carry
// tags as a listing field named by the type's tag_set — out of scope here.
var PresentUnifiedTags = internal.PresentUnifiedTags

// RecognizedPatchFields returns the subset of supported keys present in
// fields, preserving supported's order — callers pass a SORTED supported
// list so the result, and the PatchNode applied report built from it, is
// deterministic. Always non-nil, so an empty result is the authoritative
// "nothing recognized" the #182 present-empty applied contract requires,
// never a nil "did not report". The shared single-node #182 helper caldav
// and jira use (cutting-garden#197).
var RecognizedPatchFields = internal.RecognizedPatchFields

// RegisterProtocolDiff installs p under p.ProtocolKind(), returning an
// error (wrapping ErrAlreadyRegistered) on a clash instead of
// panicking — the config-driven registration path for a wire capture
// plugin (cutting-garden#146 slice 2), where a kind collision is user
// misconfiguration (EX_USAGE), not a programming error. MustRegister
// ProtocolDiff is a thin panicking wrapper for binding init() functions.
var RegisterProtocolDiff = internal.RegisterProtocolDiff

// RegisterScheme installs p under every scheme it declares, returning an
// error (wrapping ErrAlreadyRegistered) on a clash instead of panicking —
// the config-driven registration path for wire plugins (RFC 0013 §Host
// integration), where a scheme collision is user misconfiguration
// (EX_USAGE), not a programming error. On a clash, schemes registered
// before the colliding one remain registered; callers treat the error as
// fatal to startup, so the partial registration is never served.
var RegisterScheme = internal.RegisterScheme

// RegisteredPlugins returns every plugin registered in the scheme,
// capture, restore, or diff registry, deduplicated and sorted by scheme
// set. It is the read surface the `health`, `list`, and `mcp` commands use
// to enumerate plugins and probe their capabilities; the registries are
// otherwise resolve-only.
//
// The protocol registries (protocol_registry.go) contribute no new
// plugins — a protocol plugin is also registered as a capture/diff
// plugin — so protocol capabilities are detected by type-asserting the
// returned Plugin, not by enumerating those registries. The scheme
// registry (scheme_registry.go) is unioned in so a plugin registered via
// MustRegisterScheme alone — implementing none of capture/restore/diff,
// e.g. a RootProvider-only traversal plugin (RFC 0005, RFC 0009 §3) — is
// still enumerated. Dedup by scheme set means a plugin registered both via
// a direction and via MustRegisterScheme appears exactly once.
var RegisteredPlugins = internal.RegisteredPlugins

// ReporterOrNop returns r, or a no-op Stream when r is nil.
var ReporterOrNop = internal.ReporterOrNop

// ResolveCapture looks up the capture plugin registered under
// scheme. Returns an error wrapping ErrUnknownScheme on miss.
var ResolveCapture = internal.ResolveCapture

// ResolveDiff is the diff-direction analogue of ResolveCapture.
var ResolveDiff = internal.ResolveDiff

// ResolveNodeTypeByURI answers RFC 0018's URI→type question locally, with
// no plugin round trip: it matches uri against the URITemplate of each type
// lister declares, and returns the winning type and its captured bindings.
//
// When several templates match, RFC 0018 §4's most-specific rule selects
// one — greater literal-character count, then fewer variables, then longer
// literal prefix. A TRUE tie (no strict winner) returns ok == false: the
// host MUST fall back (RFC 0018 §6; the #168 gate probes) and MUST NOT
// guess. A type declaring no template, an unparseable template, and a URI
// no template matches all likewise return ok == false — the template is an
// optimization, never a precondition. Roots are outside this scheme
// (RFC 0018 §5) and are deliberately not resolved through this path.
var ResolveNodeTypeByURI = internal.ResolveNodeTypeByURI

// ResolveProtocolDiff is the diff-direction analogue of
// ResolveProtocolRestore.
var ResolveProtocolDiff = internal.ResolveProtocolDiff

// ResolveProtocolRestore looks up the protocol restore plugin for a
// capture kind. Returns an error wrapping ErrUnknownScheme on miss.
var ResolveProtocolRestore = internal.ResolveProtocolRestore

// ResolveRestore is the restore-direction analogue of
// ResolveCapture.
var ResolveRestore = internal.ResolveRestore

// ResolveScheme looks up the base plugin registered under scheme via
// MustRegisterScheme. Returns an error wrapping ErrUnknownScheme on miss.
var ResolveScheme = internal.ResolveScheme

// SortAndLimitContainerBreakdown orders a per-container breakdown by
// descending Count (ties broken by ascending URI for determinism) and caps
// it at FacetContainerBreakdownLimit, reporting whether truncation
// occurred — the shared bounding logic behind FacetResult.ByContainer, so
// every FacetCounter implementation enforces the same cap the same way
// instead of each hand-rolling it (RFC 0012 §13, cutting-garden#170).
// breakdown is sorted and possibly resliced in place; callers MUST NOT
// rely on its pre-call order or capacity afterward.
var SortAndLimitContainerBreakdown = internal.SortAndLimitContainerBreakdown

// TruncateDateKey coarsens a date bucket key to the granularity by prefix
// truncation. A key already at or coarser than the granularity is unchanged.
var TruncateDateKey = internal.TruncateDateKey

// ValidateFacetWrites cross-checks write mappings against the read-side facet
// schema. It returns the first violation (nil when consistent) so a plugin's
// write schema cannot silently reference a dimension that does not exist:
//
//   - every NodeTypeFacetWrites.Tag MUST have a matching NodeTypeFacets entry;
//   - every FacetWrite.DimensionKey MUST name a dimension that tag declares;
//   - a non-none Mode MUST carry a Field, and Mode MUST be one of the three
//     declared values.
//
// reads and writes are the plugin's own DescribeFacets / DescribeFacetWrites
// outputs. It is the loud-rejection mechanism the apply engine uses before
// writing, and the check a plugin's own tests assert against.
var ValidateFacetWrites = internal.ValidateFacetWrites

// ValidateFilterFor validates (and prefix-arms) a filter against a lister's
// declared facet schema: the probe-DescribeFacets-then-Validate dance every
// host-side filter consumer must perform before Matches, centralized so a new
// call site cannot forget it (a forgotten Validate silently degrades a
// date-kind predicate to exact matching). A lister without FacetDescriber has
// no schema; the filter passes through unchecked, exactly as Validate(nil).
var ValidateFilterFor = internal.ValidateFilterFor

// ValidateUnifiedFieldSets checks a unified declaration's cross-codec
// invariants that no single codec can see: at most one FieldTag field per node
// type (G6 v1 — one designated tag set per type). PresentUnifiedTags reads THE
// designated field, so a second FieldTag declaration is a declaration error
// naming both keys, never a silent first-wins. The framework wires it at
// organize generate's resolution point (native tags slice 2), so a bad
// declaration fails the command loudly; a plugin SHOULD additionally pin its
// declaration with a unit test calling this (caldav does), catching the error
// before any command runs.
var ValidateUnifiedFieldSets = internal.ValidateUnifiedFieldSets

// BulkAtomic requires all-or-nothing completion. A plugin that cannot
// honor it — for this request or at all — MUST reject the request with
// an error; it MUST NOT silently downgrade to BulkBestEffort.
const BulkAtomic = internal.BulkAtomic

// BulkBestEffort applies each targeted node independently; partial
// completion is expected and reported via BulkResult. REQUIRED of
// every BulkMutator for every request shape it accepts — the floor.
const BulkBestEffort = internal.BulkBestEffort
const BulkCreate = internal.BulkCreate
const BulkDelete = internal.BulkDelete
const BulkPatch = internal.BulkPatch
const BulkPut = internal.BulkPut

// FacetCategorical is a plain discrete bucket (status, state, domain).
const FacetCategorical = internal.FacetCategorical

// FacetContainerBreakdownLimit bounds how many non-empty child containers a
// FacetResult.ByContainer may list. A container fan-out can be large (a
// newsblur account's several hundred feeds); an unbounded breakdown would
// trade one guessing problem (which of 23 calendars?) for another (a
// 285-entry list to scan). See RFC 0012 §13.
const FacetContainerBreakdownLimit = internal.FacetContainerBreakdownLimit

// FacetDate is a calendar-date dimension: bucket keys are ISO days
// ("2026-08-15"), chronologically ordered, and PREFIX-COARSENABLE — the
// year ("2026") and month ("2026-08") buckets are string prefixes of the
// day key, so consumers coarsen by TruncateDateKey with no calendar
// knowledge, and filters prefix-match by validated shape (see
// FacetFilter.Validate). Introduced for cutting-garden#230.
const FacetDate = internal.FacetDate

// FacetLabelled is an opaque stable key whose human name is resolved out
// of band via FacetLabeler (a feed id, an account id).
const FacetLabelled = internal.FacetLabelled

// FacetNumericBucket is a number quantized to an ordered bucket; values
// carry FacetValue.Order (year, month, size band).
const FacetNumericBucket = internal.FacetNumericBucket

// FacetWriteMany: several values; a write is a per-value membership delta
// (add/remove a label or tag). Pairs with a Multi dimension.
const FacetWriteMany = internal.FacetWriteMany

// FacetWriteNone: the dimension is read-only. It is DECLARED (not merely
// absent) so an organize edit targeting it fails loudly with "not writable"
// rather than silently — distinct from a dimension the plugin never mapped
// at all (FDR 0023 "writability must be declared").
const FacetWriteNone = internal.FacetWriteNone

// FacetWriteOne: at most one value; a write REPLACES the node's membership
// (a status change, a reschedule-by-move). Pairs with a non-Multi
// dimension.
const FacetWriteOne = internal.FacetWriteOne

// FieldCategorical is a plain discrete bucket (status, component, domain) —
// the FacetCategorical carry-over.
const FieldCategorical = internal.FieldCategorical

// FieldDate is a calendar date (optionally with a clock), presented split into a
// date and time component by a SplitDateTime-style codec.
const FieldDate = internal.FieldDate

// FieldLabelled is an opaque stable key whose human name is resolved out of band
// (a feed id, an account id) — the FacetLabelled carry-over.
const FieldLabelled = internal.FieldLabelled

// FieldNumericBucket is a number quantized to an ordered bucket whose values
// carry FieldValue.Order (a size band, priority band) — the FacetNumericBucket
// carry-over.
const FieldNumericBucket = internal.FieldNumericBucket

// FieldTag is a multi-valued category membership (iCalendar CATEGORIES, a
// carddav group, a fastmail label). MultiValued is set; a tag-interpreter codec
// maps segment hierarchy to grouping buckets (cutting-garden#231).
const FieldTag = internal.FieldTag

// FieldText is free text (a summary / description trailer) — diffed at the word
// level, never bucketed.
const FieldText = internal.FieldText
const GranularityDay = internal.GranularityDay
const GranularityMonth = internal.GranularityMonth
const GranularityYear = internal.GranularityYear

// MimeTypeDefault is the mimetype a leaf NodeType speaks when its
// declaration leaves MimeType empty: opaque bytes, dodder's null-type
// posture. Consumers MUST apply this default rather than propagating
// the empty string.
const MimeTypeDefault = internal.MimeTypeDefault

// TagAdd adds a membership: the returned tag set includes whatever tag the
// bucket edit implies, if not already present.
const TagAdd = internal.TagAdd

// TagRemove removes a membership: the returned tag set drops whatever tag
// the bucket edit implies, if present.
const TagRemove = internal.TagRemove
