// Code generated by dagnabit (0.4.1+bc7607f); DO NOT EDIT.

package cutting_garden_plugins

import internal "github.com/amarbel-llc/cutting-garden/internal/cutting_garden_plugins"

// BodyDescriber is the OPTIONAL capability a write-capable plugin implements
// to describe the create/update payloads of its writable node types, for the
// mcp server's `describe_node_types` schema tool. It is probed by type
// assertion exactly as NodeMutator / RootLister are; a plugin that omits it
// contributes types (from RootLister.Types) without payload detail.
//
// A type is reported "writable" by the schema tool iff DescribeBodies
// returns an entry for its tag — so a plugin lists exactly the types its
// NodeMutator can currently create (e.g. caldav describes its object leaf
// but not its calendar container, which awaits MKCALENDAR).
type BodyDescriber = internal.BodyDescriber

// CapturePlugin walks one capture root into the destination store,
// emitting entries and live stream events. Plugins MAY support only
// capture or only restore.
type CapturePlugin = internal.CapturePlugin

// CaptureRootRequest is what a CapturePlugin needs to walk one
// capture root: the source URL (already parsed; may be schemeless)
// and the destination blob store. Context is the command's cancelable
// context; plugins MUST observe it on long-running I/O (large file
// copies, etc.) so SIGINT/SIGTERM unwinds promptly.
type CaptureRootRequest = internal.CaptureRootRequest

// CaptureRootResult is what a CapturePlugin produces from one root:
// the entries to be folded into the receipt and a count of per-entry
// failures the stream already reported.
type CaptureRootResult = internal.CaptureRootResult

// DiffPlugin enumerates the current state at a location and returns
// entries in the same shape a CapturePlugin would produce, suitable
// for comparison against a receipt. Plugins MAY support diff without
// supporting capture or restore (e.g. a read-only HTTP listing
// plugin) or vice versa.
type DiffPlugin = internal.DiffPlugin

// DiffScanRequest is what a DiffPlugin needs to enumerate the
// current state at Dir and return entries that can be compared
// against ReceiptEntries. The plugin computes blob-ids using
// BlobStore (typically a discard-store wrapping the receipt's
// source store, so only the hash family matters). ReceiptEntries
// is provided so the plugin can run its own pre-walk validation
// (path sanitization etc.) before any I/O — diff is read-only and
// atomic.
type DiffScanRequest = internal.DiffScanRequest

// FacetCounter is the OPTIONAL capability that returns a node's hoisted facet
// summary in one operation, without the framework walking the subtree — the
// PREFERRED path, size-agnostic (an atomic listing, an in-memory index, or a
// backend GROUP BY). A plugin that can only walk its tree lazily omits it and
// the framework folds Node.Facets over ListRoots instead. See RFC 0012 §4–§5.
type FacetCounter = internal.FacetCounter

// FacetDescriber is the OPTIONAL capability that declares a plugin's facet
// schema, symmetric with BodyDescriber. Probed by type assertion on an
// already-resolved plugin. See RFC 0012 §2.
type FacetDescriber = internal.FacetDescriber

// FacetDimension declares one aggregation axis of a node type. See RFC 0012 §2.
type FacetDimension = internal.FacetDimension

// FacetFilter is a set of predicates, AND-composed. The empty filter matches
// everything; a node matches the filter iff it matches EVERY predicate. See
// RFC 0012 §6.
type FacetFilter = internal.FacetFilter

// FacetHistogram is one dimension's aggregate: a count per value Key.
// See RFC 0012 §3.
type FacetHistogram = internal.FacetHistogram

// FacetKind classifies a dimension's VALUE SHAPE. Cardinality (one vs. many
// values per node) is the separate FacetDimension.Multi flag. See RFC 0012 §2.
type FacetKind = internal.FacetKind

// FacetLabeler is the OPTIONAL capability that resolves a labelled dimension's
// opaque value keys to human display names, in batch and presentation-only.
// See RFC 0012 §7.
type FacetLabeler = internal.FacetLabeler

// FacetPredicate is one equality constraint: a node matches when its
// Facets[Dimension] contains a FacetValue whose Key == Value. See RFC 0012 §6.
type FacetPredicate = internal.FacetPredicate

// FacetResult is a hoisted summary plus whether it covers the whole subtree.
// See RFC 0012 §5.
type FacetResult = internal.FacetResult

// FacetSummary is the aggregate of all dimensions over a node set, keyed by
// FacetDimension.Key. See RFC 0012 §3. The commutative, associative merge that
// hoists leaf summaries into a container summary (RFC 0012 §3–§4.2) arrives
// with the framework-fold consumer; the one-shot FacetCounter path builds its
// summary directly, so no merge helper is published yet.
type FacetSummary = internal.FacetSummary

// FacetValue is one node's membership in one bucket of one dimension — the
// unit a plugin attaches to Node.Facets and the framework counts. See
// RFC 0012 §1.
type FacetValue = internal.FacetValue

// LeafContent is one leaf node's fetched content, returned by ReadLeaf. It
// carries two views of the same object: a structured, JSON-marshalable
// projection a client reads (the parsed fields), and the verbatim source
// bytes (the content-addressable original).
type LeafContent = internal.LeafContent

// LeafReader is the OPTIONAL capability a RootLister implements to fetch a
// single leaf node's content on demand — the per-object body-fetch backing
// MCP resources/read (cutting-garden#85). It is probed by type assertion on
// an already-resolved plugin, exactly as RootProvider is; a plugin whose
// scheme has no individually-fetchable objects omits it, and consumers fall
// back to the structure-only listing.
//
// ReadLeaf is consulted only after ListRoots reports a node has no children
// (a leaf or an empty container), so it never has to re-derive that a
// populated container is not a leaf. It is read-only: it never mutates the
// source and never writes to a blob store.
type LeafReader = internal.LeafReader

// Node is one addressable point in a RootLister plugin's capturable
// tree, as returned by ListRoots.
type Node = internal.Node

// NodeMutator is the OPTIONAL write capability: create, update, or delete a
// single addressable node in a plugin's tree — the write-side sibling of
// RootLister (FDR 0014/0020). It is probed by type assertion on an
// already-resolved plugin, exactly as RootLister / LeafReader / RootProvider
// are; a plugin whose scheme has no meaningful write surface simply omits it.
//
// Node addressing reuses the RootLister URI space verbatim: a mutation
// targets the same *url.URL a ListRoots / resources/read walk surfaces, so
// the read and write axes share one address space. CUD is NOT receipt-based —
// it mutates one live node, with no blob store and no capture receipt
// (capturing the post-mutation state is a separate `capture` invocation).
type NodeMutator = internal.NodeMutator

// NodeType is one entry in a RootLister plugin's declared type list. It
// is the unit of self-description for the traversal tree: a Node names
// its type by Tag, and a consumer resolves that Tag against the
// plugin's Types() to learn whether the node can be descended, which
// format version it speaks, and what its bytes are.
//
// Tag is a hyphenated, horizontally-versioned identifier in the
// madder/dodder scheme (e.g. "cutting_garden-caldav-calendar-v1"). The
// declared list is the plugin's backwards-compatibility surface: a
// format change adds a "-v2" entry while the "-v1" entry stays
// readable, so a consumer built against -v1 keeps working when -v2
// nodes appear beside it (see amarbel-llc/cutting-garden#79).
//
// The shape deliberately grows toward dodder's type definitions
// (dodder FDR 0010; the `!toml-type-v2` blob with binary /
// file-extension / mime-type / formatter fields), one field at a time
// as a consumer needs it — MimeType is the first.
type NodeType = internal.NodeType

// NodeTypeBody describes the create/update payload one writable node type
// accepts — the schema-discovery surface behind the mcp server's
// describe_node_types tool, so an agent can construct a valid body without
// guessing or reading an existing node first.
type NodeTypeBody = internal.NodeTypeBody

// NodeTypeFacets binds a set of facet dimensions to one node type. See
// RFC 0012 §2.
type NodeTypeFacets = internal.NodeTypeFacets

// NopReporter is the no-op Stream.
type NopReporter = internal.NopReporter

// Plugin is the cross-cutting identity every capture or restore
// backend must declare. Schemes returns the URI schemes a plugin
// handles; the empty string registers the plugin as the schemeless
// default and SHOULD only be claimed by one plugin per binary.
type Plugin = internal.Plugin

// ProtocolCapturePlugin is the opt-in interface a capture plugin
// implements to emit an RFC 0002 receipt merkle tree instead of (or in
// addition to) the EntryV1 stream of CapturePlugin.CaptureRoot. When the
// orchestrator resolves a capture plugin that also satisfies this
// interface, it routes the root through CaptureProtocol and records the
// returned receipt id directly — the per-root capture produces its own
// self-contained receipt rather than folding EntryV1 records into a
// shared store-group receipt.
type ProtocolCapturePlugin = internal.ProtocolCapturePlugin

// ProtocolCaptureRequest is what a ProtocolCapturePlugin needs to
// materialize one capture as a Capture Plugin Protocol (RFC 0002) merkle
// tree: the parsed source, the destination blob store (the protocol
// "writer" sink), and the command's cancelable context. RawArg is the
// original CLI argument, for diagnostics.
type ProtocolCaptureRequest = internal.ProtocolCaptureRequest

// ProtocolCaptureResult is the orchestrator-visible output of one
// protocol capture: the root receipt's markl id and the number of
// payload objects stored (for the sink's per-receipt summary).
type ProtocolCaptureResult = internal.ProtocolCaptureResult

// ProtocolDiffPlugin compares an RFC 0002 receipt against a live source.
type ProtocolDiffPlugin = internal.ProtocolDiffPlugin

// ProtocolDiffRequest is what a ProtocolDiffPlugin needs to compare a
// captured receipt against a live source: the store holding the
// receipt, the receipt id, and the parsed comparison source.
type ProtocolDiffRequest = internal.ProtocolDiffRequest

// ProtocolDiffResult carries the human-readable difference lines (empty
// when the receipt and source agree).
type ProtocolDiffResult = internal.ProtocolDiffResult

// ProtocolRestorePlugin reconstructs a capture from its receipt merkle
// tree. ProtocolKind returns the receipt kind it handles (e.g. "git").
type ProtocolRestorePlugin = internal.ProtocolRestorePlugin

// ProtocolRestoreRequest is what a ProtocolRestorePlugin needs to
// rebuild a capture from its RFC 0002 receipt: the store holding the
// receipt (and its referenced blobs), the receipt's markl id, and the
// parsed destination. Routing is by receipt *kind*, not dest scheme —
// the receipt knows how it was captured.
type ProtocolRestoreRequest = internal.ProtocolRestoreRequest
type ReportPlan = internal.ReportPlan
type ReportProgress = internal.ReportProgress

// Reporter is the unified capture-events stream. The historical name is
// kept as an alias so request structs and plugin call sites read
// unchanged; new code should say capture_events.Stream. See
// internal/capture_events for the contract and semantics.
type Reporter = internal.Reporter

// RestorePlugin materializes a receipt's entries to the destination.
type RestorePlugin = internal.RestorePlugin

// RestoreRequest is what a RestorePlugin needs to materialize a
// previously-captured tree: the receipt's parsed entries, the source
// blob store, and the destination URL (already parsed; may be
// schemeless). Context is the command's cancelable context.
type RestoreRequest = internal.RestoreRequest

// RootLister is the OPTIONAL traversal capability a Plugin implements
// when its scheme has meaningful sub-structure a user may want to
// discover, address, diff, or restore independently (a CalDAV
// endpoint's calendars, a yt-dlp channel's videos, a Drive folder's
// files). It is probed by type assertion on an already-resolved plugin,
// exactly as the orchestrator probes ProtocolCapturePlugin — there is
// no separate registry. Plugins without sub-structure (the file plugin)
// omit it, and consumers fall back to today's one-arg-one-root model.
//
// ListRoots is read-only and lazy: it returns the immediate children of
// one node, and a consumer descends a container by calling again with
// that container's URI. This hierarchical, one-level-per-call shape is
// the shape MCP `resources/list` consumes, it bounds work on large
// trees, and it lets a consumer stop at whatever depth it cares about.
//
// It is the single source of traversal truth for a plugin: capture,
// the `list` discovery command, the planned `health` command (#80), and
// a future MCP traversal server all walk the same enumeration rather
// than re-deriving the tree independently. See FDR 0014.
type RootLister = internal.RootLister

// RootProvider is the OPTIONAL capability of a RootLister that can
// enumerate its own top-level roots with no input node — the entry points
// a no-argument `mcp` / `list` surfaces (RFC 0007). It is probed by type
// assertion exactly as RootLister is.
//
// The source of the roots is plugin-defined and invisible to the caller:
// intrinsic ambient state (the file plugin's working directory),
// configured credentialed accounts (caldav), or configured preferred
// roots (a future web/yt-dlp plugin). A plugin that can enumerate none
// returns an empty slice — it then contributes nothing and does not appear
// in the aggregated listing.
type RootProvider = internal.RootProvider

// ErrAlreadyRegistered is returned by registry.Register when a
// scheme is already registered for the given direction (capture
// or restore).
var ErrAlreadyRegistered = internal.ErrAlreadyRegistered

// ErrUnknownScheme is returned by registry.Resolve when the
// scheme is not registered for the given direction.
var ErrUnknownScheme = internal.ErrUnknownScheme

// MustRegisterCapture installs p in the default capture registry
// under every scheme p.Schemes() returns. Panics on duplicate
// registration; intended for plugin init() functions where a clash
// is a programming error.
var MustRegisterCapture = internal.MustRegisterCapture

// MustRegisterDiff is the diff-direction analogue of
// MustRegisterCapture.
var MustRegisterDiff = internal.MustRegisterDiff

// MustRegisterProtocolDiff is the diff-direction analogue of
// MustRegisterProtocolRestore.
var MustRegisterProtocolDiff = internal.MustRegisterProtocolDiff

// MustRegisterProtocolRestore installs p under p.ProtocolKind(). Panics
// on duplicate registration; intended for binding init() functions.
var MustRegisterProtocolRestore = internal.MustRegisterProtocolRestore

// MustRegisterRestore is the restore-direction analogue of
// MustRegisterCapture.
var MustRegisterRestore = internal.MustRegisterRestore

// MustRegisterScheme installs p in the default scheme registry under every
// scheme p.Schemes() returns. Panics on duplicate registration; intended
// for plugin init() functions where a clash is a programming error.
//
// A plugin that already registers via MustRegisterCapture / -Restore /
// -Diff is enumerated through those registries and need not also register
// here; MustRegisterScheme is the discovery path for a plugin that
// implements none of those directions (RFC 0005, RFC 0009 §3).
var MustRegisterScheme = internal.MustRegisterScheme

// NodeTypeFor resolves a Node.Type tag against the plugin's declared
// Types() — the one lookup every traversal consumer performs. ok is
// false for an unknown tag; the zero NodeType then behaves as a leaf of
// unspecified mimetype, so a consumer built against the declared list
// neither invents descendability nor fabricates a content type beyond
// the leaf default.
var NodeTypeFor = internal.NodeTypeFor

// RegisteredPlugins returns every plugin registered in the scheme,
// capture, restore, or diff registry, deduplicated and sorted by scheme
// set. It is the read surface the `health`, `list`, and `mcp` commands use
// to enumerate plugins and probe their capabilities; the registries are
// otherwise resolve-only.
//
// The protocol registries (protocol_registry.go) contribute no new
// plugins — a protocol plugin is also registered as a capture/diff
// plugin — so protocol capabilities are detected by type-asserting the
// returned Plugin, not by enumerating those registries. The scheme
// registry (scheme_registry.go) is unioned in so a plugin registered via
// MustRegisterScheme alone — implementing none of capture/restore/diff,
// e.g. a RootProvider-only traversal plugin (RFC 0005, RFC 0009 §3) — is
// still enumerated. Dedup by scheme set means a plugin registered both via
// a direction and via MustRegisterScheme appears exactly once.
var RegisteredPlugins = internal.RegisteredPlugins

// ReporterOrNop returns r, or a no-op Stream when r is nil.
var ReporterOrNop = internal.ReporterOrNop

// ResolveCapture looks up the capture plugin registered under
// scheme. Returns an error wrapping ErrUnknownScheme on miss.
var ResolveCapture = internal.ResolveCapture

// ResolveDiff is the diff-direction analogue of ResolveCapture.
var ResolveDiff = internal.ResolveDiff

// ResolveProtocolDiff is the diff-direction analogue of
// ResolveProtocolRestore.
var ResolveProtocolDiff = internal.ResolveProtocolDiff

// ResolveProtocolRestore looks up the protocol restore plugin for a
// capture kind. Returns an error wrapping ErrUnknownScheme on miss.
var ResolveProtocolRestore = internal.ResolveProtocolRestore

// ResolveRestore is the restore-direction analogue of
// ResolveCapture.
var ResolveRestore = internal.ResolveRestore

// ResolveScheme looks up the base plugin registered under scheme via
// MustRegisterScheme. Returns an error wrapping ErrUnknownScheme on miss.
var ResolveScheme = internal.ResolveScheme

// FacetCategorical is a plain discrete bucket (status, state, domain).
const FacetCategorical = internal.FacetCategorical

// FacetLabelled is an opaque stable key whose human name is resolved out
// of band via FacetLabeler (a feed id, an account id).
const FacetLabelled = internal.FacetLabelled

// FacetNumericBucket is a number quantized to an ordered bucket; values
// carry FacetValue.Order (year, month, size band).
const FacetNumericBucket = internal.FacetNumericBucket

// MimeTypeDefault is the mimetype a leaf NodeType speaks when its
// declaration leaves MimeType empty: opaque bytes, dodder's null-type
// posture. Consumers MUST apply this default rather than propagating
// the empty string.
const MimeTypeDefault = internal.MimeTypeDefault
