// Code generated by dagnabit (0.4.0+1494bcc); DO NOT EDIT.

package plugin_blob_io

import internal "github.com/amarbel-llc/cutting-garden/internal/plugin_blob_io"

// CtxReader wraps an io.Reader so io.Copy aborts when ctx is cancelled.
// Read checks ctx.Err before each underlying Read; once ctx is done,
// every subsequent Read returns ctx.Err and io.Copy unwinds with that
// error.
//
// Granularity is one buffer (io.Copy's default 32 KiB), which keeps
// interactive cancel latency well below a second on any reasonable
// I/O path while staying allocation-free.
type CtxReader = internal.CtxReader

var NewCtxReader = internal.NewCtxReader

// WriteFileBlob streams srcPath into store and returns the content-
// addressed markl id plus the byte count. ctx is observed for
// cancellation on every Read; long copies unwind promptly on
// SIGINT/SIGTERM.
var WriteFileBlob = internal.WriteFileBlob

// WriteFileBlobProgress is WriteFileBlob with a nil-safe byte-progress
// callback: onBytes(written) is invoked with the cumulative bytes
// copied for THIS file, at least once per progressStride bytes and once
// at completion (so even a sub-stride file gets exactly one call with
// its total). onBytes == nil behaves exactly like WriteFileBlob. The
// callback is observability only — it never influences the blob bytes
// or the returned id/size.
var WriteFileBlobProgress = internal.WriteFileBlobProgress

// WriteReaderBlob streams r into store and returns the content-addressed
// markl id plus the byte count. It is the reader-based sibling of
// WriteFileBlob, used by callers that already hold an open stream (e.g.
// the git plugin piping `git cat-file` output, or an in-memory
// strings.Reader) and want to avoid a temp-file round-trip. ctx is
// observed for cancellation on every Read.
var WriteReaderBlob = internal.WriteReaderBlob
