/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 104
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 71
#define ALIAS_COUNT 0
#define TOKEN_COUNT 31
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 13
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 17
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  anon_sym_SPACE = 2,
  sym_heading_marker = 3,
  anon_sym_BANG = 4,
  sym_heading_type_name = 5,
  anon_sym_EQ = 6,
  sym_heading_dim_name = 7,
  aux_sym_heading_value_text_token1 = 8,
  anon_sym_DASH = 9,
  anon_sym_PERCENT = 10,
  anon_sym_DASH_DASH_DASH = 11,
  anon_sym_POUND = 12,
  sym_field_key = 13,
  anon_sym_AT = 14,
  sym_field_bare = 15,
  anon_sym_LT = 16,
  sym_type_name = 17,
  sym_file_path = 18,
  anon_sym_LBRACK = 19,
  anon_sym_RBRACK = 20,
  sym__box_space = 21,
  sym_box_object_id = 22,
  sym_box_bare_value = 23,
  sym_box_ident = 24,
  anon_sym_DQUOTE = 25,
  aux_sym_box_quoted_token1 = 26,
  sym_box_escape = 27,
  sym_markl_purpose = 28,
  sym_markl_format = 29,
  sym_markl_data = 30,
  sym_source_file = 31,
  sym__body_line = 32,
  sym_blank_line = 33,
  sym_heading = 34,
  sym__heading_term = 35,
  sym_heading_type = 36,
  sym_heading_dimension = 37,
  sym_heading_value = 38,
  sym_heading_value_text = 39,
  sym_object_line = 40,
  sym_description = 41,
  sym_metadata = 42,
  sym__metadata_line = 43,
  sym_description_line = 44,
  sym_description_text = 45,
  sym_field_line = 46,
  sym__field_value = 47,
  sym_field_blob = 48,
  sym_field_type = 49,
  sym_field_type_name = 50,
  sym_ref_line = 51,
  sym_reference_id = 52,
  sym_type_line = 53,
  sym_blob_line = 54,
  sym_comment_line = 55,
  sym_comment_text = 56,
  sym_box = 57,
  sym__box_item = 58,
  sym_box_blob = 59,
  sym_box_type = 60,
  sym_box_computed_tag = 61,
  sym_box_field = 62,
  sym__box_value = 63,
  sym_box_tag = 64,
  sym_box_quoted = 65,
  sym_markl_id = 66,
  aux_sym_source_file_repeat1 = 67,
  aux_sym_metadata_repeat1 = 68,
  aux_sym_box_repeat1 = 69,
  aux_sym_box_quoted_repeat1 = 70,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [anon_sym_SPACE] = " ",
  [sym_heading_marker] = "heading_marker",
  [anon_sym_BANG] = "!",
  [sym_heading_type_name] = "heading_type_name",
  [anon_sym_EQ] = "=",
  [sym_heading_dim_name] = "heading_dim_name",
  [aux_sym_heading_value_text_token1] = "heading_value_text_token1",
  [anon_sym_DASH] = "-",
  [anon_sym_PERCENT] = "%",
  [anon_sym_DASH_DASH_DASH] = "---",
  [anon_sym_POUND] = "#",
  [sym_field_key] = "field_key",
  [anon_sym_AT] = "@",
  [sym_field_bare] = "field_bare",
  [anon_sym_LT] = "<",
  [sym_type_name] = "type_name",
  [sym_file_path] = "file_path",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym__box_space] = "_box_space",
  [sym_box_object_id] = "box_object_id",
  [sym_box_bare_value] = "box_bare_value",
  [sym_box_ident] = "box_ident",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_box_quoted_token1] = "box_quoted_token1",
  [sym_box_escape] = "box_escape",
  [sym_markl_purpose] = "markl_purpose",
  [sym_markl_format] = "markl_format",
  [sym_markl_data] = "markl_data",
  [sym_source_file] = "source_file",
  [sym__body_line] = "_body_line",
  [sym_blank_line] = "blank_line",
  [sym_heading] = "heading",
  [sym__heading_term] = "_heading_term",
  [sym_heading_type] = "heading_type",
  [sym_heading_dimension] = "heading_dimension",
  [sym_heading_value] = "heading_value",
  [sym_heading_value_text] = "heading_value_text",
  [sym_object_line] = "object_line",
  [sym_description] = "description",
  [sym_metadata] = "metadata",
  [sym__metadata_line] = "_metadata_line",
  [sym_description_line] = "description_line",
  [sym_description_text] = "description_text",
  [sym_field_line] = "field_line",
  [sym__field_value] = "_field_value",
  [sym_field_blob] = "field_blob",
  [sym_field_type] = "field_type",
  [sym_field_type_name] = "field_type_name",
  [sym_ref_line] = "ref_line",
  [sym_reference_id] = "reference_id",
  [sym_type_line] = "type_line",
  [sym_blob_line] = "blob_line",
  [sym_comment_line] = "comment_line",
  [sym_comment_text] = "comment_text",
  [sym_box] = "box",
  [sym__box_item] = "_box_item",
  [sym_box_blob] = "box_blob",
  [sym_box_type] = "box_type",
  [sym_box_computed_tag] = "box_computed_tag",
  [sym_box_field] = "box_field",
  [sym__box_value] = "_box_value",
  [sym_box_tag] = "box_tag",
  [sym_box_quoted] = "box_quoted",
  [sym_markl_id] = "markl_id",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_metadata_repeat1] = "metadata_repeat1",
  [aux_sym_box_repeat1] = "box_repeat1",
  [aux_sym_box_quoted_repeat1] = "box_quoted_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [sym_heading_marker] = sym_heading_marker,
  [anon_sym_BANG] = anon_sym_BANG,
  [sym_heading_type_name] = sym_heading_type_name,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_heading_dim_name] = sym_heading_dim_name,
  [aux_sym_heading_value_text_token1] = aux_sym_heading_value_text_token1,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_DASH_DASH_DASH] = anon_sym_DASH_DASH_DASH,
  [anon_sym_POUND] = anon_sym_POUND,
  [sym_field_key] = sym_field_key,
  [anon_sym_AT] = anon_sym_AT,
  [sym_field_bare] = sym_field_bare,
  [anon_sym_LT] = anon_sym_LT,
  [sym_type_name] = sym_type_name,
  [sym_file_path] = sym_file_path,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym__box_space] = sym__box_space,
  [sym_box_object_id] = sym_box_object_id,
  [sym_box_bare_value] = sym_box_bare_value,
  [sym_box_ident] = sym_box_ident,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_box_quoted_token1] = aux_sym_box_quoted_token1,
  [sym_box_escape] = sym_box_escape,
  [sym_markl_purpose] = sym_markl_purpose,
  [sym_markl_format] = sym_markl_format,
  [sym_markl_data] = sym_markl_data,
  [sym_source_file] = sym_source_file,
  [sym__body_line] = sym__body_line,
  [sym_blank_line] = sym_blank_line,
  [sym_heading] = sym_heading,
  [sym__heading_term] = sym__heading_term,
  [sym_heading_type] = sym_heading_type,
  [sym_heading_dimension] = sym_heading_dimension,
  [sym_heading_value] = sym_heading_value,
  [sym_heading_value_text] = sym_heading_value_text,
  [sym_object_line] = sym_object_line,
  [sym_description] = sym_description,
  [sym_metadata] = sym_metadata,
  [sym__metadata_line] = sym__metadata_line,
  [sym_description_line] = sym_description_line,
  [sym_description_text] = sym_description_text,
  [sym_field_line] = sym_field_line,
  [sym__field_value] = sym__field_value,
  [sym_field_blob] = sym_field_blob,
  [sym_field_type] = sym_field_type,
  [sym_field_type_name] = sym_field_type_name,
  [sym_ref_line] = sym_ref_line,
  [sym_reference_id] = sym_reference_id,
  [sym_type_line] = sym_type_line,
  [sym_blob_line] = sym_blob_line,
  [sym_comment_line] = sym_comment_line,
  [sym_comment_text] = sym_comment_text,
  [sym_box] = sym_box,
  [sym__box_item] = sym__box_item,
  [sym_box_blob] = sym_box_blob,
  [sym_box_type] = sym_box_type,
  [sym_box_computed_tag] = sym_box_computed_tag,
  [sym_box_field] = sym_box_field,
  [sym__box_value] = sym__box_value,
  [sym_box_tag] = sym_box_tag,
  [sym_box_quoted] = sym_box_quoted,
  [sym_markl_id] = sym_markl_id,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_metadata_repeat1] = aux_sym_metadata_repeat1,
  [aux_sym_box_repeat1] = aux_sym_box_repeat1,
  [aux_sym_box_quoted_repeat1] = aux_sym_box_quoted_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [sym_heading_marker] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [sym_heading_type_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_heading_dim_name] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_heading_value_text_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [sym_field_key] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [sym_field_bare] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [sym_type_name] = {
    .visible = true,
    .named = true,
  },
  [sym_file_path] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym__box_space] = {
    .visible = false,
    .named = true,
  },
  [sym_box_object_id] = {
    .visible = true,
    .named = true,
  },
  [sym_box_bare_value] = {
    .visible = true,
    .named = true,
  },
  [sym_box_ident] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_box_quoted_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_box_escape] = {
    .visible = true,
    .named = true,
  },
  [sym_markl_purpose] = {
    .visible = true,
    .named = true,
  },
  [sym_markl_format] = {
    .visible = true,
    .named = true,
  },
  [sym_markl_data] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__body_line] = {
    .visible = false,
    .named = true,
  },
  [sym_blank_line] = {
    .visible = true,
    .named = true,
  },
  [sym_heading] = {
    .visible = true,
    .named = true,
  },
  [sym__heading_term] = {
    .visible = false,
    .named = true,
  },
  [sym_heading_type] = {
    .visible = true,
    .named = true,
  },
  [sym_heading_dimension] = {
    .visible = true,
    .named = true,
  },
  [sym_heading_value] = {
    .visible = true,
    .named = true,
  },
  [sym_heading_value_text] = {
    .visible = true,
    .named = true,
  },
  [sym_object_line] = {
    .visible = true,
    .named = true,
  },
  [sym_description] = {
    .visible = true,
    .named = true,
  },
  [sym_metadata] = {
    .visible = true,
    .named = true,
  },
  [sym__metadata_line] = {
    .visible = false,
    .named = true,
  },
  [sym_description_line] = {
    .visible = true,
    .named = true,
  },
  [sym_description_text] = {
    .visible = true,
    .named = true,
  },
  [sym_field_line] = {
    .visible = true,
    .named = true,
  },
  [sym__field_value] = {
    .visible = false,
    .named = true,
  },
  [sym_field_blob] = {
    .visible = true,
    .named = true,
  },
  [sym_field_type] = {
    .visible = true,
    .named = true,
  },
  [sym_field_type_name] = {
    .visible = true,
    .named = true,
  },
  [sym_ref_line] = {
    .visible = true,
    .named = true,
  },
  [sym_reference_id] = {
    .visible = true,
    .named = true,
  },
  [sym_type_line] = {
    .visible = true,
    .named = true,
  },
  [sym_blob_line] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_line] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_text] = {
    .visible = true,
    .named = true,
  },
  [sym_box] = {
    .visible = true,
    .named = true,
  },
  [sym__box_item] = {
    .visible = false,
    .named = true,
  },
  [sym_box_blob] = {
    .visible = true,
    .named = true,
  },
  [sym_box_type] = {
    .visible = true,
    .named = true,
  },
  [sym_box_computed_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_box_field] = {
    .visible = true,
    .named = true,
  },
  [sym__box_value] = {
    .visible = false,
    .named = true,
  },
  [sym_box_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_box_quoted] = {
    .visible = true,
    .named = true,
  },
  [sym_markl_id] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_metadata_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_box_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_box_quoted_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_data = 1,
  field_description = 2,
  field_format = 3,
  field_id = 4,
  field_key = 5,
  field_lock = 6,
  field_marker = 7,
  field_name = 8,
  field_prefix = 9,
  field_ref = 10,
  field_text = 11,
  field_type = 12,
  field_value = 13,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_data] = "data",
  [field_description] = "description",
  [field_format] = "format",
  [field_id] = "id",
  [field_key] = "key",
  [field_lock] = "lock",
  [field_marker] = "marker",
  [field_name] = "name",
  [field_prefix] = "prefix",
  [field_ref] = "ref",
  [field_text] = "text",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 1},
  [6] = {.index = 5, .length = 1},
  [7] = {.index = 6, .length = 1},
  [8] = {.index = 7, .length = 2},
  [9] = {.index = 9, .length = 1},
  [10] = {.index = 10, .length = 1},
  [11] = {.index = 11, .length = 1},
  [12] = {.index = 12, .length = 2},
  [13] = {.index = 14, .length = 2},
  [14] = {.index = 16, .length = 2},
  [15] = {.index = 18, .length = 2},
  [16] = {.index = 20, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_value, 1},
  [2] =
    {field_name, 0},
  [3] =
    {field_marker, 0},
  [4] =
    {field_prefix, 0},
  [5] =
    {field_id, 1},
  [6] =
    {field_text, 1},
  [7] =
    {field_description, 4},
    {field_prefix, 0},
  [9] =
    {field_type, 2},
  [10] =
    {field_text, 2},
  [11] =
    {field_ref, 2},
  [12] =
    {field_data, 2},
    {field_format, 0},
  [14] =
    {field_key, 0},
    {field_value, 2},
  [16] =
    {field_lock, 4},
    {field_type, 2},
  [18] =
    {field_data, 3},
    {field_format, 1},
  [20] =
    {field_key, 2},
    {field_value, 6},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(21);
      ADVANCE_MAP(
        '\n', 22,
        ' ', 23,
        '!', 25,
        '"', 52,
        '#', 35,
        '%', 32,
        '-', 31,
        '<', 39,
        '=', 28,
        '@', 37,
        '[', 42,
        '\\', 19,
        ']', 43,
        '_', 56,
      );
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 2:
      if (lookahead == '!') ADVANCE(25);
      if (lookahead == '#') ADVANCE(34);
      if (lookahead == '%') ADVANCE(32);
      if (lookahead == '-') ADVANCE(31);
      if (lookahead == '<') ADVANCE(39);
      if (lookahead == '@') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 3:
      if (lookahead == '!') ADVANCE(25);
      if (lookahead == '@') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(38);
      END_STATE();
    case 4:
      if (lookahead == '!') ADVANCE(26);
      if (lookahead == '=') ADVANCE(28);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!') ADVANCE(29);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(52);
      if (lookahead == '\\') ADVANCE(19);
      if (lookahead != 0) ADVANCE(53);
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(52);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != ' ' &&
          lookahead != ']') ADVANCE(50);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(33);
      END_STATE();
    case 8:
      if (lookahead == '.') ADVANCE(10);
      if (lookahead == '@') ADVANCE(55);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(11);
      END_STATE();
    case 9:
      if (lookahead == '.') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(11);
      END_STATE();
    case 10:
      if (lookahead == '.') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(41);
      END_STATE();
    case 11:
      if (lookahead == '.') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(11);
      END_STATE();
    case 12:
      if (lookahead == '@') ADVANCE(55);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 14:
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 15:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 16:
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '=') ADVANCE(36);
      END_STATE();
    case 17:
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(27);
      END_STATE();
    case 18:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(40);
      END_STATE();
    case 19:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(54);
      END_STATE();
    case 20:
      if (eof) ADVANCE(21);
      ADVANCE_MAP(
        '\n', 22,
        '!', 25,
        '"', 52,
        '#', 24,
        '%', 32,
        '-', 31,
        '=', 28,
        '@', 37,
        ']', 43,
        '\t', 44,
        ' ', 44,
      );
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_SPACE);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_heading_marker);
      if (lookahead == '#') ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_BANG);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '=') ADVANCE(29);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_heading_type_name);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_heading_dim_name);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '=') ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_heading_value_text_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '-') ADVANCE(7);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_DASH_DASH_DASH);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead == '#') ADVANCE(24);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_field_key);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '=') ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_field_bare);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_type_name);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_file_path);
      if (lookahead == '.') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym__box_space);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_box_object_id);
      if (lookahead == '-') ADVANCE(47);
      if (lookahead == '@') ADVANCE(55);
      if (lookahead == '_') ADVANCE(46);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(49);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_box_object_id);
      if (lookahead == '-') ADVANCE(47);
      if (lookahead == '@') ADVANCE(55);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(49);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_box_object_id);
      if (lookahead == '@') ADVANCE(55);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(49);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(48);
      if (('-' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_box_object_id);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(49);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_box_object_id);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_box_bare_value);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != ']') ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_box_ident);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_box_quoted_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(53);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_box_escape);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_markl_purpose);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_markl_format);
      if (lookahead == '-') ADVANCE(12);
      if (lookahead == '@') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_markl_format);
      if (lookahead == '-') ADVANCE(8);
      if (lookahead == '.') ADVANCE(10);
      if (lookahead == '@') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(11);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_markl_format);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_markl_data);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 20},
  [2] = {.lex_state = 2},
  [3] = {.lex_state = 2},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 20},
  [6] = {.lex_state = 20},
  [7] = {.lex_state = 20},
  [8] = {.lex_state = 20},
  [9] = {.lex_state = 20},
  [10] = {.lex_state = 20},
  [11] = {.lex_state = 20},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 4},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 3},
  [22] = {.lex_state = 20},
  [23] = {.lex_state = 20},
  [24] = {.lex_state = 20},
  [25] = {.lex_state = 20},
  [26] = {.lex_state = 20},
  [27] = {.lex_state = 20},
  [28] = {.lex_state = 9},
  [29] = {.lex_state = 5},
  [30] = {.lex_state = 5},
  [31] = {.lex_state = 5},
  [32] = {.lex_state = 6},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 20},
  [35] = {.lex_state = 20},
  [36] = {.lex_state = 20},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 20},
  [41] = {.lex_state = 20},
  [42] = {.lex_state = 20},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 20},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 20},
  [53] = {.lex_state = 20},
  [54] = {.lex_state = 20},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 20},
  [58] = {.lex_state = 20},
  [59] = {.lex_state = 20},
  [60] = {.lex_state = 1},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 17},
  [63] = {.lex_state = 16},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 13},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 18},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 20},
  [82] = {.lex_state = 15},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 13},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 14},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 20},
  [103] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_SPACE] = ACTIONS(1),
    [sym_heading_marker] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_DASH_DASH_DASH] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_box_object_id] = ACTIONS(1),
    [sym_box_ident] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_box_escape] = ACTIONS(1),
    [sym_markl_purpose] = ACTIONS(1),
    [sym_markl_format] = ACTIONS(1),
    [sym_markl_data] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(97),
    [sym__body_line] = STATE(9),
    [sym_blank_line] = STATE(9),
    [sym_heading] = STATE(9),
    [sym_object_line] = STATE(9),
    [sym_metadata] = STATE(10),
    [aux_sym_source_file_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(5),
    [sym_heading_marker] = ACTIONS(7),
    [anon_sym_DASH] = ACTIONS(9),
    [anon_sym_PERCENT] = ACTIONS(11),
    [anon_sym_DASH_DASH_DASH] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(15), 1,
      anon_sym_BANG,
    ACTIONS(17), 1,
      anon_sym_DASH,
    ACTIONS(19), 1,
      anon_sym_PERCENT,
    ACTIONS(21), 1,
      anon_sym_DASH_DASH_DASH,
    ACTIONS(23), 1,
      anon_sym_POUND,
    ACTIONS(25), 1,
      anon_sym_AT,
    ACTIONS(27), 1,
      anon_sym_LT,
    STATE(3), 8,
      sym__metadata_line,
      sym_description_line,
      sym_field_line,
      sym_ref_line,
      sym_type_line,
      sym_blob_line,
      sym_comment_line,
      aux_sym_metadata_repeat1,
  [32] = 8,
    ACTIONS(15), 1,
      anon_sym_BANG,
    ACTIONS(17), 1,
      anon_sym_DASH,
    ACTIONS(19), 1,
      anon_sym_PERCENT,
    ACTIONS(23), 1,
      anon_sym_POUND,
    ACTIONS(25), 1,
      anon_sym_AT,
    ACTIONS(27), 1,
      anon_sym_LT,
    ACTIONS(29), 1,
      anon_sym_DASH_DASH_DASH,
    STATE(4), 8,
      sym__metadata_line,
      sym_description_line,
      sym_field_line,
      sym_ref_line,
      sym_type_line,
      sym_blob_line,
      sym_comment_line,
      aux_sym_metadata_repeat1,
  [64] = 8,
    ACTIONS(31), 1,
      anon_sym_BANG,
    ACTIONS(34), 1,
      anon_sym_DASH,
    ACTIONS(37), 1,
      anon_sym_PERCENT,
    ACTIONS(40), 1,
      anon_sym_DASH_DASH_DASH,
    ACTIONS(42), 1,
      anon_sym_POUND,
    ACTIONS(45), 1,
      anon_sym_AT,
    ACTIONS(48), 1,
      anon_sym_LT,
    STATE(4), 8,
      sym__metadata_line,
      sym_description_line,
      sym_field_line,
      sym_ref_line,
      sym_type_line,
      sym_blob_line,
      sym_comment_line,
      aux_sym_metadata_repeat1,
  [96] = 7,
    ACTIONS(51), 1,
      anon_sym_BANG,
    ACTIONS(53), 1,
      anon_sym_PERCENT,
    ACTIONS(55), 1,
      anon_sym_AT,
    ACTIONS(57), 1,
      anon_sym_RBRACK,
    ACTIONS(59), 1,
      sym_box_ident,
    ACTIONS(61), 1,
      anon_sym_DQUOTE,
    STATE(50), 7,
      sym__box_item,
      sym_box_blob,
      sym_box_type,
      sym_box_computed_tag,
      sym_box_field,
      sym_box_tag,
      sym_box_quoted,
  [124] = 7,
    ACTIONS(51), 1,
      anon_sym_BANG,
    ACTIONS(53), 1,
      anon_sym_PERCENT,
    ACTIONS(55), 1,
      anon_sym_AT,
    ACTIONS(59), 1,
      sym_box_ident,
    ACTIONS(61), 1,
      anon_sym_DQUOTE,
    ACTIONS(63), 1,
      anon_sym_RBRACK,
    STATE(50), 7,
      sym__box_item,
      sym_box_blob,
      sym_box_type,
      sym_box_computed_tag,
      sym_box_field,
      sym_box_tag,
      sym_box_quoted,
  [152] = 6,
    ACTIONS(51), 1,
      anon_sym_BANG,
    ACTIONS(53), 1,
      anon_sym_PERCENT,
    ACTIONS(55), 1,
      anon_sym_AT,
    ACTIONS(59), 1,
      sym_box_ident,
    ACTIONS(61), 1,
      anon_sym_DQUOTE,
    STATE(50), 7,
      sym__box_item,
      sym_box_blob,
      sym_box_type,
      sym_box_computed_tag,
      sym_box_field,
      sym_box_tag,
      sym_box_quoted,
  [177] = 5,
    ACTIONS(65), 1,
      ts_builtin_sym_end,
    ACTIONS(67), 1,
      anon_sym_LF,
    ACTIONS(70), 1,
      sym_heading_marker,
    ACTIONS(73), 2,
      anon_sym_DASH,
      anon_sym_PERCENT,
    STATE(8), 5,
      sym__body_line,
      sym_blank_line,
      sym_heading,
      sym_object_line,
      aux_sym_source_file_repeat1,
  [198] = 5,
    ACTIONS(5), 1,
      anon_sym_LF,
    ACTIONS(7), 1,
      sym_heading_marker,
    ACTIONS(76), 1,
      ts_builtin_sym_end,
    ACTIONS(11), 2,
      anon_sym_DASH,
      anon_sym_PERCENT,
    STATE(8), 5,
      sym__body_line,
      sym_blank_line,
      sym_heading,
      sym_object_line,
      aux_sym_source_file_repeat1,
  [219] = 5,
    ACTIONS(5), 1,
      anon_sym_LF,
    ACTIONS(7), 1,
      sym_heading_marker,
    ACTIONS(76), 1,
      ts_builtin_sym_end,
    ACTIONS(11), 2,
      anon_sym_DASH,
      anon_sym_PERCENT,
    STATE(11), 5,
      sym__body_line,
      sym_blank_line,
      sym_heading,
      sym_object_line,
      aux_sym_source_file_repeat1,
  [240] = 5,
    ACTIONS(5), 1,
      anon_sym_LF,
    ACTIONS(7), 1,
      sym_heading_marker,
    ACTIONS(78), 1,
      ts_builtin_sym_end,
    ACTIONS(11), 2,
      anon_sym_DASH,
      anon_sym_PERCENT,
    STATE(8), 5,
      sym__body_line,
      sym_blank_line,
      sym_heading,
      sym_object_line,
      aux_sym_source_file_repeat1,
  [261] = 2,
    ACTIONS(82), 1,
      anon_sym_DASH,
    ACTIONS(80), 6,
      anon_sym_BANG,
      anon_sym_PERCENT,
      anon_sym_DASH_DASH_DASH,
      anon_sym_POUND,
      anon_sym_AT,
      anon_sym_LT,
  [273] = 4,
    ACTIONS(84), 1,
      anon_sym_BANG,
    ACTIONS(86), 1,
      anon_sym_EQ,
    ACTIONS(88), 1,
      sym_heading_dim_name,
    STATE(68), 4,
      sym__heading_term,
      sym_heading_type,
      sym_heading_dimension,
      sym_heading_value,
  [289] = 2,
    ACTIONS(92), 1,
      anon_sym_DASH,
    ACTIONS(90), 6,
      anon_sym_BANG,
      anon_sym_PERCENT,
      anon_sym_DASH_DASH_DASH,
      anon_sym_POUND,
      anon_sym_AT,
      anon_sym_LT,
  [301] = 2,
    ACTIONS(96), 1,
      anon_sym_DASH,
    ACTIONS(94), 6,
      anon_sym_BANG,
      anon_sym_PERCENT,
      anon_sym_DASH_DASH_DASH,
      anon_sym_POUND,
      anon_sym_AT,
      anon_sym_LT,
  [313] = 2,
    ACTIONS(100), 1,
      anon_sym_DASH,
    ACTIONS(98), 6,
      anon_sym_BANG,
      anon_sym_PERCENT,
      anon_sym_DASH_DASH_DASH,
      anon_sym_POUND,
      anon_sym_AT,
      anon_sym_LT,
  [325] = 2,
    ACTIONS(104), 1,
      anon_sym_DASH,
    ACTIONS(102), 6,
      anon_sym_BANG,
      anon_sym_PERCENT,
      anon_sym_DASH_DASH_DASH,
      anon_sym_POUND,
      anon_sym_AT,
      anon_sym_LT,
  [337] = 2,
    ACTIONS(108), 1,
      anon_sym_DASH,
    ACTIONS(106), 6,
      anon_sym_BANG,
      anon_sym_PERCENT,
      anon_sym_DASH_DASH_DASH,
      anon_sym_POUND,
      anon_sym_AT,
      anon_sym_LT,
  [349] = 2,
    ACTIONS(112), 1,
      anon_sym_DASH,
    ACTIONS(110), 6,
      anon_sym_BANG,
      anon_sym_PERCENT,
      anon_sym_DASH_DASH_DASH,
      anon_sym_POUND,
      anon_sym_AT,
      anon_sym_LT,
  [361] = 2,
    ACTIONS(116), 1,
      anon_sym_DASH,
    ACTIONS(114), 6,
      anon_sym_BANG,
      anon_sym_PERCENT,
      anon_sym_DASH_DASH_DASH,
      anon_sym_POUND,
      anon_sym_AT,
      anon_sym_LT,
  [373] = 4,
    ACTIONS(118), 1,
      anon_sym_BANG,
    ACTIONS(120), 1,
      anon_sym_AT,
    ACTIONS(122), 1,
      sym_field_bare,
    STATE(98), 3,
      sym__field_value,
      sym_field_blob,
      sym_field_type,
  [388] = 1,
    ACTIONS(124), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_heading_marker,
      anon_sym_DASH,
      anon_sym_PERCENT,
  [396] = 1,
    ACTIONS(126), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_heading_marker,
      anon_sym_DASH,
      anon_sym_PERCENT,
  [404] = 1,
    ACTIONS(128), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_heading_marker,
      anon_sym_DASH,
      anon_sym_PERCENT,
  [412] = 1,
    ACTIONS(130), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_heading_marker,
      anon_sym_DASH,
      anon_sym_PERCENT,
  [420] = 1,
    ACTIONS(132), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_heading_marker,
      anon_sym_DASH,
      anon_sym_PERCENT,
  [428] = 1,
    ACTIONS(134), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_heading_marker,
      anon_sym_DASH,
      anon_sym_PERCENT,
  [436] = 4,
    ACTIONS(136), 1,
      sym_file_path,
    ACTIONS(138), 1,
      sym_markl_purpose,
    ACTIONS(140), 1,
      sym_markl_format,
    STATE(89), 1,
      sym_markl_id,
  [449] = 3,
    ACTIONS(142), 1,
      anon_sym_DQUOTE,
    STATE(31), 1,
      aux_sym_box_quoted_repeat1,
    ACTIONS(144), 2,
      aux_sym_box_quoted_token1,
      sym_box_escape,
  [460] = 3,
    ACTIONS(146), 1,
      anon_sym_DQUOTE,
    STATE(30), 1,
      aux_sym_box_quoted_repeat1,
    ACTIONS(148), 2,
      aux_sym_box_quoted_token1,
      sym_box_escape,
  [471] = 3,
    ACTIONS(151), 1,
      anon_sym_DQUOTE,
    STATE(30), 1,
      aux_sym_box_quoted_repeat1,
    ACTIONS(153), 2,
      aux_sym_box_quoted_token1,
      sym_box_escape,
  [482] = 3,
    ACTIONS(61), 1,
      anon_sym_DQUOTE,
    ACTIONS(155), 1,
      sym_box_bare_value,
    STATE(57), 2,
      sym__box_value,
      sym_box_quoted,
  [493] = 3,
    ACTIONS(138), 1,
      sym_markl_purpose,
    ACTIONS(140), 1,
      sym_markl_format,
    STATE(101), 1,
      sym_markl_id,
  [503] = 3,
    ACTIONS(157), 1,
      anon_sym_RBRACK,
    ACTIONS(159), 1,
      sym__box_space,
    STATE(34), 1,
      aux_sym_box_repeat1,
  [513] = 2,
    ACTIONS(162), 1,
      anon_sym_EQ,
    ACTIONS(164), 2,
      anon_sym_RBRACK,
      sym__box_space,
  [521] = 3,
    ACTIONS(57), 1,
      anon_sym_RBRACK,
    ACTIONS(166), 1,
      sym__box_space,
    STATE(34), 1,
      aux_sym_box_repeat1,
  [531] = 3,
    ACTIONS(138), 1,
      sym_markl_purpose,
    ACTIONS(140), 1,
      sym_markl_format,
    STATE(52), 1,
      sym_markl_id,
  [541] = 3,
    ACTIONS(168), 1,
      anon_sym_LF,
    ACTIONS(170), 1,
      aux_sym_heading_value_text_token1,
    STATE(70), 1,
      sym_comment_text,
  [551] = 3,
    ACTIONS(138), 1,
      sym_markl_purpose,
    ACTIONS(140), 1,
      sym_markl_format,
    STATE(86), 1,
      sym_markl_id,
  [561] = 1,
    ACTIONS(172), 3,
      anon_sym_LF,
      anon_sym_RBRACK,
      sym__box_space,
  [567] = 1,
    ACTIONS(174), 3,
      anon_sym_LF,
      anon_sym_RBRACK,
      sym__box_space,
  [573] = 3,
    ACTIONS(176), 1,
      anon_sym_RBRACK,
    ACTIONS(178), 1,
      sym__box_space,
    STATE(36), 1,
      aux_sym_box_repeat1,
  [583] = 1,
    ACTIONS(180), 2,
      anon_sym_LF,
      anon_sym_SPACE,
  [588] = 2,
    ACTIONS(182), 1,
      aux_sym_heading_value_text_token1,
    STATE(84), 1,
      sym_description_text,
  [595] = 2,
    ACTIONS(184), 1,
      anon_sym_LF,
    ACTIONS(186), 1,
      anon_sym_AT,
  [602] = 2,
    ACTIONS(188), 1,
      aux_sym_heading_value_text_token1,
    STATE(93), 1,
      sym_heading_value_text,
  [609] = 1,
    ACTIONS(190), 2,
      anon_sym_LF,
      anon_sym_SPACE,
  [614] = 2,
    ACTIONS(192), 1,
      aux_sym_heading_value_text_token1,
    STATE(96), 1,
      sym_reference_id,
  [621] = 2,
    ACTIONS(194), 1,
      anon_sym_LF,
    ACTIONS(196), 1,
      anon_sym_SPACE,
  [628] = 1,
    ACTIONS(157), 2,
      anon_sym_RBRACK,
      sym__box_space,
  [633] = 2,
    ACTIONS(198), 1,
      aux_sym_heading_value_text_token1,
    STATE(78), 1,
      sym_description,
  [640] = 1,
    ACTIONS(200), 2,
      anon_sym_RBRACK,
      sym__box_space,
  [645] = 1,
    ACTIONS(202), 2,
      anon_sym_RBRACK,
      sym__box_space,
  [650] = 1,
    ACTIONS(204), 2,
      anon_sym_RBRACK,
      sym__box_space,
  [655] = 1,
    ACTIONS(206), 2,
      anon_sym_LF,
      anon_sym_SPACE,
  [660] = 2,
    ACTIONS(208), 1,
      anon_sym_LBRACK,
    STATE(49), 1,
      sym_box,
  [667] = 1,
    ACTIONS(210), 2,
      anon_sym_RBRACK,
      sym__box_space,
  [672] = 1,
    ACTIONS(212), 2,
      anon_sym_RBRACK,
      sym__box_space,
  [677] = 1,
    ACTIONS(214), 2,
      anon_sym_RBRACK,
      sym__box_space,
  [682] = 2,
    ACTIONS(216), 1,
      aux_sym_heading_value_text_token1,
    STATE(100), 1,
      sym_field_type_name,
  [689] = 1,
    ACTIONS(218), 1,
      anon_sym_EQ,
  [693] = 1,
    ACTIONS(220), 1,
      sym_heading_type_name,
  [697] = 1,
    ACTIONS(222), 1,
      sym_field_key,
  [701] = 1,
    ACTIONS(224), 1,
      anon_sym_SPACE,
  [705] = 1,
    ACTIONS(226), 1,
      anon_sym_EQ,
  [709] = 1,
    ACTIONS(228), 1,
      anon_sym_LF,
  [713] = 1,
    ACTIONS(230), 1,
      anon_sym_SPACE,
  [717] = 1,
    ACTIONS(232), 1,
      anon_sym_LF,
  [721] = 1,
    ACTIONS(234), 1,
      anon_sym_SPACE,
  [725] = 1,
    ACTIONS(236), 1,
      anon_sym_LF,
  [729] = 1,
    ACTIONS(238), 1,
      anon_sym_LF,
  [733] = 1,
    ACTIONS(240), 1,
      anon_sym_SPACE,
  [737] = 1,
    ACTIONS(242), 1,
      anon_sym_LF,
  [741] = 1,
    ACTIONS(244), 1,
      anon_sym_SPACE,
  [745] = 1,
    ACTIONS(246), 1,
      anon_sym_DASH,
  [749] = 1,
    ACTIONS(248), 1,
      sym_markl_data,
  [753] = 1,
    ACTIONS(250), 1,
      anon_sym_SPACE,
  [757] = 1,
    ACTIONS(252), 1,
      anon_sym_LF,
  [761] = 1,
    ACTIONS(254), 1,
      sym_type_name,
  [765] = 1,
    ACTIONS(256), 1,
      anon_sym_SPACE,
  [769] = 1,
    ACTIONS(258), 1,
      sym_box_ident,
  [773] = 1,
    ACTIONS(260), 1,
      sym_box_object_id,
  [777] = 1,
    ACTIONS(262), 1,
      anon_sym_LF,
  [781] = 1,
    ACTIONS(264), 1,
      anon_sym_LF,
  [785] = 1,
    ACTIONS(266), 1,
      anon_sym_LF,
  [789] = 1,
    ACTIONS(268), 1,
      anon_sym_LF,
  [793] = 1,
    ACTIONS(270), 1,
      anon_sym_SPACE,
  [797] = 1,
    ACTIONS(272), 1,
      sym_markl_data,
  [801] = 1,
    ACTIONS(274), 1,
      anon_sym_LF,
  [805] = 1,
    ACTIONS(276), 1,
      sym_markl_format,
  [809] = 1,
    ACTIONS(278), 1,
      anon_sym_DASH,
  [813] = 1,
    ACTIONS(280), 1,
      anon_sym_LF,
  [817] = 1,
    ACTIONS(282), 1,
      anon_sym_LF,
  [821] = 1,
    ACTIONS(284), 1,
      anon_sym_LF,
  [825] = 1,
    ACTIONS(286), 1,
      anon_sym_LF,
  [829] = 1,
    ACTIONS(288), 1,
      anon_sym_LF,
  [833] = 1,
    ACTIONS(290), 1,
      ts_builtin_sym_end,
  [837] = 1,
    ACTIONS(292), 1,
      anon_sym_LF,
  [841] = 1,
    ACTIONS(294), 1,
      anon_sym_LF,
  [845] = 1,
    ACTIONS(296), 1,
      anon_sym_LF,
  [849] = 1,
    ACTIONS(298), 1,
      anon_sym_LF,
  [853] = 1,
    ACTIONS(300), 1,
      sym_box_ident,
  [857] = 1,
    ACTIONS(302), 1,
      anon_sym_SPACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 32,
  [SMALL_STATE(4)] = 64,
  [SMALL_STATE(5)] = 96,
  [SMALL_STATE(6)] = 124,
  [SMALL_STATE(7)] = 152,
  [SMALL_STATE(8)] = 177,
  [SMALL_STATE(9)] = 198,
  [SMALL_STATE(10)] = 219,
  [SMALL_STATE(11)] = 240,
  [SMALL_STATE(12)] = 261,
  [SMALL_STATE(13)] = 273,
  [SMALL_STATE(14)] = 289,
  [SMALL_STATE(15)] = 301,
  [SMALL_STATE(16)] = 313,
  [SMALL_STATE(17)] = 325,
  [SMALL_STATE(18)] = 337,
  [SMALL_STATE(19)] = 349,
  [SMALL_STATE(20)] = 361,
  [SMALL_STATE(21)] = 373,
  [SMALL_STATE(22)] = 388,
  [SMALL_STATE(23)] = 396,
  [SMALL_STATE(24)] = 404,
  [SMALL_STATE(25)] = 412,
  [SMALL_STATE(26)] = 420,
  [SMALL_STATE(27)] = 428,
  [SMALL_STATE(28)] = 436,
  [SMALL_STATE(29)] = 449,
  [SMALL_STATE(30)] = 460,
  [SMALL_STATE(31)] = 471,
  [SMALL_STATE(32)] = 482,
  [SMALL_STATE(33)] = 493,
  [SMALL_STATE(34)] = 503,
  [SMALL_STATE(35)] = 513,
  [SMALL_STATE(36)] = 521,
  [SMALL_STATE(37)] = 531,
  [SMALL_STATE(38)] = 541,
  [SMALL_STATE(39)] = 551,
  [SMALL_STATE(40)] = 561,
  [SMALL_STATE(41)] = 567,
  [SMALL_STATE(42)] = 573,
  [SMALL_STATE(43)] = 583,
  [SMALL_STATE(44)] = 588,
  [SMALL_STATE(45)] = 595,
  [SMALL_STATE(46)] = 602,
  [SMALL_STATE(47)] = 609,
  [SMALL_STATE(48)] = 614,
  [SMALL_STATE(49)] = 621,
  [SMALL_STATE(50)] = 628,
  [SMALL_STATE(51)] = 633,
  [SMALL_STATE(52)] = 640,
  [SMALL_STATE(53)] = 645,
  [SMALL_STATE(54)] = 650,
  [SMALL_STATE(55)] = 655,
  [SMALL_STATE(56)] = 660,
  [SMALL_STATE(57)] = 667,
  [SMALL_STATE(58)] = 672,
  [SMALL_STATE(59)] = 677,
  [SMALL_STATE(60)] = 682,
  [SMALL_STATE(61)] = 689,
  [SMALL_STATE(62)] = 693,
  [SMALL_STATE(63)] = 697,
  [SMALL_STATE(64)] = 701,
  [SMALL_STATE(65)] = 705,
  [SMALL_STATE(66)] = 709,
  [SMALL_STATE(67)] = 713,
  [SMALL_STATE(68)] = 717,
  [SMALL_STATE(69)] = 721,
  [SMALL_STATE(70)] = 725,
  [SMALL_STATE(71)] = 729,
  [SMALL_STATE(72)] = 733,
  [SMALL_STATE(73)] = 737,
  [SMALL_STATE(74)] = 741,
  [SMALL_STATE(75)] = 745,
  [SMALL_STATE(76)] = 749,
  [SMALL_STATE(77)] = 753,
  [SMALL_STATE(78)] = 757,
  [SMALL_STATE(79)] = 761,
  [SMALL_STATE(80)] = 765,
  [SMALL_STATE(81)] = 769,
  [SMALL_STATE(82)] = 773,
  [SMALL_STATE(83)] = 777,
  [SMALL_STATE(84)] = 781,
  [SMALL_STATE(85)] = 785,
  [SMALL_STATE(86)] = 789,
  [SMALL_STATE(87)] = 793,
  [SMALL_STATE(88)] = 797,
  [SMALL_STATE(89)] = 801,
  [SMALL_STATE(90)] = 805,
  [SMALL_STATE(91)] = 809,
  [SMALL_STATE(92)] = 813,
  [SMALL_STATE(93)] = 817,
  [SMALL_STATE(94)] = 821,
  [SMALL_STATE(95)] = 825,
  [SMALL_STATE(96)] = 829,
  [SMALL_STATE(97)] = 833,
  [SMALL_STATE(98)] = 837,
  [SMALL_STATE(99)] = 841,
  [SMALL_STATE(100)] = 845,
  [SMALL_STATE(101)] = 849,
  [SMALL_STATE(102)] = 853,
  [SMALL_STATE(103)] = 857,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_metadata_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_metadata_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_metadata_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_metadata_repeat1, 2, 0, 0),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_metadata_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_metadata_repeat1, 2, 0, 0), SHIFT_REPEAT(77),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_metadata_repeat1, 2, 0, 0), SHIFT_REPEAT(103),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(72),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(64),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_line, 3, 0, 7),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment_line, 3, 0, 7),
  [84] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [88] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_line, 2, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment_line, 2, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_line, 4, 0, 9),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_line, 4, 0, 9),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_blob_line, 4, 0, 11),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_blob_line, 4, 0, 11),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ref_line, 4, 0, 11),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ref_line, 4, 0, 11),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_line, 6, 0, 14),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_line, 6, 0, 14),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_description_line, 4, 0, 10),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_description_line, 4, 0, 10),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_line, 8, 0, 16),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field_line, 8, 0, 16),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading, 4, 0, 4),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_blank_line, 1, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_metadata, 3, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_metadata, 4, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_line, 4, 0, 5),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_line, 6, 0, 8),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [140] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_box_quoted_repeat1, 2, 0, 0),
  [148] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_box_quoted_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_box_repeat1, 2, 0, 0),
  [159] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_box_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_box_tag, 1, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markl_id, 4, 0, 15),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markl_id, 3, 0, 12),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_box, 3, 0, 6),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_box, 4, 0, 6),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_box_blob, 2, 0, 0),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_box_type, 2, 0, 1),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_box_computed_tag, 2, 0, 1),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_box, 5, 0, 6),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_box_field, 3, 0, 13),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_box_quoted, 3, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_box_quoted, 2, 0, 0),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_text, 1, 0, 0),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_description, 1, 0, 0),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_description_text, 1, 0, 0),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading_type, 2, 0, 1),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [280] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading_value_text, 1, 0, 0),
  [282] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading_value, 2, 0, 2),
  [284] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading_dimension, 2, 0, 3),
  [286] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_reference_id, 1, 0, 0),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [290] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [294] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_type_name, 1, 0, 0),
  [296] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_type, 2, 0, 1),
  [298] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_blob, 2, 0, 0),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_cutting_garden_organize(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "cutting_garden_organize",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
