/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 140
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 86
#define ALIAS_COUNT 2
#define TOKEN_COUNT 35
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 15
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 24
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  sym_heading_marker = 2,
  sym__heading_space = 3,
  anon_sym_BANG = 4,
  sym_heading_type_name = 5,
  anon_sym_EQ = 6,
  aux_sym_heading_value_text_token1 = 7,
  aux_sym_tag_name_token1 = 8,
  anon_sym_LPAREN = 9,
  anon_sym_RPAREN = 10,
  sym_qualifier_name = 11,
  anon_sym_DASH = 12,
  anon_sym_SPACE = 13,
  anon_sym__group_DASHby = 14,
  anon_sym_PERCENT = 15,
  aux_sym_description_continuation_token1 = 16,
  anon_sym_DASH_DASH_DASH = 17,
  anon_sym_POUND = 18,
  sym_field_key = 19,
  anon_sym_AT = 20,
  sym_field_bare = 21,
  anon_sym_LT = 22,
  sym_type_name = 23,
  sym_file_path = 24,
  anon_sym_LBRACK = 25,
  anon_sym_RBRACK = 26,
  sym__box_space = 27,
  sym_box_object_id = 28,
  anon_sym_DQUOTE = 29,
  aux_sym_box_quoted_token1 = 30,
  sym_box_escape = 31,
  sym_markl_purpose = 32,
  sym_markl_format = 33,
  sym_markl_data = 34,
  sym_source_file = 35,
  sym__body_line = 36,
  sym_blank_line = 37,
  sym_heading = 38,
  sym_heading_reset = 39,
  sym__heading_term = 40,
  sym_heading_type = 41,
  sym_heading_dimension = 42,
  sym_heading_value = 43,
  sym_heading_value_text = 44,
  sym_heading_tag = 45,
  sym_tag_name = 46,
  sym_dim_name = 47,
  sym_qualifier = 48,
  sym_group_by_line = 49,
  sym__group_by_spec = 50,
  sym_object_line = 51,
  sym_description = 52,
  sym_description_continuation = 53,
  sym_metadata = 54,
  sym__metadata_line = 55,
  sym_description_line = 56,
  sym_description_text = 57,
  sym_field_line = 58,
  sym__field_value = 59,
  sym_field_blob = 60,
  sym_field_type = 61,
  sym_field_type_name = 62,
  sym_ref_line = 63,
  sym_reference_id = 64,
  sym_type_line = 65,
  sym_blob_line = 66,
  sym_comment_line = 67,
  sym_comment_text = 68,
  sym_box = 69,
  sym__box_item = 70,
  sym_box_blob = 71,
  sym_box_type = 72,
  sym_box_computed_tag = 73,
  sym_box_field = 74,
  sym__box_value = 75,
  sym_box_bare_value = 76,
  sym_box_tag = 77,
  sym_box_ident = 78,
  sym_box_quoted = 79,
  sym_markl_id = 80,
  aux_sym_source_file_repeat1 = 81,
  aux_sym_object_line_repeat1 = 82,
  aux_sym_metadata_repeat1 = 83,
  aux_sym_box_repeat1 = 84,
  aux_sym_box_quoted_repeat1 = 85,
  alias_sym_box_tag_quoted = 86,
  alias_sym_heading_tag_quoted = 87,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [sym_heading_marker] = "heading_marker",
  [sym__heading_space] = "_heading_space",
  [anon_sym_BANG] = "!",
  [sym_heading_type_name] = "heading_type_name",
  [anon_sym_EQ] = "=",
  [aux_sym_heading_value_text_token1] = "heading_value_text_token1",
  [aux_sym_tag_name_token1] = "tag_name_token1",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_qualifier_name] = "qualifier_name",
  [anon_sym_DASH] = "-",
  [anon_sym_SPACE] = " ",
  [anon_sym__group_DASHby] = "field_key",
  [anon_sym_PERCENT] = "%",
  [aux_sym_description_continuation_token1] = "description_continuation_token1",
  [anon_sym_DASH_DASH_DASH] = "---",
  [anon_sym_POUND] = "#",
  [sym_field_key] = "field_key",
  [anon_sym_AT] = "@",
  [sym_field_bare] = "field_bare",
  [anon_sym_LT] = "<",
  [sym_type_name] = "type_name",
  [sym_file_path] = "file_path",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym__box_space] = "_box_space",
  [sym_box_object_id] = "box_object_id",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_box_quoted_token1] = "box_quoted_token1",
  [sym_box_escape] = "box_escape",
  [sym_markl_purpose] = "markl_purpose",
  [sym_markl_format] = "markl_format",
  [sym_markl_data] = "markl_data",
  [sym_source_file] = "source_file",
  [sym__body_line] = "_body_line",
  [sym_blank_line] = "blank_line",
  [sym_heading] = "heading",
  [sym_heading_reset] = "heading_reset",
  [sym__heading_term] = "_heading_term",
  [sym_heading_type] = "heading_type",
  [sym_heading_dimension] = "heading_dimension",
  [sym_heading_value] = "heading_value",
  [sym_heading_value_text] = "heading_value_text",
  [sym_heading_tag] = "heading_tag",
  [sym_tag_name] = "tag_name",
  [sym_dim_name] = "dim_name",
  [sym_qualifier] = "qualifier",
  [sym_group_by_line] = "group_by_line",
  [sym__group_by_spec] = "_group_by_spec",
  [sym_object_line] = "object_line",
  [sym_description] = "description",
  [sym_description_continuation] = "description_continuation",
  [sym_metadata] = "metadata",
  [sym__metadata_line] = "_metadata_line",
  [sym_description_line] = "description_line",
  [sym_description_text] = "description_text",
  [sym_field_line] = "field_line",
  [sym__field_value] = "_field_value",
  [sym_field_blob] = "field_blob",
  [sym_field_type] = "field_type",
  [sym_field_type_name] = "field_type_name",
  [sym_ref_line] = "ref_line",
  [sym_reference_id] = "reference_id",
  [sym_type_line] = "type_line",
  [sym_blob_line] = "blob_line",
  [sym_comment_line] = "comment_line",
  [sym_comment_text] = "comment_text",
  [sym_box] = "box",
  [sym__box_item] = "_box_item",
  [sym_box_blob] = "box_blob",
  [sym_box_type] = "box_type",
  [sym_box_computed_tag] = "box_computed_tag",
  [sym_box_field] = "box_field",
  [sym__box_value] = "_box_value",
  [sym_box_bare_value] = "box_bare_value",
  [sym_box_tag] = "box_tag",
  [sym_box_ident] = "box_ident",
  [sym_box_quoted] = "box_quoted",
  [sym_markl_id] = "markl_id",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_object_line_repeat1] = "object_line_repeat1",
  [aux_sym_metadata_repeat1] = "metadata_repeat1",
  [aux_sym_box_repeat1] = "box_repeat1",
  [aux_sym_box_quoted_repeat1] = "box_quoted_repeat1",
  [alias_sym_box_tag_quoted] = "box_tag_quoted",
  [alias_sym_heading_tag_quoted] = "heading_tag_quoted",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [sym_heading_marker] = sym_heading_marker,
  [sym__heading_space] = sym__heading_space,
  [anon_sym_BANG] = anon_sym_BANG,
  [sym_heading_type_name] = sym_heading_type_name,
  [anon_sym_EQ] = anon_sym_EQ,
  [aux_sym_heading_value_text_token1] = aux_sym_heading_value_text_token1,
  [aux_sym_tag_name_token1] = aux_sym_tag_name_token1,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_qualifier_name] = sym_qualifier_name,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [anon_sym__group_DASHby] = sym_field_key,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [aux_sym_description_continuation_token1] = aux_sym_description_continuation_token1,
  [anon_sym_DASH_DASH_DASH] = anon_sym_DASH_DASH_DASH,
  [anon_sym_POUND] = anon_sym_POUND,
  [sym_field_key] = sym_field_key,
  [anon_sym_AT] = anon_sym_AT,
  [sym_field_bare] = sym_field_bare,
  [anon_sym_LT] = anon_sym_LT,
  [sym_type_name] = sym_type_name,
  [sym_file_path] = sym_file_path,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym__box_space] = sym__box_space,
  [sym_box_object_id] = sym_box_object_id,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_box_quoted_token1] = aux_sym_box_quoted_token1,
  [sym_box_escape] = sym_box_escape,
  [sym_markl_purpose] = sym_markl_purpose,
  [sym_markl_format] = sym_markl_format,
  [sym_markl_data] = sym_markl_data,
  [sym_source_file] = sym_source_file,
  [sym__body_line] = sym__body_line,
  [sym_blank_line] = sym_blank_line,
  [sym_heading] = sym_heading,
  [sym_heading_reset] = sym_heading_reset,
  [sym__heading_term] = sym__heading_term,
  [sym_heading_type] = sym_heading_type,
  [sym_heading_dimension] = sym_heading_dimension,
  [sym_heading_value] = sym_heading_value,
  [sym_heading_value_text] = sym_heading_value_text,
  [sym_heading_tag] = sym_heading_tag,
  [sym_tag_name] = sym_tag_name,
  [sym_dim_name] = sym_dim_name,
  [sym_qualifier] = sym_qualifier,
  [sym_group_by_line] = sym_group_by_line,
  [sym__group_by_spec] = sym__group_by_spec,
  [sym_object_line] = sym_object_line,
  [sym_description] = sym_description,
  [sym_description_continuation] = sym_description_continuation,
  [sym_metadata] = sym_metadata,
  [sym__metadata_line] = sym__metadata_line,
  [sym_description_line] = sym_description_line,
  [sym_description_text] = sym_description_text,
  [sym_field_line] = sym_field_line,
  [sym__field_value] = sym__field_value,
  [sym_field_blob] = sym_field_blob,
  [sym_field_type] = sym_field_type,
  [sym_field_type_name] = sym_field_type_name,
  [sym_ref_line] = sym_ref_line,
  [sym_reference_id] = sym_reference_id,
  [sym_type_line] = sym_type_line,
  [sym_blob_line] = sym_blob_line,
  [sym_comment_line] = sym_comment_line,
  [sym_comment_text] = sym_comment_text,
  [sym_box] = sym_box,
  [sym__box_item] = sym__box_item,
  [sym_box_blob] = sym_box_blob,
  [sym_box_type] = sym_box_type,
  [sym_box_computed_tag] = sym_box_computed_tag,
  [sym_box_field] = sym_box_field,
  [sym__box_value] = sym__box_value,
  [sym_box_bare_value] = sym_box_bare_value,
  [sym_box_tag] = sym_box_tag,
  [sym_box_ident] = sym_box_ident,
  [sym_box_quoted] = sym_box_quoted,
  [sym_markl_id] = sym_markl_id,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_object_line_repeat1] = aux_sym_object_line_repeat1,
  [aux_sym_metadata_repeat1] = aux_sym_metadata_repeat1,
  [aux_sym_box_repeat1] = aux_sym_box_repeat1,
  [aux_sym_box_quoted_repeat1] = aux_sym_box_quoted_repeat1,
  [alias_sym_box_tag_quoted] = alias_sym_box_tag_quoted,
  [alias_sym_heading_tag_quoted] = alias_sym_heading_tag_quoted,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_heading_marker] = {
    .visible = true,
    .named = true,
  },
  [sym__heading_space] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [sym_heading_type_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_heading_value_text_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tag_name_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_qualifier_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__group_DASHby] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_description_continuation_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DASH_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [sym_field_key] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [sym_field_bare] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [sym_type_name] = {
    .visible = true,
    .named = true,
  },
  [sym_file_path] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym__box_space] = {
    .visible = false,
    .named = true,
  },
  [sym_box_object_id] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_box_quoted_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_box_escape] = {
    .visible = true,
    .named = true,
  },
  [sym_markl_purpose] = {
    .visible = true,
    .named = true,
  },
  [sym_markl_format] = {
    .visible = true,
    .named = true,
  },
  [sym_markl_data] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__body_line] = {
    .visible = false,
    .named = true,
  },
  [sym_blank_line] = {
    .visible = true,
    .named = true,
  },
  [sym_heading] = {
    .visible = true,
    .named = true,
  },
  [sym_heading_reset] = {
    .visible = true,
    .named = true,
  },
  [sym__heading_term] = {
    .visible = false,
    .named = true,
  },
  [sym_heading_type] = {
    .visible = true,
    .named = true,
  },
  [sym_heading_dimension] = {
    .visible = true,
    .named = true,
  },
  [sym_heading_value] = {
    .visible = true,
    .named = true,
  },
  [sym_heading_value_text] = {
    .visible = true,
    .named = true,
  },
  [sym_heading_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_dim_name] = {
    .visible = true,
    .named = true,
  },
  [sym_qualifier] = {
    .visible = true,
    .named = true,
  },
  [sym_group_by_line] = {
    .visible = true,
    .named = true,
  },
  [sym__group_by_spec] = {
    .visible = false,
    .named = true,
  },
  [sym_object_line] = {
    .visible = true,
    .named = true,
  },
  [sym_description] = {
    .visible = true,
    .named = true,
  },
  [sym_description_continuation] = {
    .visible = true,
    .named = true,
  },
  [sym_metadata] = {
    .visible = true,
    .named = true,
  },
  [sym__metadata_line] = {
    .visible = false,
    .named = true,
  },
  [sym_description_line] = {
    .visible = true,
    .named = true,
  },
  [sym_description_text] = {
    .visible = true,
    .named = true,
  },
  [sym_field_line] = {
    .visible = true,
    .named = true,
  },
  [sym__field_value] = {
    .visible = false,
    .named = true,
  },
  [sym_field_blob] = {
    .visible = true,
    .named = true,
  },
  [sym_field_type] = {
    .visible = true,
    .named = true,
  },
  [sym_field_type_name] = {
    .visible = true,
    .named = true,
  },
  [sym_ref_line] = {
    .visible = true,
    .named = true,
  },
  [sym_reference_id] = {
    .visible = true,
    .named = true,
  },
  [sym_type_line] = {
    .visible = true,
    .named = true,
  },
  [sym_blob_line] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_line] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_text] = {
    .visible = true,
    .named = true,
  },
  [sym_box] = {
    .visible = true,
    .named = true,
  },
  [sym__box_item] = {
    .visible = false,
    .named = true,
  },
  [sym_box_blob] = {
    .visible = true,
    .named = true,
  },
  [sym_box_type] = {
    .visible = true,
    .named = true,
  },
  [sym_box_computed_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_box_field] = {
    .visible = true,
    .named = true,
  },
  [sym__box_value] = {
    .visible = false,
    .named = true,
  },
  [sym_box_bare_value] = {
    .visible = true,
    .named = true,
  },
  [sym_box_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_box_ident] = {
    .visible = true,
    .named = true,
  },
  [sym_box_quoted] = {
    .visible = true,
    .named = true,
  },
  [sym_markl_id] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_object_line_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_metadata_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_box_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_box_quoted_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_box_tag_quoted] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_heading_tag_quoted] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_continuation = 1,
  field_data = 2,
  field_description = 3,
  field_format = 4,
  field_id = 5,
  field_key = 6,
  field_lock = 7,
  field_marker = 8,
  field_name = 9,
  field_prefix = 10,
  field_qualifier = 11,
  field_ref = 12,
  field_text = 13,
  field_type = 14,
  field_value = 15,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_continuation] = "continuation",
  [field_data] = "data",
  [field_description] = "description",
  [field_format] = "format",
  [field_id] = "id",
  [field_key] = "key",
  [field_lock] = "lock",
  [field_marker] = "marker",
  [field_name] = "name",
  [field_prefix] = "prefix",
  [field_qualifier] = "qualifier",
  [field_ref] = "ref",
  [field_text] = "text",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 1, .length = 1},
  [4] = {.index = 2, .length = 1},
  [5] = {.index = 3, .length = 1},
  [6] = {.index = 4, .length = 1},
  [7] = {.index = 5, .length = 2},
  [8] = {.index = 7, .length = 1},
  [9] = {.index = 8, .length = 1},
  [10] = {.index = 9, .length = 2},
  [11] = {.index = 11, .length = 1},
  [12] = {.index = 1, .length = 1},
  [13] = {.index = 12, .length = 2},
  [14] = {.index = 14, .length = 2},
  [15] = {.index = 16, .length = 1},
  [16] = {.index = 17, .length = 1},
  [17] = {.index = 18, .length = 1},
  [18] = {.index = 19, .length = 3},
  [19] = {.index = 22, .length = 2},
  [20] = {.index = 24, .length = 2},
  [21] = {.index = 26, .length = 2},
  [22] = {.index = 28, .length = 2},
  [23] = {.index = 30, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_marker, 0},
  [1] =
    {field_name, 0},
  [2] =
    {field_name, 1},
  [3] =
    {field_value, 1},
  [4] =
    {field_prefix, 0},
  [5] =
    {field_name, 0},
    {field_qualifier, 2},
  [7] =
    {field_id, 1},
  [8] =
    {field_continuation, 0},
  [9] =
    {field_continuation, 4, .inherited = true},
    {field_prefix, 0},
  [11] =
    {field_text, 1},
  [12] =
    {field_continuation, 0, .inherited = true},
    {field_continuation, 1, .inherited = true},
  [14] =
    {field_description, 4},
    {field_prefix, 0},
  [16] =
    {field_type, 2},
  [17] =
    {field_text, 2},
  [18] =
    {field_ref, 2},
  [19] =
    {field_continuation, 6, .inherited = true},
    {field_description, 4},
    {field_prefix, 0},
  [22] =
    {field_data, 2},
    {field_format, 0},
  [24] =
    {field_key, 0},
    {field_value, 2},
  [26] =
    {field_lock, 4},
    {field_type, 2},
  [28] =
    {field_data, 3},
    {field_format, 1},
  [30] =
    {field_key, 2},
    {field_value, 6},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [3] = {
    [0] = alias_sym_heading_tag_quoted,
  },
  [12] = {
    [0] = alias_sym_box_tag_quoted,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  sym_box_quoted, 3,
    sym_box_quoted,
    alias_sym_box_tag_quoted,
    alias_sym_heading_tag_quoted,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 39,
  [43] = 41,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 76,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 75,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 54,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 78,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 97,
  [135] = 110,
  [136] = 126,
  [137] = 96,
  [138] = 123,
  [139] = 139,
};

static const TSCharacterRange aux_sym_tag_name_token1_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'&', '&'}, {'+', '+'}, {'-', ';'}, {'?', '?'}, {'A', 'Z'}, {'\\', '\\'},
  {'_', '}'}, {0x7f, 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(23);
      ADVANCE_MAP(
        '\n', 24,
        ' ', 36,
        '!', 27,
        '"', 65,
        '#', 42,
        '%', 38,
        '(', 32,
        ')', 33,
        '-', 35,
        '<', 54,
        '=', 29,
        '@', 52,
        '[', 57,
        '\\', 20,
        ']', 58,
        '_', 69,
      );
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '\n', 24,
        '!', 27,
        '"', 65,
        '%', 38,
        '(', 32,
        '=', 29,
        '@', 52,
        ']', 58,
        '\t', 26,
        ' ', 26,
      );
      if ((!eof && set_contains(aux_sym_tag_name_token1_character_set_1, 10, lookahead))) ADVANCE(31);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(24);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '\n', 60,
        '!', 27,
        '#', 41,
        '%', 38,
        '-', 35,
        '<', 54,
        '=', 29,
        '@', 52,
        ']', 58,
        '\t', 59,
        ' ', 59,
      );
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 4:
      if (lookahead == '!') ADVANCE(27);
      if (lookahead == '@') ADVANCE(52);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(53);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(65);
      if (lookahead == '\\') ADVANCE(20);
      if (lookahead != 0) ADVANCE(66);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(40);
      END_STATE();
    case 7:
      if (lookahead == '.') ADVANCE(9);
      if (lookahead == '@') ADVANCE(68);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(7);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(10);
      END_STATE();
    case 8:
      if (lookahead == '.') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(10);
      END_STATE();
    case 9:
      if (lookahead == '.') ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(56);
      END_STATE();
    case 10:
      if (lookahead == '.') ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(10);
      END_STATE();
    case 11:
      if (lookahead == '@') ADVANCE(68);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 12:
      if (lookahead == '\\') ADVANCE(21);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(12);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '#' &&
          lookahead != '%' &&
          lookahead != '-') ADVANCE(39);
      END_STATE();
    case 13:
      if (lookahead == '_') ADVANCE(45);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '=') ADVANCE(51);
      END_STATE();
    case 14:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 15:
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 16:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 17:
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(34);
      END_STATE();
    case 18:
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(28);
      END_STATE();
    case 19:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(55);
      END_STATE();
    case 20:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(67);
      END_STATE();
    case 21:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(39);
      END_STATE();
    case 22:
      if (eof) ADVANCE(23);
      if (lookahead == '\n') ADVANCE(24);
      if (lookahead == '#') ADVANCE(25);
      if (lookahead == '%') ADVANCE(38);
      if (lookahead == '-') ADVANCE(35);
      if (lookahead == '\\') ADVANCE(21);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(12);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(39);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_heading_marker);
      if (lookahead == '#') ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym__heading_space);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_heading_type_name);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_heading_value_text_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_tag_name_token1);
      if ((!eof && set_contains(aux_sym_tag_name_token1_character_set_1, 10, lookahead))) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_qualifier_name);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '-') ADVANCE(6);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_SPACE);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym__group_DASHby);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '=') ADVANCE(51);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_description_continuation_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_DASH_DASH_DASH);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead == '#') ADVANCE(25);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_field_key);
      if (lookahead == '-') ADVANCE(44);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '=') ADVANCE(51);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_field_key);
      if (lookahead == 'b') ADVANCE(50);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '=') ADVANCE(51);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_field_key);
      if (lookahead == 'g') ADVANCE(48);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '=') ADVANCE(51);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_field_key);
      if (lookahead == 'o') ADVANCE(49);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '=') ADVANCE(51);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_field_key);
      if (lookahead == 'p') ADVANCE(43);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '=') ADVANCE(51);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_field_key);
      if (lookahead == 'r') ADVANCE(46);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '=') ADVANCE(51);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_field_key);
      if (lookahead == 'u') ADVANCE(47);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '=') ADVANCE(51);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_field_key);
      if (lookahead == 'y') ADVANCE(37);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '=') ADVANCE(51);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_field_key);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '=') ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_field_bare);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(53);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_type_name);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_file_path);
      if (lookahead == '.') ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '@') ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym__box_space);
      if (lookahead == '\n') ADVANCE(60);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym__box_space);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_box_object_id);
      if (lookahead == '-') ADVANCE(63);
      if (lookahead == '@') ADVANCE(68);
      if (lookahead == '_') ADVANCE(62);
      if (lookahead == '.' ||
          lookahead == '/' ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_box_object_id);
      if (lookahead == '-') ADVANCE(63);
      if (lookahead == '@') ADVANCE(68);
      if (lookahead == '.' ||
          lookahead == '/' ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_box_object_id);
      if (lookahead == '@') ADVANCE(68);
      if (lookahead == '.' ||
          lookahead == '/' ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(64);
      if (('-' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_box_object_id);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(aux_sym_box_quoted_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_box_escape);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_markl_purpose);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_markl_format);
      if (lookahead == '-') ADVANCE(11);
      if (lookahead == '@') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_markl_format);
      if (lookahead == '-') ADVANCE(7);
      if (lookahead == '.') ADVANCE(9);
      if (lookahead == '@') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(10);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_markl_format);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_markl_data);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 22},
  [2] = {.lex_state = 3},
  [3] = {.lex_state = 3},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 22},
  [10] = {.lex_state = 22},
  [11] = {.lex_state = 22},
  [12] = {.lex_state = 22},
  [13] = {.lex_state = 22},
  [14] = {.lex_state = 22},
  [15] = {.lex_state = 22},
  [16] = {.lex_state = 22},
  [17] = {.lex_state = 22},
  [18] = {.lex_state = 3},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 3},
  [21] = {.lex_state = 3},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 3},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 3},
  [26] = {.lex_state = 3},
  [27] = {.lex_state = 22},
  [28] = {.lex_state = 4},
  [29] = {.lex_state = 22},
  [30] = {.lex_state = 22},
  [31] = {.lex_state = 22},
  [32] = {.lex_state = 22},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 22},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 22},
  [37] = {.lex_state = 22},
  [38] = {.lex_state = 8},
  [39] = {.lex_state = 5},
  [40] = {.lex_state = 5},
  [41] = {.lex_state = 5},
  [42] = {.lex_state = 5},
  [43] = {.lex_state = 5},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 3},
  [46] = {.lex_state = 3},
  [47] = {.lex_state = 3},
  [48] = {.lex_state = 2},
  [49] = {.lex_state = 3},
  [50] = {.lex_state = 3},
  [51] = {.lex_state = 3},
  [52] = {.lex_state = 3},
  [53] = {.lex_state = 3},
  [54] = {.lex_state = 3},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 2},
  [58] = {.lex_state = 3},
  [59] = {.lex_state = 3},
  [60] = {.lex_state = 3},
  [61] = {.lex_state = 1},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 3},
  [66] = {.lex_state = 3},
  [67] = {.lex_state = 3},
  [68] = {.lex_state = 2},
  [69] = {.lex_state = 3},
  [70] = {.lex_state = 2},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 2},
  [74] = {.lex_state = 13},
  [75] = {.lex_state = 3},
  [76] = {.lex_state = 3},
  [77] = {.lex_state = 1},
  [78] = {.lex_state = 3},
  [79] = {.lex_state = 2},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 17},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 14},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 14},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 15},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 16},
  [132] = {.lex_state = 18},
  [133] = {.lex_state = 19},
  [134] = {.lex_state = 14},
  [135] = {.lex_state = 14},
  [136] = {.lex_state = 0},
  [137] = {.lex_state = 0},
  [138] = {.lex_state = 15},
  [139] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [sym_heading_marker] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_SPACE] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_DASH_DASH_DASH] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_box_object_id] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_box_escape] = ACTIONS(1),
    [sym_markl_purpose] = ACTIONS(1),
    [sym_markl_format] = ACTIONS(1),
    [sym_markl_data] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(91),
    [sym__body_line] = STATE(12),
    [sym_blank_line] = STATE(12),
    [sym_heading] = STATE(12),
    [sym_heading_reset] = STATE(12),
    [sym_object_line] = STATE(12),
    [sym_metadata] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(12),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(5),
    [sym_heading_marker] = ACTIONS(7),
    [anon_sym_DASH] = ACTIONS(9),
    [anon_sym_PERCENT] = ACTIONS(11),
    [anon_sym_DASH_DASH_DASH] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(15), 1,
      anon_sym_BANG,
    ACTIONS(17), 1,
      anon_sym_DASH,
    ACTIONS(19), 1,
      anon_sym_PERCENT,
    ACTIONS(21), 1,
      anon_sym_DASH_DASH_DASH,
    ACTIONS(23), 1,
      anon_sym_POUND,
    ACTIONS(25), 1,
      anon_sym_AT,
    ACTIONS(27), 1,
      anon_sym_LT,
    STATE(4), 9,
      sym_group_by_line,
      sym__metadata_line,
      sym_description_line,
      sym_field_line,
      sym_ref_line,
      sym_type_line,
      sym_blob_line,
      sym_comment_line,
      aux_sym_metadata_repeat1,
  [33] = 8,
    ACTIONS(15), 1,
      anon_sym_BANG,
    ACTIONS(17), 1,
      anon_sym_DASH,
    ACTIONS(19), 1,
      anon_sym_PERCENT,
    ACTIONS(23), 1,
      anon_sym_POUND,
    ACTIONS(25), 1,
      anon_sym_AT,
    ACTIONS(27), 1,
      anon_sym_LT,
    ACTIONS(29), 1,
      anon_sym_DASH_DASH_DASH,
    STATE(2), 9,
      sym_group_by_line,
      sym__metadata_line,
      sym_description_line,
      sym_field_line,
      sym_ref_line,
      sym_type_line,
      sym_blob_line,
      sym_comment_line,
      aux_sym_metadata_repeat1,
  [66] = 8,
    ACTIONS(31), 1,
      anon_sym_BANG,
    ACTIONS(34), 1,
      anon_sym_DASH,
    ACTIONS(37), 1,
      anon_sym_PERCENT,
    ACTIONS(40), 1,
      anon_sym_DASH_DASH_DASH,
    ACTIONS(42), 1,
      anon_sym_POUND,
    ACTIONS(45), 1,
      anon_sym_AT,
    ACTIONS(48), 1,
      anon_sym_LT,
    STATE(4), 9,
      sym_group_by_line,
      sym__metadata_line,
      sym_description_line,
      sym_field_line,
      sym_ref_line,
      sym_type_line,
      sym_blob_line,
      sym_comment_line,
      aux_sym_metadata_repeat1,
  [99] = 9,
    ACTIONS(51), 1,
      anon_sym_BANG,
    ACTIONS(53), 1,
      aux_sym_tag_name_token1,
    ACTIONS(55), 1,
      anon_sym_PERCENT,
    ACTIONS(57), 1,
      anon_sym_AT,
    ACTIONS(59), 1,
      anon_sym_RBRACK,
    ACTIONS(61), 1,
      anon_sym_DQUOTE,
    STATE(53), 1,
      sym_box_ident,
    STATE(69), 1,
      sym_box_quoted,
    STATE(67), 6,
      sym__box_item,
      sym_box_blob,
      sym_box_type,
      sym_box_computed_tag,
      sym_box_field,
      sym_box_tag,
  [132] = 9,
    ACTIONS(51), 1,
      anon_sym_BANG,
    ACTIONS(53), 1,
      aux_sym_tag_name_token1,
    ACTIONS(55), 1,
      anon_sym_PERCENT,
    ACTIONS(57), 1,
      anon_sym_AT,
    ACTIONS(61), 1,
      anon_sym_DQUOTE,
    ACTIONS(63), 1,
      anon_sym_RBRACK,
    STATE(53), 1,
      sym_box_ident,
    STATE(69), 1,
      sym_box_quoted,
    STATE(67), 6,
      sym__box_item,
      sym_box_blob,
      sym_box_type,
      sym_box_computed_tag,
      sym_box_field,
      sym_box_tag,
  [165] = 9,
    ACTIONS(65), 1,
      anon_sym_LF,
    ACTIONS(67), 1,
      anon_sym_BANG,
    ACTIONS(69), 1,
      anon_sym_EQ,
    ACTIONS(71), 1,
      aux_sym_tag_name_token1,
    ACTIONS(73), 1,
      anon_sym_DQUOTE,
    STATE(112), 1,
      sym_tag_name,
    STATE(115), 1,
      sym_dim_name,
    STATE(130), 1,
      sym_box_quoted,
    STATE(104), 5,
      sym__heading_term,
      sym_heading_type,
      sym_heading_dimension,
      sym_heading_value,
      sym_heading_tag,
  [197] = 8,
    ACTIONS(51), 1,
      anon_sym_BANG,
    ACTIONS(53), 1,
      aux_sym_tag_name_token1,
    ACTIONS(55), 1,
      anon_sym_PERCENT,
    ACTIONS(57), 1,
      anon_sym_AT,
    ACTIONS(61), 1,
      anon_sym_DQUOTE,
    STATE(53), 1,
      sym_box_ident,
    STATE(69), 1,
      sym_box_quoted,
    STATE(67), 6,
      sym__box_item,
      sym_box_blob,
      sym_box_type,
      sym_box_computed_tag,
      sym_box_field,
      sym_box_tag,
  [227] = 5,
    ACTIONS(5), 1,
      anon_sym_LF,
    ACTIONS(7), 1,
      sym_heading_marker,
    ACTIONS(75), 1,
      ts_builtin_sym_end,
    ACTIONS(11), 2,
      anon_sym_DASH,
      anon_sym_PERCENT,
    STATE(10), 6,
      sym__body_line,
      sym_blank_line,
      sym_heading,
      sym_heading_reset,
      sym_object_line,
      aux_sym_source_file_repeat1,
  [249] = 5,
    ACTIONS(5), 1,
      anon_sym_LF,
    ACTIONS(7), 1,
      sym_heading_marker,
    ACTIONS(77), 1,
      ts_builtin_sym_end,
    ACTIONS(11), 2,
      anon_sym_DASH,
      anon_sym_PERCENT,
    STATE(11), 6,
      sym__body_line,
      sym_blank_line,
      sym_heading,
      sym_heading_reset,
      sym_object_line,
      aux_sym_source_file_repeat1,
  [271] = 5,
    ACTIONS(79), 1,
      ts_builtin_sym_end,
    ACTIONS(81), 1,
      anon_sym_LF,
    ACTIONS(84), 1,
      sym_heading_marker,
    ACTIONS(87), 2,
      anon_sym_DASH,
      anon_sym_PERCENT,
    STATE(11), 6,
      sym__body_line,
      sym_blank_line,
      sym_heading,
      sym_heading_reset,
      sym_object_line,
      aux_sym_source_file_repeat1,
  [293] = 5,
    ACTIONS(5), 1,
      anon_sym_LF,
    ACTIONS(7), 1,
      sym_heading_marker,
    ACTIONS(75), 1,
      ts_builtin_sym_end,
    ACTIONS(11), 2,
      anon_sym_DASH,
      anon_sym_PERCENT,
    STATE(11), 6,
      sym__body_line,
      sym_blank_line,
      sym_heading,
      sym_heading_reset,
      sym_object_line,
      aux_sym_source_file_repeat1,
  [315] = 4,
    ACTIONS(92), 1,
      aux_sym_description_continuation_token1,
    STATE(14), 1,
      aux_sym_object_line_repeat1,
    STATE(27), 1,
      sym_description_continuation,
    ACTIONS(90), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_heading_marker,
      anon_sym_DASH,
      anon_sym_PERCENT,
  [332] = 4,
    ACTIONS(92), 1,
      aux_sym_description_continuation_token1,
    STATE(15), 1,
      aux_sym_object_line_repeat1,
    STATE(27), 1,
      sym_description_continuation,
    ACTIONS(94), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_heading_marker,
      anon_sym_DASH,
      anon_sym_PERCENT,
  [349] = 4,
    ACTIONS(98), 1,
      aux_sym_description_continuation_token1,
    STATE(15), 1,
      aux_sym_object_line_repeat1,
    STATE(27), 1,
      sym_description_continuation,
    ACTIONS(96), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_heading_marker,
      anon_sym_DASH,
      anon_sym_PERCENT,
  [366] = 4,
    ACTIONS(92), 1,
      aux_sym_description_continuation_token1,
    STATE(17), 1,
      aux_sym_object_line_repeat1,
    STATE(27), 1,
      sym_description_continuation,
    ACTIONS(101), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_heading_marker,
      anon_sym_DASH,
      anon_sym_PERCENT,
  [383] = 4,
    ACTIONS(92), 1,
      aux_sym_description_continuation_token1,
    STATE(15), 1,
      aux_sym_object_line_repeat1,
    STATE(27), 1,
      sym_description_continuation,
    ACTIONS(103), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_heading_marker,
      anon_sym_DASH,
      anon_sym_PERCENT,
  [400] = 2,
    ACTIONS(107), 1,
      anon_sym_DASH,
    ACTIONS(105), 6,
      anon_sym_BANG,
      anon_sym_PERCENT,
      anon_sym_DASH_DASH_DASH,
      anon_sym_POUND,
      anon_sym_AT,
      anon_sym_LT,
  [412] = 2,
    ACTIONS(111), 1,
      anon_sym_DASH,
    ACTIONS(109), 6,
      anon_sym_BANG,
      anon_sym_PERCENT,
      anon_sym_DASH_DASH_DASH,
      anon_sym_POUND,
      anon_sym_AT,
      anon_sym_LT,
  [424] = 2,
    ACTIONS(115), 1,
      anon_sym_DASH,
    ACTIONS(113), 6,
      anon_sym_BANG,
      anon_sym_PERCENT,
      anon_sym_DASH_DASH_DASH,
      anon_sym_POUND,
      anon_sym_AT,
      anon_sym_LT,
  [436] = 2,
    ACTIONS(119), 1,
      anon_sym_DASH,
    ACTIONS(117), 6,
      anon_sym_BANG,
      anon_sym_PERCENT,
      anon_sym_DASH_DASH_DASH,
      anon_sym_POUND,
      anon_sym_AT,
      anon_sym_LT,
  [448] = 2,
    ACTIONS(123), 1,
      anon_sym_DASH,
    ACTIONS(121), 6,
      anon_sym_BANG,
      anon_sym_PERCENT,
      anon_sym_DASH_DASH_DASH,
      anon_sym_POUND,
      anon_sym_AT,
      anon_sym_LT,
  [460] = 2,
    ACTIONS(127), 1,
      anon_sym_DASH,
    ACTIONS(125), 6,
      anon_sym_BANG,
      anon_sym_PERCENT,
      anon_sym_DASH_DASH_DASH,
      anon_sym_POUND,
      anon_sym_AT,
      anon_sym_LT,
  [472] = 2,
    ACTIONS(131), 1,
      anon_sym_DASH,
    ACTIONS(129), 6,
      anon_sym_BANG,
      anon_sym_PERCENT,
      anon_sym_DASH_DASH_DASH,
      anon_sym_POUND,
      anon_sym_AT,
      anon_sym_LT,
  [484] = 2,
    ACTIONS(135), 1,
      anon_sym_DASH,
    ACTIONS(133), 6,
      anon_sym_BANG,
      anon_sym_PERCENT,
      anon_sym_DASH_DASH_DASH,
      anon_sym_POUND,
      anon_sym_AT,
      anon_sym_LT,
  [496] = 2,
    ACTIONS(139), 1,
      anon_sym_DASH,
    ACTIONS(137), 6,
      anon_sym_BANG,
      anon_sym_PERCENT,
      anon_sym_DASH_DASH_DASH,
      anon_sym_POUND,
      anon_sym_AT,
      anon_sym_LT,
  [508] = 1,
    ACTIONS(141), 6,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_heading_marker,
      anon_sym_DASH,
      anon_sym_PERCENT,
      aux_sym_description_continuation_token1,
  [517] = 4,
    ACTIONS(143), 1,
      anon_sym_BANG,
    ACTIONS(145), 1,
      anon_sym_AT,
    ACTIONS(147), 1,
      sym_field_bare,
    STATE(122), 3,
      sym__field_value,
      sym_field_blob,
      sym_field_type,
  [532] = 1,
    ACTIONS(149), 6,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_heading_marker,
      anon_sym_DASH,
      anon_sym_PERCENT,
      aux_sym_description_continuation_token1,
  [541] = 1,
    ACTIONS(151), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_heading_marker,
      anon_sym_DASH,
      anon_sym_PERCENT,
  [549] = 1,
    ACTIONS(153), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_heading_marker,
      anon_sym_DASH,
      anon_sym_PERCENT,
  [557] = 1,
    ACTIONS(155), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_heading_marker,
      anon_sym_DASH,
      anon_sym_PERCENT,
  [565] = 3,
    ACTIONS(61), 1,
      anon_sym_DQUOTE,
    ACTIONS(157), 1,
      aux_sym_tag_name_token1,
    STATE(66), 3,
      sym__box_value,
      sym_box_bare_value,
      sym_box_quoted,
  [577] = 1,
    ACTIONS(159), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_heading_marker,
      anon_sym_DASH,
      anon_sym_PERCENT,
  [585] = 3,
    ACTIONS(161), 1,
      aux_sym_tag_name_token1,
    ACTIONS(163), 1,
      anon_sym_LPAREN,
    STATE(119), 3,
      sym_tag_name,
      sym_qualifier,
      sym__group_by_spec,
  [597] = 1,
    ACTIONS(165), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_heading_marker,
      anon_sym_DASH,
      anon_sym_PERCENT,
  [605] = 1,
    ACTIONS(167), 5,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_heading_marker,
      anon_sym_DASH,
      anon_sym_PERCENT,
  [613] = 4,
    ACTIONS(169), 1,
      sym_file_path,
    ACTIONS(171), 1,
      sym_markl_purpose,
    ACTIONS(173), 1,
      sym_markl_format,
    STATE(121), 1,
      sym_markl_id,
  [626] = 3,
    ACTIONS(175), 1,
      anon_sym_DQUOTE,
    STATE(41), 1,
      aux_sym_box_quoted_repeat1,
    ACTIONS(177), 2,
      aux_sym_box_quoted_token1,
      sym_box_escape,
  [637] = 3,
    ACTIONS(179), 1,
      anon_sym_DQUOTE,
    STATE(40), 1,
      aux_sym_box_quoted_repeat1,
    ACTIONS(181), 2,
      aux_sym_box_quoted_token1,
      sym_box_escape,
  [648] = 3,
    ACTIONS(184), 1,
      anon_sym_DQUOTE,
    STATE(40), 1,
      aux_sym_box_quoted_repeat1,
    ACTIONS(186), 2,
      aux_sym_box_quoted_token1,
      sym_box_escape,
  [659] = 3,
    ACTIONS(188), 1,
      anon_sym_DQUOTE,
    STATE(43), 1,
      aux_sym_box_quoted_repeat1,
    ACTIONS(190), 2,
      aux_sym_box_quoted_token1,
      sym_box_escape,
  [670] = 3,
    ACTIONS(192), 1,
      anon_sym_DQUOTE,
    STATE(40), 1,
      aux_sym_box_quoted_repeat1,
    ACTIONS(186), 2,
      aux_sym_box_quoted_token1,
      sym_box_escape,
  [681] = 3,
    ACTIONS(163), 1,
      anon_sym_LPAREN,
    ACTIONS(194), 1,
      anon_sym_LF,
    STATE(95), 1,
      sym_qualifier,
  [691] = 3,
    ACTIONS(196), 1,
      anon_sym_RBRACK,
    ACTIONS(198), 1,
      sym__box_space,
    STATE(49), 1,
      aux_sym_box_repeat1,
  [701] = 3,
    ACTIONS(171), 1,
      sym_markl_purpose,
    ACTIONS(173), 1,
      sym_markl_format,
    STATE(107), 1,
      sym_markl_id,
  [711] = 3,
    ACTIONS(200), 1,
      anon_sym_RBRACK,
    ACTIONS(202), 1,
      sym__box_space,
    STATE(47), 1,
      aux_sym_box_repeat1,
  [721] = 3,
    ACTIONS(205), 1,
      anon_sym_LF,
    ACTIONS(207), 1,
      aux_sym_heading_value_text_token1,
    STATE(84), 1,
      sym_comment_text,
  [731] = 3,
    ACTIONS(59), 1,
      anon_sym_RBRACK,
    ACTIONS(209), 1,
      sym__box_space,
    STATE(47), 1,
      aux_sym_box_repeat1,
  [741] = 3,
    ACTIONS(171), 1,
      sym_markl_purpose,
    ACTIONS(173), 1,
      sym_markl_format,
    STATE(81), 1,
      sym_markl_id,
  [751] = 1,
    ACTIONS(211), 3,
      anon_sym_EQ,
      anon_sym_RBRACK,
      sym__box_space,
  [757] = 3,
    ACTIONS(213), 1,
      sym_markl_purpose,
    ACTIONS(215), 1,
      sym_markl_format,
    STATE(60), 1,
      sym_markl_id,
  [767] = 2,
    ACTIONS(217), 1,
      anon_sym_EQ,
    ACTIONS(219), 2,
      anon_sym_RBRACK,
      sym__box_space,
  [775] = 1,
    ACTIONS(221), 2,
      anon_sym_RBRACK,
      sym__box_space,
  [780] = 2,
    ACTIONS(223), 1,
      anon_sym_LF,
    ACTIONS(225), 1,
      anon_sym_SPACE,
  [787] = 2,
    ACTIONS(53), 1,
      aux_sym_tag_name_token1,
    STATE(58), 1,
      sym_box_ident,
  [794] = 2,
    ACTIONS(227), 1,
      aux_sym_heading_value_text_token1,
    STATE(128), 1,
      sym_reference_id,
  [801] = 1,
    ACTIONS(229), 2,
      anon_sym_RBRACK,
      sym__box_space,
  [806] = 1,
    ACTIONS(231), 2,
      anon_sym_RBRACK,
      sym__box_space,
  [811] = 1,
    ACTIONS(233), 2,
      anon_sym_RBRACK,
      sym__box_space,
  [816] = 2,
    ACTIONS(53), 1,
      aux_sym_tag_name_token1,
    STATE(59), 1,
      sym_box_ident,
  [823] = 1,
    ACTIONS(235), 2,
      anon_sym_LF,
      anon_sym_SPACE,
  [828] = 2,
    ACTIONS(237), 1,
      anon_sym_LBRACK,
    STATE(55), 1,
      sym_box,
  [835] = 1,
    ACTIONS(239), 2,
      anon_sym_LF,
      anon_sym_SPACE,
  [840] = 1,
    ACTIONS(241), 2,
      anon_sym_RBRACK,
      sym__box_space,
  [845] = 1,
    ACTIONS(243), 2,
      anon_sym_RBRACK,
      sym__box_space,
  [850] = 1,
    ACTIONS(200), 2,
      anon_sym_RBRACK,
      sym__box_space,
  [855] = 2,
    ACTIONS(245), 1,
      aux_sym_heading_value_text_token1,
    STATE(101), 1,
      sym_heading_value_text,
  [862] = 1,
    ACTIONS(247), 2,
      anon_sym_RBRACK,
      sym__box_space,
  [867] = 2,
    ACTIONS(249), 1,
      aux_sym_heading_value_text_token1,
    STATE(125), 1,
      sym_field_type_name,
  [874] = 2,
    ACTIONS(251), 1,
      anon_sym_LF,
    ACTIONS(253), 1,
      anon_sym_EQ,
  [881] = 1,
    ACTIONS(255), 2,
      anon_sym_LF,
      anon_sym_SPACE,
  [886] = 2,
    ACTIONS(257), 1,
      aux_sym_heading_value_text_token1,
    STATE(106), 1,
      sym_description,
  [893] = 2,
    ACTIONS(259), 1,
      anon_sym__group_DASHby,
    ACTIONS(261), 1,
      sym_field_key,
  [900] = 1,
    ACTIONS(263), 2,
      anon_sym_RBRACK,
      sym__box_space,
  [905] = 1,
    ACTIONS(265), 2,
      anon_sym_RBRACK,
      sym__box_space,
  [910] = 2,
    ACTIONS(267), 1,
      anon_sym_LF,
    ACTIONS(269), 1,
      sym__heading_space,
  [917] = 1,
    ACTIONS(271), 2,
      anon_sym_RBRACK,
      sym__box_space,
  [922] = 2,
    ACTIONS(273), 1,
      aux_sym_heading_value_text_token1,
    STATE(120), 1,
      sym_description_text,
  [929] = 2,
    ACTIONS(275), 1,
      anon_sym_LF,
    ACTIONS(277), 1,
      anon_sym_AT,
  [936] = 1,
    ACTIONS(279), 1,
      anon_sym_LF,
  [940] = 1,
    ACTIONS(281), 1,
      anon_sym_SPACE,
  [944] = 1,
    ACTIONS(283), 1,
      anon_sym_LF,
  [948] = 1,
    ACTIONS(285), 1,
      anon_sym_LF,
  [952] = 1,
    ACTIONS(287), 1,
      anon_sym_SPACE,
  [956] = 1,
    ACTIONS(289), 1,
      anon_sym_LF,
  [960] = 1,
    ACTIONS(291), 1,
      anon_sym_SPACE,
  [964] = 1,
    ACTIONS(293), 1,
      anon_sym_SPACE,
  [968] = 1,
    ACTIONS(295), 1,
      anon_sym_SPACE,
  [972] = 1,
    ACTIONS(265), 1,
      anon_sym_LF,
  [976] = 1,
    ACTIONS(297), 1,
      ts_builtin_sym_end,
  [980] = 1,
    ACTIONS(299), 1,
      anon_sym_EQ,
  [984] = 1,
    ACTIONS(301), 1,
      anon_sym_EQ,
  [988] = 1,
    ACTIONS(303), 1,
      sym_qualifier_name,
  [992] = 1,
    ACTIONS(305), 1,
      anon_sym_LF,
  [996] = 1,
    ACTIONS(307), 1,
      anon_sym_DASH,
  [1000] = 1,
    ACTIONS(309), 1,
      sym_markl_data,
  [1004] = 1,
    ACTIONS(311), 1,
      anon_sym_LF,
  [1008] = 1,
    ACTIONS(313), 1,
      anon_sym_LF,
  [1012] = 1,
    ACTIONS(315), 1,
      anon_sym_LF,
  [1016] = 1,
    ACTIONS(317), 1,
      anon_sym_LF,
  [1020] = 1,
    ACTIONS(319), 1,
      anon_sym_LF,
  [1024] = 1,
    ACTIONS(263), 1,
      anon_sym_LF,
  [1028] = 1,
    ACTIONS(321), 1,
      anon_sym_LF,
  [1032] = 1,
    ACTIONS(323), 1,
      anon_sym_LF,
  [1036] = 1,
    ACTIONS(325), 1,
      anon_sym_LF,
  [1040] = 1,
    ACTIONS(327), 1,
      anon_sym_LF,
  [1044] = 1,
    ACTIONS(329), 1,
      anon_sym_SPACE,
  [1048] = 1,
    ACTIONS(331), 1,
      anon_sym_SPACE,
  [1052] = 1,
    ACTIONS(333), 1,
      sym_markl_data,
  [1056] = 1,
    ACTIONS(221), 1,
      anon_sym_LF,
  [1060] = 1,
    ACTIONS(335), 1,
      anon_sym_LF,
  [1064] = 1,
    ACTIONS(337), 1,
      anon_sym_SPACE,
  [1068] = 1,
    ACTIONS(339), 1,
      anon_sym_SPACE,
  [1072] = 1,
    ACTIONS(341), 1,
      anon_sym_EQ,
  [1076] = 1,
    ACTIONS(343), 1,
      anon_sym_LF,
  [1080] = 1,
    ACTIONS(271), 1,
      anon_sym_LF,
  [1084] = 1,
    ACTIONS(251), 1,
      anon_sym_LF,
  [1088] = 1,
    ACTIONS(345), 1,
      anon_sym_LF,
  [1092] = 1,
    ACTIONS(347), 1,
      anon_sym_LF,
  [1096] = 1,
    ACTIONS(349), 1,
      anon_sym_LF,
  [1100] = 1,
    ACTIONS(351), 1,
      anon_sym_LF,
  [1104] = 1,
    ACTIONS(353), 1,
      sym_markl_format,
  [1108] = 1,
    ACTIONS(355), 1,
      anon_sym_LF,
  [1112] = 1,
    ACTIONS(357), 1,
      anon_sym_LF,
  [1116] = 1,
    ACTIONS(359), 1,
      anon_sym_DASH,
  [1120] = 1,
    ACTIONS(361), 1,
      anon_sym_LF,
  [1124] = 1,
    ACTIONS(363), 1,
      anon_sym_LF,
  [1128] = 1,
    ACTIONS(365), 1,
      anon_sym_RPAREN,
  [1132] = 1,
    ACTIONS(367), 1,
      anon_sym_LF,
  [1136] = 1,
    ACTIONS(369), 1,
      sym_box_object_id,
  [1140] = 1,
    ACTIONS(371), 1,
      sym_heading_type_name,
  [1144] = 1,
    ACTIONS(373), 1,
      sym_type_name,
  [1148] = 1,
    ACTIONS(375), 1,
      sym_markl_data,
  [1152] = 1,
    ACTIONS(377), 1,
      sym_markl_data,
  [1156] = 1,
    ACTIONS(379), 1,
      anon_sym_DASH,
  [1160] = 1,
    ACTIONS(381), 1,
      anon_sym_DASH,
  [1164] = 1,
    ACTIONS(383), 1,
      sym_markl_format,
  [1168] = 1,
    ACTIONS(385), 1,
      anon_sym_SPACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 33,
  [SMALL_STATE(4)] = 66,
  [SMALL_STATE(5)] = 99,
  [SMALL_STATE(6)] = 132,
  [SMALL_STATE(7)] = 165,
  [SMALL_STATE(8)] = 197,
  [SMALL_STATE(9)] = 227,
  [SMALL_STATE(10)] = 249,
  [SMALL_STATE(11)] = 271,
  [SMALL_STATE(12)] = 293,
  [SMALL_STATE(13)] = 315,
  [SMALL_STATE(14)] = 332,
  [SMALL_STATE(15)] = 349,
  [SMALL_STATE(16)] = 366,
  [SMALL_STATE(17)] = 383,
  [SMALL_STATE(18)] = 400,
  [SMALL_STATE(19)] = 412,
  [SMALL_STATE(20)] = 424,
  [SMALL_STATE(21)] = 436,
  [SMALL_STATE(22)] = 448,
  [SMALL_STATE(23)] = 460,
  [SMALL_STATE(24)] = 472,
  [SMALL_STATE(25)] = 484,
  [SMALL_STATE(26)] = 496,
  [SMALL_STATE(27)] = 508,
  [SMALL_STATE(28)] = 517,
  [SMALL_STATE(29)] = 532,
  [SMALL_STATE(30)] = 541,
  [SMALL_STATE(31)] = 549,
  [SMALL_STATE(32)] = 557,
  [SMALL_STATE(33)] = 565,
  [SMALL_STATE(34)] = 577,
  [SMALL_STATE(35)] = 585,
  [SMALL_STATE(36)] = 597,
  [SMALL_STATE(37)] = 605,
  [SMALL_STATE(38)] = 613,
  [SMALL_STATE(39)] = 626,
  [SMALL_STATE(40)] = 637,
  [SMALL_STATE(41)] = 648,
  [SMALL_STATE(42)] = 659,
  [SMALL_STATE(43)] = 670,
  [SMALL_STATE(44)] = 681,
  [SMALL_STATE(45)] = 691,
  [SMALL_STATE(46)] = 701,
  [SMALL_STATE(47)] = 711,
  [SMALL_STATE(48)] = 721,
  [SMALL_STATE(49)] = 731,
  [SMALL_STATE(50)] = 741,
  [SMALL_STATE(51)] = 751,
  [SMALL_STATE(52)] = 757,
  [SMALL_STATE(53)] = 767,
  [SMALL_STATE(54)] = 775,
  [SMALL_STATE(55)] = 780,
  [SMALL_STATE(56)] = 787,
  [SMALL_STATE(57)] = 794,
  [SMALL_STATE(58)] = 801,
  [SMALL_STATE(59)] = 806,
  [SMALL_STATE(60)] = 811,
  [SMALL_STATE(61)] = 816,
  [SMALL_STATE(62)] = 823,
  [SMALL_STATE(63)] = 828,
  [SMALL_STATE(64)] = 835,
  [SMALL_STATE(65)] = 840,
  [SMALL_STATE(66)] = 845,
  [SMALL_STATE(67)] = 850,
  [SMALL_STATE(68)] = 855,
  [SMALL_STATE(69)] = 862,
  [SMALL_STATE(70)] = 867,
  [SMALL_STATE(71)] = 874,
  [SMALL_STATE(72)] = 881,
  [SMALL_STATE(73)] = 886,
  [SMALL_STATE(74)] = 893,
  [SMALL_STATE(75)] = 900,
  [SMALL_STATE(76)] = 905,
  [SMALL_STATE(77)] = 910,
  [SMALL_STATE(78)] = 917,
  [SMALL_STATE(79)] = 922,
  [SMALL_STATE(80)] = 929,
  [SMALL_STATE(81)] = 936,
  [SMALL_STATE(82)] = 940,
  [SMALL_STATE(83)] = 944,
  [SMALL_STATE(84)] = 948,
  [SMALL_STATE(85)] = 952,
  [SMALL_STATE(86)] = 956,
  [SMALL_STATE(87)] = 960,
  [SMALL_STATE(88)] = 964,
  [SMALL_STATE(89)] = 968,
  [SMALL_STATE(90)] = 972,
  [SMALL_STATE(91)] = 976,
  [SMALL_STATE(92)] = 980,
  [SMALL_STATE(93)] = 984,
  [SMALL_STATE(94)] = 988,
  [SMALL_STATE(95)] = 992,
  [SMALL_STATE(96)] = 996,
  [SMALL_STATE(97)] = 1000,
  [SMALL_STATE(98)] = 1004,
  [SMALL_STATE(99)] = 1008,
  [SMALL_STATE(100)] = 1012,
  [SMALL_STATE(101)] = 1016,
  [SMALL_STATE(102)] = 1020,
  [SMALL_STATE(103)] = 1024,
  [SMALL_STATE(104)] = 1028,
  [SMALL_STATE(105)] = 1032,
  [SMALL_STATE(106)] = 1036,
  [SMALL_STATE(107)] = 1040,
  [SMALL_STATE(108)] = 1044,
  [SMALL_STATE(109)] = 1048,
  [SMALL_STATE(110)] = 1052,
  [SMALL_STATE(111)] = 1056,
  [SMALL_STATE(112)] = 1060,
  [SMALL_STATE(113)] = 1064,
  [SMALL_STATE(114)] = 1068,
  [SMALL_STATE(115)] = 1072,
  [SMALL_STATE(116)] = 1076,
  [SMALL_STATE(117)] = 1080,
  [SMALL_STATE(118)] = 1084,
  [SMALL_STATE(119)] = 1088,
  [SMALL_STATE(120)] = 1092,
  [SMALL_STATE(121)] = 1096,
  [SMALL_STATE(122)] = 1100,
  [SMALL_STATE(123)] = 1104,
  [SMALL_STATE(124)] = 1108,
  [SMALL_STATE(125)] = 1112,
  [SMALL_STATE(126)] = 1116,
  [SMALL_STATE(127)] = 1120,
  [SMALL_STATE(128)] = 1124,
  [SMALL_STATE(129)] = 1128,
  [SMALL_STATE(130)] = 1132,
  [SMALL_STATE(131)] = 1136,
  [SMALL_STATE(132)] = 1140,
  [SMALL_STATE(133)] = 1144,
  [SMALL_STATE(134)] = 1148,
  [SMALL_STATE(135)] = 1152,
  [SMALL_STATE(136)] = 1156,
  [SMALL_STATE(137)] = 1160,
  [SMALL_STATE(138)] = 1164,
  [SMALL_STATE(139)] = 1168,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_metadata_repeat1, 2, 0, 0), SHIFT_REPEAT(109),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_metadata_repeat1, 2, 0, 0), SHIFT_REPEAT(82),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_metadata_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_metadata_repeat1, 2, 0, 0),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_metadata_repeat1, 2, 0, 0), SHIFT_REPEAT(87),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_metadata_repeat1, 2, 0, 0), SHIFT_REPEAT(88),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_metadata_repeat1, 2, 0, 0), SHIFT_REPEAT(89),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [84] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(77),
  [87] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(85),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_line, 4, 0, 6),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_line, 5, 0, 10),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_object_line_repeat1, 2, 0, 13),
  [98] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_object_line_repeat1, 2, 0, 13), SHIFT_REPEAT(102),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_line, 6, 0, 14),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_line, 7, 0, 18),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_line, 2, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment_line, 2, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_line, 3, 0, 11),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment_line, 3, 0, 11),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_blob_line, 4, 0, 17),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_blob_line, 4, 0, 17),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_description_line, 4, 0, 16),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_description_line, 4, 0, 16),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_line, 4, 0, 15),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_line, 4, 0, 15),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ref_line, 4, 0, 17),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ref_line, 4, 0, 17),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_line, 6, 0, 21),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_line, 6, 0, 21),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group_by_line, 8, 0, 23),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_group_by_line, 8, 0, 23),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_line, 8, 0, 23),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field_line, 8, 0, 23),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_object_line_repeat1, 1, 0, 9),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_description_continuation, 2, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_blank_line, 1, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading_reset, 3, 0, 1),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_metadata, 4, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_metadata, 3, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading_reset, 2, 0, 1),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading, 4, 0, 1),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [173] = {.entry = {.count = 1, .reusable = false}}, SHIFT(126),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_box_quoted_repeat1, 2, 0, 0),
  [181] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_box_quoted_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading_dimension, 2, 0, 2),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_box_repeat1, 2, 0, 0),
  [202] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_box_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_box_ident, 1, 0, 0),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(138),
  [215] = {.entry = {.count = 1, .reusable = false}}, SHIFT(136),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_box_tag, 1, 0, 2),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markl_id, 3, 0, 19),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_box_type, 2, 0, 4),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_box_computed_tag, 2, 0, 4),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_box_blob, 2, 0, 0),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_box, 5, 0, 8),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_box, 4, 0, 8),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_box_bare_value, 1, 0, 0),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_box_field, 3, 0, 20),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_box_tag, 1, 0, 12),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_name, 1, 0, 0),
  [253] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dim_name, 1, 0, 0),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_box, 3, 0, 8),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [259] = {.entry = {.count = 1, .reusable = false}}, SHIFT(113),
  [261] = {.entry = {.count = 1, .reusable = false}}, SHIFT(114),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_box_quoted, 2, 0, 0),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_box_quoted, 3, 0, 0),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [271] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markl_id, 4, 0, 22),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_blob, 2, 0, 0),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [283] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_text, 1, 0, 0),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [297] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(139),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [305] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading_dimension, 3, 0, 7),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [311] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading_type, 2, 0, 4),
  [313] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_qualifier, 3, 0, 4),
  [315] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading_value_text, 1, 0, 0),
  [317] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading_value, 2, 0, 5),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [323] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_description, 1, 0, 0),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [335] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading_tag, 1, 0, 2),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [343] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_description_text, 1, 0, 0),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [355] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_type_name, 1, 0, 0),
  [357] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_type, 2, 0, 4),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [361] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_reference_id, 1, 0, 0),
  [363] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [367] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading_tag, 1, 0, 3),
  [369] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [371] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [373] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [375] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [377] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [379] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [381] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [383] = {.entry = {.count = 1, .reusable = true}}, SHIFT(137),
  [385] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_cutting_garden_organize(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "cutting_garden_organize",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
