// Code generated by tommy 0.4.6 (41efed3); DO NOT EDIT.

package cgconfig

import (
	"fmt"
	"strings"

	"github.com/amarbel-llc/cutting-garden/plugins/caldav"
	"github.com/amarbel-llc/cutting-garden/plugins/jira"
	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type ConfigV0Document struct {
	data   ConfigV0
	cstDoc *document.Document
	model  *cst.Value
}

func DecodeConfigV0(input []byte) (*ConfigV0Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}
	model, err := cst.Decompose(doc.Root())
	if err != nil {
		return nil, err
	}

	d := &ConfigV0Document{
		cstDoc: doc,
		model:  model,
	}

	if _vCaldav, _ok := model.Get("caldav"); _ok && _vCaldav.Kind == cst.VTable {
		_vCaldav.MarkSeen()
		if err := caldav.DecodeAccountsConfigInto(&d.data.Caldav, _vCaldav); err != nil {
			return nil, fmt.Errorf("caldav: %w", err)
		}
	}
	if _vJira, _ok := model.Get("jira"); _ok && _vJira.Kind == cst.VTable {
		_vJira.MarkSeen()
		if err := jira.DecodeAccountsConfigInto(&d.data.Jira, _vJira); err != nil {
			return nil, fmt.Errorf("jira: %w", err)
		}
	}
	if err := d.data.Validate(); err != nil {
		return nil, fmt.Errorf("validation failed: %w", err)
	}
	return d, nil
}

func (d *ConfigV0Document) Data() *ConfigV0 {
	return &d.data
}

func (d *ConfigV0Document) Encode() ([]byte, error) {
	if err := d.data.Validate(); err != nil {
		return nil, fmt.Errorf("validation failed: %w", err)
	}
	{
		tableNode := cst.EnsureChildTable(d.cstDoc.Root(), d.cstDoc.Root(), "caldav")
		if err := caldav.EncodeAccountsConfigFrom(&d.data.Caldav, d.cstDoc, tableNode); err != nil {
			return nil, fmt.Errorf("caldav: %w", err)
		}
	}
	{
		tableNode := cst.EnsureChildTable(d.cstDoc.Root(), d.cstDoc.Root(), "jira")
		if err := jira.EncodeAccountsConfigFrom(&d.data.Jira, d.cstDoc, tableNode); err != nil {
			return nil, fmt.Errorf("jira: %w", err)
		}
	}
	return d.cstDoc.Bytes(), nil
}

func (d *ConfigV0Document) Undecoded() []string {
	if d.model == nil {
		return nil
	}
	return d.model.Undecoded()
}

func (d *ConfigV0Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *ConfigV0Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *ConfigV0Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *ConfigV0Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeConfigV0Into(data *ConfigV0, sub *cst.Value) error {
	if _vCaldav, _ok := sub.Get("caldav"); _ok && _vCaldav.Kind == cst.VTable {
		_vCaldav.MarkSeen()
		if err := caldav.DecodeAccountsConfigInto(&data.Caldav, _vCaldav); err != nil {
			return fmt.Errorf("caldav: %w", err)
		}
	}
	if _vJira, _ok := sub.Get("jira"); _ok && _vJira.Kind == cst.VTable {
		_vJira.MarkSeen()
		if err := jira.DecodeAccountsConfigInto(&data.Jira, _vJira); err != nil {
			return fmt.Errorf("jira: %w", err)
		}
	}
	if err := data.Validate(); err != nil {
		return fmt.Errorf("validation failed: %w", err)
	}
	return nil
}

func EncodeConfigV0From(data *ConfigV0, doc *document.Document, container *cst.Node) error {
	if err := data.Validate(); err != nil {
		return fmt.Errorf("validation failed: %w", err)
	}
	{
		tableNode := cst.EnsureChildTable(doc.Root(), container, "caldav")
		if err := caldav.EncodeAccountsConfigFrom(&data.Caldav, doc, tableNode); err != nil {
			return fmt.Errorf("caldav: %w", err)
		}
	}
	{
		tableNode := cst.EnsureChildTable(doc.Root(), container, "jira")
		if err := jira.EncodeAccountsConfigFrom(&data.Jira, doc, tableNode); err != nil {
			return fmt.Errorf("jira: %w", err)
		}
	}
	return nil
}
