// Code generated by tommy 0.5.0 (b88f14c); DO NOT EDIT.

package cgconfig

import (
	"fmt"
	"strings"

	"code.linenisgreat.com/cutting-garden/internal/traversal_serve"
	"code.linenisgreat.com/cutting-garden/plugins/caldav"
	"code.linenisgreat.com/cutting-garden/plugins/fastmail"
	"code.linenisgreat.com/cutting-garden/plugins/jira"
	"code.linenisgreat.com/tommy/pkg/cst"
	"code.linenisgreat.com/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type ConfigV0Document struct {
	data   ConfigV0
	cstDoc *document.Document
	model  *cst.Value
}

func DecodeConfigV0(input []byte) (*ConfigV0Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}
	model, err := cst.Decompose(doc.Root())
	if err != nil {
		return nil, err
	}

	d := &ConfigV0Document{
		cstDoc: doc,
		model:  model,
	}

	if _vCaldav, _ok := model.Get("caldav"); _ok && _vCaldav.Kind == cst.VTable {
		_vCaldav.MarkSeen()
		if err := caldav.DecodeAccountsConfigInto(&d.data.Caldav, _vCaldav); err != nil {
			return nil, fmt.Errorf("caldav: %w", err)
		}
	}
	if _vFastmail, _ok := model.Get("fastmail"); _ok && _vFastmail.Kind == cst.VTable {
		_vFastmail.MarkSeen()
		if err := fastmail.DecodeAccountsConfigInto(&d.data.Fastmail, _vFastmail); err != nil {
			return nil, fmt.Errorf("fastmail: %w", err)
		}
	}
	if _vJira, _ok := model.Get("jira"); _ok && _vJira.Kind == cst.VTable {
		_vJira.MarkSeen()
		if err := jira.DecodeAccountsConfigInto(&d.data.Jira, _vJira); err != nil {
			return nil, fmt.Errorf("jira: %w", err)
		}
	}
	if _vOrganize, _ok := model.Get("organize"); _ok && _vOrganize.Kind == cst.VTable {
		_vOrganize.MarkSeen()
		if _vOrganizeDateGranularity, _ok := _vOrganize.Get("date_granularity"); _ok && _vOrganizeDateGranularity.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vOrganizeDateGranularity.Leaf); _xok {
				d.data.Organize.DateGranularity = _x
				_vOrganizeDateGranularity.MarkConsumed()
			}
		}
	} else {
		if _vDateGranularity, _ok := model.Get("date_granularity"); _ok && _vDateGranularity.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vDateGranularity.Leaf); _xok {
				d.data.Organize.DateGranularity = _x
				_vDateGranularity.MarkConsumed()
			}
		}
	}
	if _vPlugins, _ok := model.Get("plugins"); _ok && _vPlugins.Kind == cst.VArray {
		_vPlugins.MarkSeen()
		d.data.Plugins = make([]traversal_serve.PluginStanza, len(_vPlugins.Items))
		for i := range _vPlugins.Items {
			_ePlugins := &_vPlugins.Items[i]
			_ePlugins.MarkSeen()
			if err := traversal_serve.DecodePluginStanzaInto(&d.data.Plugins[i], _ePlugins); err != nil {
				return nil, fmt.Errorf("plugins[%d]: %w", i, err)
			}
		}
	}
	if _eaPlugins, _eaok := model.Get("plugins"); _eaok && _eaPlugins.IsEmptyArray() {
		_eaPlugins.MarkConsumed()
		d.data.Plugins = []traversal_serve.PluginStanza{}
	}
	if _vTraversalPlugins, _ok := model.Get("traversal_plugins"); _ok && _vTraversalPlugins.Kind == cst.VArray {
		_vTraversalPlugins.MarkSeen()
		d.data.TraversalPlugins = make([]traversal_serve.PluginStanza, len(_vTraversalPlugins.Items))
		for i := range _vTraversalPlugins.Items {
			_eTraversalPlugins := &_vTraversalPlugins.Items[i]
			_eTraversalPlugins.MarkSeen()
			if err := traversal_serve.DecodePluginStanzaInto(&d.data.TraversalPlugins[i], _eTraversalPlugins); err != nil {
				return nil, fmt.Errorf("traversal_plugins[%d]: %w", i, err)
			}
		}
	}
	if _eaTraversalPlugins, _eaok := model.Get("traversal_plugins"); _eaok && _eaTraversalPlugins.IsEmptyArray() {
		_eaTraversalPlugins.MarkConsumed()
		d.data.TraversalPlugins = []traversal_serve.PluginStanza{}
	}
	if err := d.data.Validate(); err != nil {
		return nil, fmt.Errorf("validation failed: %w", err)
	}
	return d, nil
}

func (d *ConfigV0Document) Data() *ConfigV0 {
	return &d.data
}

func (d *ConfigV0Document) Encode() ([]byte, error) {
	if err := d.data.Validate(); err != nil {
		return nil, fmt.Errorf("validation failed: %w", err)
	}
	{
		tableNode := cst.EnsureChildTable(d.cstDoc.Root(), d.cstDoc.Root(), "caldav")
		if err := caldav.EncodeAccountsConfigFrom(&d.data.Caldav, d.cstDoc, tableNode); err != nil {
			return nil, fmt.Errorf("caldav: %w", err)
		}
	}
	{
		tableNode := cst.EnsureChildTable(d.cstDoc.Root(), d.cstDoc.Root(), "fastmail")
		if err := fastmail.EncodeAccountsConfigFrom(&d.data.Fastmail, d.cstDoc, tableNode); err != nil {
			return nil, fmt.Errorf("fastmail: %w", err)
		}
	}
	{
		tableNode := cst.EnsureChildTable(d.cstDoc.Root(), d.cstDoc.Root(), "jira")
		if err := jira.EncodeAccountsConfigFrom(&d.data.Jira, d.cstDoc, tableNode); err != nil {
			return nil, fmt.Errorf("jira: %w", err)
		}
	}
	{
		tableNode := cst.EnsureChildTable(d.cstDoc.Root(), d.cstDoc.Root(), "organize")
		if d.data.Organize.DateGranularity != "" {
			if err := cst.SetAny(tableNode, "date_granularity", d.data.Organize.DateGranularity); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		} else {
			cst.DeleteValue(tableNode, "date_granularity")
		}
	}
	{
		_existPlugins := cst.FindArrayTableNodes(d.cstDoc.Root(), "plugins")
		for i := range d.data.Plugins {
			var container *cst.Node
			if i < len(_existPlugins) {
				container = _existPlugins[i]
			} else {
				container = cst.AppendArrayTableEntryAfter(d.cstDoc.Root(), "plugins")
			}
			if err := traversal_serve.EncodePluginStanzaFrom(&d.data.Plugins[i], d.cstDoc, container); err != nil {
				return nil, fmt.Errorf("plugins[%d]: %w", i, err)
			}
		}
	}
	{
		_existTraversalPlugins := cst.FindArrayTableNodes(d.cstDoc.Root(), "traversal_plugins")
		for i := range d.data.TraversalPlugins {
			var container *cst.Node
			if i < len(_existTraversalPlugins) {
				container = _existTraversalPlugins[i]
			} else {
				container = cst.AppendArrayTableEntryAfter(d.cstDoc.Root(), "traversal_plugins")
			}
			if err := traversal_serve.EncodePluginStanzaFrom(&d.data.TraversalPlugins[i], d.cstDoc, container); err != nil {
				return nil, fmt.Errorf("traversal_plugins[%d]: %w", i, err)
			}
		}
	}
	return d.cstDoc.Bytes(), nil
}

func (d *ConfigV0Document) Undecoded() []string {
	if d.model == nil {
		return nil
	}
	return d.model.Undecoded()
}

func (d *ConfigV0Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *ConfigV0Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *ConfigV0Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *ConfigV0Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeConfigV0Into(data *ConfigV0, sub *cst.Value) error {
	if _vCaldav, _ok := sub.Get("caldav"); _ok && _vCaldav.Kind == cst.VTable {
		_vCaldav.MarkSeen()
		if err := caldav.DecodeAccountsConfigInto(&data.Caldav, _vCaldav); err != nil {
			return fmt.Errorf("caldav: %w", err)
		}
	}
	if _vFastmail, _ok := sub.Get("fastmail"); _ok && _vFastmail.Kind == cst.VTable {
		_vFastmail.MarkSeen()
		if err := fastmail.DecodeAccountsConfigInto(&data.Fastmail, _vFastmail); err != nil {
			return fmt.Errorf("fastmail: %w", err)
		}
	}
	if _vJira, _ok := sub.Get("jira"); _ok && _vJira.Kind == cst.VTable {
		_vJira.MarkSeen()
		if err := jira.DecodeAccountsConfigInto(&data.Jira, _vJira); err != nil {
			return fmt.Errorf("jira: %w", err)
		}
	}
	if _vOrganize, _ok := sub.Get("organize"); _ok && _vOrganize.Kind == cst.VTable {
		_vOrganize.MarkSeen()
		if _vOrganizeDateGranularity, _ok := _vOrganize.Get("date_granularity"); _ok && _vOrganizeDateGranularity.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vOrganizeDateGranularity.Leaf); _xok {
				data.Organize.DateGranularity = _x
				_vOrganizeDateGranularity.MarkConsumed()
			}
		}
	} else {
		if _vDateGranularity, _ok := sub.Get("date_granularity"); _ok && _vDateGranularity.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vDateGranularity.Leaf); _xok {
				data.Organize.DateGranularity = _x
				_vDateGranularity.MarkConsumed()
			}
		}
	}
	if _vPlugins, _ok := sub.Get("plugins"); _ok && _vPlugins.Kind == cst.VArray {
		_vPlugins.MarkSeen()
		data.Plugins = make([]traversal_serve.PluginStanza, len(_vPlugins.Items))
		for i := range _vPlugins.Items {
			_ePlugins := &_vPlugins.Items[i]
			_ePlugins.MarkSeen()
			if err := traversal_serve.DecodePluginStanzaInto(&data.Plugins[i], _ePlugins); err != nil {
				return fmt.Errorf("plugins[%d]: %w", i, err)
			}
		}
	}
	if _eaPlugins, _eaok := sub.Get("plugins"); _eaok && _eaPlugins.IsEmptyArray() {
		_eaPlugins.MarkConsumed()
		data.Plugins = []traversal_serve.PluginStanza{}
	}
	if _vTraversalPlugins, _ok := sub.Get("traversal_plugins"); _ok && _vTraversalPlugins.Kind == cst.VArray {
		_vTraversalPlugins.MarkSeen()
		data.TraversalPlugins = make([]traversal_serve.PluginStanza, len(_vTraversalPlugins.Items))
		for i := range _vTraversalPlugins.Items {
			_eTraversalPlugins := &_vTraversalPlugins.Items[i]
			_eTraversalPlugins.MarkSeen()
			if err := traversal_serve.DecodePluginStanzaInto(&data.TraversalPlugins[i], _eTraversalPlugins); err != nil {
				return fmt.Errorf("traversal_plugins[%d]: %w", i, err)
			}
		}
	}
	if _eaTraversalPlugins, _eaok := sub.Get("traversal_plugins"); _eaok && _eaTraversalPlugins.IsEmptyArray() {
		_eaTraversalPlugins.MarkConsumed()
		data.TraversalPlugins = []traversal_serve.PluginStanza{}
	}
	if err := data.Validate(); err != nil {
		return fmt.Errorf("validation failed: %w", err)
	}
	return nil
}

func EncodeConfigV0From(data *ConfigV0, doc *document.Document, container *cst.Node) error {
	if err := data.Validate(); err != nil {
		return fmt.Errorf("validation failed: %w", err)
	}
	{
		tableNode := cst.EnsureChildTable(doc.Root(), container, "caldav")
		if err := caldav.EncodeAccountsConfigFrom(&data.Caldav, doc, tableNode); err != nil {
			return fmt.Errorf("caldav: %w", err)
		}
	}
	{
		tableNode := cst.EnsureChildTable(doc.Root(), container, "fastmail")
		if err := fastmail.EncodeAccountsConfigFrom(&data.Fastmail, doc, tableNode); err != nil {
			return fmt.Errorf("fastmail: %w", err)
		}
	}
	{
		tableNode := cst.EnsureChildTable(doc.Root(), container, "jira")
		if err := jira.EncodeAccountsConfigFrom(&data.Jira, doc, tableNode); err != nil {
			return fmt.Errorf("jira: %w", err)
		}
	}
	{
		tableNode := cst.EnsureChildTable(doc.Root(), container, "organize")
		if data.Organize.DateGranularity != "" {
			if err := cst.SetAny(tableNode, "date_granularity", data.Organize.DateGranularity); err != nil {
				return fmt.Errorf("%w", err)
			}
		} else {
			cst.DeleteValue(tableNode, "date_granularity")
		}
	}
	{
		_apPlugins := container
		_existPlugins := cst.FindChildArrayTableNodes(doc.Root(), _apPlugins, "plugins")
		for i := range data.Plugins {
			var container *cst.Node
			if i < len(_existPlugins) {
				container = _existPlugins[i]
			} else {
				container = cst.AppendChildArrayTableEntry(doc.Root(), _apPlugins, "plugins")
			}
			if err := traversal_serve.EncodePluginStanzaFrom(&data.Plugins[i], doc, container); err != nil {
				return fmt.Errorf("plugins[%d]: %w", i, err)
			}
		}
	}
	{
		_apTraversalPlugins := container
		_existTraversalPlugins := cst.FindChildArrayTableNodes(doc.Root(), _apTraversalPlugins, "traversal_plugins")
		for i := range data.TraversalPlugins {
			var container *cst.Node
			if i < len(_existTraversalPlugins) {
				container = _existTraversalPlugins[i]
			} else {
				container = cst.AppendChildArrayTableEntry(doc.Root(), _apTraversalPlugins, "traversal_plugins")
			}
			if err := traversal_serve.EncodePluginStanzaFrom(&data.TraversalPlugins[i], doc, container); err != nil {
				return fmt.Errorf("traversal_plugins[%d]: %w", i, err)
			}
		}
	}
	return nil
}

type OrganizeConfigDocument struct {
	data   OrganizeConfig
	cstDoc *document.Document
	model  *cst.Value
}

func DecodeOrganizeConfig(input []byte) (*OrganizeConfigDocument, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}
	model, err := cst.Decompose(doc.Root())
	if err != nil {
		return nil, err
	}

	d := &OrganizeConfigDocument{
		cstDoc: doc,
		model:  model,
	}

	if _vDateGranularity, _ok := model.Get("date_granularity"); _ok && _vDateGranularity.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vDateGranularity.Leaf); _xok {
			d.data.DateGranularity = _x
			_vDateGranularity.MarkConsumed()
		}
	}
	if err := d.data.Validate(); err != nil {
		return nil, fmt.Errorf("validation failed: %w", err)
	}
	return d, nil
}

func (d *OrganizeConfigDocument) Data() *OrganizeConfig {
	return &d.data
}

func (d *OrganizeConfigDocument) Encode() ([]byte, error) {
	if err := d.data.Validate(); err != nil {
		return nil, fmt.Errorf("validation failed: %w", err)
	}
	if d.data.DateGranularity != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "date_granularity", d.data.DateGranularity); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "date_granularity")
	}
	return d.cstDoc.Bytes(), nil
}

func (d *OrganizeConfigDocument) Undecoded() []string {
	if d.model == nil {
		return nil
	}
	return d.model.Undecoded()
}

func (d *OrganizeConfigDocument) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *OrganizeConfigDocument) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *OrganizeConfigDocument) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *OrganizeConfigDocument) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeOrganizeConfigInto(data *OrganizeConfig, sub *cst.Value) error {
	if _vDateGranularity, _ok := sub.Get("date_granularity"); _ok && _vDateGranularity.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vDateGranularity.Leaf); _xok {
			data.DateGranularity = _x
			_vDateGranularity.MarkConsumed()
		}
	}
	if err := data.Validate(); err != nil {
		return fmt.Errorf("validation failed: %w", err)
	}
	return nil
}

func EncodeOrganizeConfigFrom(data *OrganizeConfig, doc *document.Document, container *cst.Node) error {
	if err := data.Validate(); err != nil {
		return fmt.Errorf("validation failed: %w", err)
	}
	if data.DateGranularity != "" {
		if err := cst.SetAny(container, "date_granularity", data.DateGranularity); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "date_granularity")
	}
	return nil
}
