// Code generated by tommy 0.4.7 (unknown); DO NOT EDIT.

package traversal_serve

import (
	"fmt"
	"strings"

	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type PluginStanzaDocument struct {
	data   PluginStanza
	cstDoc *document.Document
	model  *cst.Value
}

func DecodePluginStanza(input []byte) (*PluginStanzaDocument, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}
	model, err := cst.Decompose(doc.Root())
	if err != nil {
		return nil, err
	}

	d := &PluginStanzaDocument{
		cstDoc: doc,
		model:  model,
	}

	if _vName, _ok := model.Get("name"); _ok && _vName.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vName.Leaf); _xok {
			d.data.Name = _x
			_vName.MarkConsumed()
		}
	}
	if _vCommand, _ok := model.Get("command"); _ok && _vCommand.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractStringSlice(_vCommand.Leaf); _xok {
			d.data.Command = _x
			if d.data.Command == nil {
				d.data.Command = []string{}
			}
			_vCommand.MarkConsumed()
		}
	}
	if _vSchemes, _ok := model.Get("schemes"); _ok && _vSchemes.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractStringSlice(_vSchemes.Leaf); _xok {
			d.data.Schemes = _x
			if d.data.Schemes == nil {
				d.data.Schemes = []string{}
			}
			_vSchemes.MarkConsumed()
		}
	}
	if _vConfigSection, _ok := model.Get("config_section"); _ok && _vConfigSection.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vConfigSection.Leaf); _xok {
			d.data.ConfigSection = _x
			_vConfigSection.MarkConsumed()
		}
	}
	if err := d.data.Validate(); err != nil {
		return nil, fmt.Errorf("validation failed: %w", err)
	}
	return d, nil
}

func (d *PluginStanzaDocument) Data() *PluginStanza {
	return &d.data
}

func (d *PluginStanzaDocument) Encode() ([]byte, error) {
	if err := d.data.Validate(); err != nil {
		return nil, fmt.Errorf("validation failed: %w", err)
	}
	if d.data.Name != "" || cst.HasValue(d.cstDoc.Root(), "name") {
		if err := cst.SetAny(d.cstDoc.Root(), "name", d.data.Name); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	{
		if d.data.Command != nil {
			if err := cst.SetAny(d.cstDoc.Root(), "command", d.data.Command); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
	}
	{
		if d.data.Schemes != nil {
			if err := cst.SetAny(d.cstDoc.Root(), "schemes", d.data.Schemes); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
	}
	if d.data.ConfigSection != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "config_section", d.data.ConfigSection); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "config_section")
	}
	return d.cstDoc.Bytes(), nil
}

func (d *PluginStanzaDocument) Undecoded() []string {
	if d.model == nil {
		return nil
	}
	return d.model.Undecoded()
}

func (d *PluginStanzaDocument) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *PluginStanzaDocument) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *PluginStanzaDocument) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *PluginStanzaDocument) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodePluginStanzaInto(data *PluginStanza, sub *cst.Value) error {
	if _vName, _ok := sub.Get("name"); _ok && _vName.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vName.Leaf); _xok {
			data.Name = _x
			_vName.MarkConsumed()
		}
	}
	if _vCommand, _ok := sub.Get("command"); _ok && _vCommand.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractStringSlice(_vCommand.Leaf); _xok {
			data.Command = _x
			if data.Command == nil {
				data.Command = []string{}
			}
			_vCommand.MarkConsumed()
		}
	}
	if _vSchemes, _ok := sub.Get("schemes"); _ok && _vSchemes.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractStringSlice(_vSchemes.Leaf); _xok {
			data.Schemes = _x
			if data.Schemes == nil {
				data.Schemes = []string{}
			}
			_vSchemes.MarkConsumed()
		}
	}
	if _vConfigSection, _ok := sub.Get("config_section"); _ok && _vConfigSection.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vConfigSection.Leaf); _xok {
			data.ConfigSection = _x
			_vConfigSection.MarkConsumed()
		}
	}
	if err := data.Validate(); err != nil {
		return fmt.Errorf("validation failed: %w", err)
	}
	return nil
}

func EncodePluginStanzaFrom(data *PluginStanza, doc *document.Document, container *cst.Node) error {
	if err := data.Validate(); err != nil {
		return fmt.Errorf("validation failed: %w", err)
	}
	if data.Name != "" || cst.HasValue(container, "name") {
		if err := cst.SetAny(container, "name", data.Name); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	{
		if data.Command != nil {
			if err := cst.SetAny(container, "command", data.Command); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
	}
	{
		if data.Schemes != nil {
			if err := cst.SetAny(container, "schemes", data.Schemes); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
	}
	if data.ConfigSection != "" {
		if err := cst.SetAny(container, "config_section", data.ConfigSection); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "config_section")
	}
	return nil
}
