// Code generated by tommy 0.4.7 (65f9cee); DO NOT EDIT.

package config_common

import (
	"fmt"
	"strings"

	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type RootDocument struct {
	data   Root
	cstDoc *document.Document
	model  *cst.Value
}

func DecodeRoot(input []byte) (*RootDocument, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}
	model, err := cst.Decompose(doc.Root())
	if err != nil {
		return nil, err
	}

	d := &RootDocument{
		cstDoc: doc,
		model:  model,
	}

	if _vName, _ok := model.Get("name"); _ok && _vName.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vName.Leaf); _xok {
			d.data.Name = _x
			_vName.MarkConsumed()
		}
	}
	if _vUrl, _ok := model.Get("url"); _ok && _vUrl.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vUrl.Leaf); _xok {
			d.data.URL = _x
			_vUrl.MarkConsumed()
		}
	}
	return d, nil
}

func (d *RootDocument) Data() *Root {
	return &d.data
}

func (d *RootDocument) Encode() ([]byte, error) {
	if d.data.Name != "" || cst.HasValue(d.cstDoc.Root(), "name") {
		if err := cst.SetAny(d.cstDoc.Root(), "name", d.data.Name); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.URL != "" || cst.HasValue(d.cstDoc.Root(), "url") {
		if err := cst.SetAny(d.cstDoc.Root(), "url", d.data.URL); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	return d.cstDoc.Bytes(), nil
}

func (d *RootDocument) Undecoded() []string {
	if d.model == nil {
		return nil
	}
	return d.model.Undecoded()
}

func (d *RootDocument) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *RootDocument) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *RootDocument) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *RootDocument) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeRootInto(data *Root, sub *cst.Value) error {
	if _vName, _ok := sub.Get("name"); _ok && _vName.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vName.Leaf); _xok {
			data.Name = _x
			_vName.MarkConsumed()
		}
	}
	if _vUrl, _ok := sub.Get("url"); _ok && _vUrl.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vUrl.Leaf); _xok {
			data.URL = _x
			_vUrl.MarkConsumed()
		}
	}
	return nil
}

func EncodeRootFrom(data *Root, doc *document.Document, container *cst.Node) error {
	if data.Name != "" || cst.HasValue(container, "name") {
		if err := cst.SetAny(container, "name", data.Name); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.URL != "" || cst.HasValue(container, "url") {
		if err := cst.SetAny(container, "url", data.URL); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	return nil
}

type AccountDocument struct {
	data   Account
	cstDoc *document.Document
	model  *cst.Value
}

func DecodeAccount(input []byte) (*AccountDocument, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}
	model, err := cst.Decompose(doc.Root())
	if err != nil {
		return nil, err
	}

	d := &AccountDocument{
		cstDoc: doc,
		model:  model,
	}

	if _vName, _ok := model.Get("name"); _ok && _vName.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vName.Leaf); _xok {
			d.data.Name = _x
			_vName.MarkConsumed()
		}
	}
	if _vUrl, _ok := model.Get("url"); _ok && _vUrl.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vUrl.Leaf); _xok {
			d.data.URL = _x
			_vUrl.MarkConsumed()
		}
	}
	if _vUsername, _ok := model.Get("username"); _ok && _vUsername.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vUsername.Leaf); _xok {
			d.data.Username = _x
			_vUsername.MarkConsumed()
		}
	}
	if _vPasswordEnv, _ok := model.Get("password_env"); _ok && _vPasswordEnv.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vPasswordEnv.Leaf); _xok {
			d.data.PasswordEnv = _x
			_vPasswordEnv.MarkConsumed()
		}
	}
	return d, nil
}

func (d *AccountDocument) Data() *Account {
	return &d.data
}

func (d *AccountDocument) Encode() ([]byte, error) {
	if d.data.Name != "" || cst.HasValue(d.cstDoc.Root(), "name") {
		if err := cst.SetAny(d.cstDoc.Root(), "name", d.data.Name); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.URL != "" || cst.HasValue(d.cstDoc.Root(), "url") {
		if err := cst.SetAny(d.cstDoc.Root(), "url", d.data.URL); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.Username != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "username", d.data.Username); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "username")
	}
	if d.data.PasswordEnv != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "password_env", d.data.PasswordEnv); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "password_env")
	}
	return d.cstDoc.Bytes(), nil
}

func (d *AccountDocument) Undecoded() []string {
	if d.model == nil {
		return nil
	}
	return d.model.Undecoded()
}

func (d *AccountDocument) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *AccountDocument) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *AccountDocument) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *AccountDocument) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeAccountInto(data *Account, sub *cst.Value) error {
	if _vName, _ok := sub.Get("name"); _ok && _vName.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vName.Leaf); _xok {
			data.Name = _x
			_vName.MarkConsumed()
		}
	}
	if _vUrl, _ok := sub.Get("url"); _ok && _vUrl.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vUrl.Leaf); _xok {
			data.URL = _x
			_vUrl.MarkConsumed()
		}
	}
	if _vUsername, _ok := sub.Get("username"); _ok && _vUsername.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vUsername.Leaf); _xok {
			data.Username = _x
			_vUsername.MarkConsumed()
		}
	}
	if _vPasswordEnv, _ok := sub.Get("password_env"); _ok && _vPasswordEnv.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vPasswordEnv.Leaf); _xok {
			data.PasswordEnv = _x
			_vPasswordEnv.MarkConsumed()
		}
	}
	return nil
}

func EncodeAccountFrom(data *Account, doc *document.Document, container *cst.Node) error {
	if data.Name != "" || cst.HasValue(container, "name") {
		if err := cst.SetAny(container, "name", data.Name); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.URL != "" || cst.HasValue(container, "url") {
		if err := cst.SetAny(container, "url", data.URL); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.Username != "" {
		if err := cst.SetAny(container, "username", data.Username); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "username")
	}
	if data.PasswordEnv != "" {
		if err := cst.SetAny(container, "password_env", data.PasswordEnv); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "password_env")
	}
	return nil
}
