// Code generated by dagnabit (0.5.0+182545a); DO NOT EDIT.

package config_common

// The public facade for this package lives at
// code.linenisgreat.com/cutting-garden/pkgs/config_common. Exported in
// COPY mode (real source copied into pkgs/, not thin aliases) so the
// type definitions live in a non-internal package: tommy resolves a
// config struct's field types to their DEFINING package, so caldav's
// generated config codec (plugins/caldav) must see config_common defined
// outside internal/ to stay guard-legal (RFC 0009 §4/§5). The explicit
// package arg scopes copy mode to THIS package; the registry/interface
// facades stay alias-mode (their identity is load-bearing).
//
//go:generate dagnabit export -copy code.linenisgreat.com/cutting-garden/internal/config_common
