// Code generated by dagnabit (0.4.1+cb8b767); DO NOT EDIT.

package cgapp

import internal "github.com/amarbel-llc/cutting-garden/internal/cgapp"

// Build returns a fully-configured cutting-garden Utility with the
// canonical name "cutting-garden", the "cg" alias, the hidden
// `complete` subcommand registered, and the nine user-facing
// subcommands (capture, restore, diff, serve, failures, health, list,
// mcp, version) attached.
//
// Every cutting-garden binary main.go calls this and dispatches
// utility.Run(os.Args).
var Build = internal.Build
