// Code generated by dagnabit (0.4.1+400e71c); DO NOT EDIT.

package capture_plugin

import internal "github.com/amarbel-llc/cutting-garden/internal/capture_plugin"

// BinaryInfo identifies the plugin binary that produced a capture. Name
// and Version are required; Digest (markl id of the binary itself) is
// optional and, when present, makes the binary's bytes part of identity
// — RFC 0002 RECOMMENDS it only under deterministic builds, so callers
// on non-deterministic builds leave it empty to avoid identity churn.
type BinaryInfo = internal.BinaryInfo

// HostInfo describes the machine a capture ran on. It feeds the
// `jcs-cutting_garden-capture-environment-host-v1` node body and is part
// of capture identity: two captures on the same machine share a host
// markl-id.
type HostInfo = internal.HostInfo

// Invocation is the resolved request the capture answered. It feeds the
// `jcs-cutting_garden-capture-invocation-v1` node and is part of
// identity: two captures with identical invocations share an invocation
// markl-id.
type Invocation = internal.Invocation

// Node is a parsed protocol node: its type-string, its ordered typed
// blob references, and its body (nil for metadata-only nodes; the raw
// bytes after the blank line otherwise, JCS callers TrimSpace before
// unmarshaling).
type Node = internal.Node

// PluginEnv is the plugin-defined, identity-affecting environment node
// the environment subtree REQUIRES (RFC 0002 §Environment). TypeString
// is the plugin's `jcs-<plugin>-capture-environment-v1`; Body is its
// JCS-serializable value (an ASCII-keyed map per jcsMarshal's contract).
type PluginEnv = internal.PluginEnv

// ReceiptParams is everything WriteReceipt needs to assemble one
// capture's merkle tree. The payload subtree is the caller's
// responsibility: it writes its payload node(s) through the same Writer
// and passes the resulting reference(s) in PayloadRefs.
type ReceiptParams = internal.ReceiptParams

// Ref is one FDR-0001 typed blob reference: a named slot pointing at a
// previously-written node by its markl digest and type-string, with an
// optional type-signature lock.
type Ref = internal.Ref

// TypeDef is the registrable interface definition of one node type. It
// is the source the canonical type-blob (and therefore the signature) is
// derived from.
type TypeDef = internal.TypeDef

// Writer is the narrow sink every node blob flows through. WriteBlob
// streams r into the backing store and returns the content-addressed
// markl id (as a string, e.g. "sha256-…") plus the byte count. It is
// the in-process analogue of RFC 0002's writer-subprocess contract.
type Writer = internal.Writer

// BuildNode is the exported entry point bindings use to materialize a
// plugin-defined node (e.g. the git payload node) in the same byte
// framing the protocol nodes use. typeString is the `!`-line value;
// refs are emitted in order; body is nil for metadata-only nodes.
var BuildNode = internal.BuildNode

// GatherHost collects the current host's identity fields. os and arch
// come from the Go runtime; kernel is read from the OS where cheaply
// available (Linux `/proc/sys/kernel/osrelease`); libc detection is not
// attempted and reports "unknown" — RFC 0002 requires the field, not a
// specific provenance, and a wrong value would forge identity. Refining
// kernel/libc detection is a documented follow-up.
var GatherHost = internal.GatherHost

// JCS exposes the package's JCS-canonical JSON marshaler to bindings
// that build their own node bodies. The ASCII-key / no-float constraint
// documented on jcsMarshal applies.
var JCS = internal.JCS

// KindFromReceiptType extracts the capture kind from a protocol receipt
// type-string, e.g. "cutting_garden-capture-receipt-git-v1" → "git" or
// "cutting_garden-capture_receipt-caldav-v1" → "caldav". Both the legacy
// hyphen prefix and the converged underscore prefix (#112) are
// recognized.
//
// ok is false for any string that is not a protocol receipt type —
// notably the flat fs tag "cutting_garden-capture_receipt-fs-v1", which
// shares the underscore prefix but is a flat NDJSON receipt, not a
// protocol merkle tree. Callers rely on that exclusion to discriminate
// protocol receipts from the flat fs receipt.
var KindFromReceiptType = internal.KindFromReceiptType

// LockedRef builds a reference with its type-signature filled from the
// build-time registry, locking the reference to the type's current
// definition. Unregistered types yield a sig-less (unlocked) reference.
var LockedRef = internal.LockedRef

// MediaTypeFor returns the registered type's IANA media type, and
// whether the type is known.
var MediaTypeFor = internal.MediaTypeFor

// NewBlobStoreWriter returns a Writer backed by store.
var NewBlobStoreWriter = internal.NewBlobStoreWriter

// OpenNodeBody opens the blob identified by digest and parses its node
// header, returning the header and a ReadCloser that streams the node
// body. The caller MUST Close the returned reader — it owns the underlying
// blob reader. Use this instead of ReadNode when the body may be large
// (e.g. restoring a captured payload) to avoid buffering it in memory.
var OpenNodeBody = internal.OpenNodeBody

// ParseNode parses one hyphence node written by encodeNode/BuildNode. It
// is the inverse of that framing: an opening boundary, `- <alias> <
// @<digest> !<type>` reference lines, the `! type` line, the closing
// boundary, and an optional blank-line-separated body.
var ParseNode = internal.ParseNode

// ParseNodeHeader parses a node's framing (its type-string and ordered
// references) from r and returns the parsed header alongside a reader
// positioned at the first byte of the node body. Unlike ParseNode it does
// not buffer the body, so a caller materializing a large payload can
// io.Copy it straight to its destination.
//
// The body reader yields exactly the bytes ParseNode would have returned
// as Node.Body (verified by TestParseNodeHeader_BodyMatchesParseNode); it
// is empty when the node has no body, and is only valid until r is
// exhausted or closed. The returned Node's Body field is always nil — the
// body lives in the reader.
var ParseNodeHeader = internal.ParseNodeHeader

// ReadNode opens the blob identified by digest in store and parses it as a
// protocol node. It is the store-backed counterpart of ParseNode: the
// markl-id parse + MakeBlobReader + ParseNode loop that every binding's
// receipt walk needs lives here once, rather than being copied per plugin.
//
// Use this when the body is small (receipts, identity/invocation metadata,
// JCS payload bodies). For a node whose body may be large — a restored
// capture artifact — use OpenNodeBody to stream the body instead of
// buffering it.
var ReadNode = internal.ReadNode

// ReceiptType returns the receipt type-string for a capture kind, e.g.
// ReceiptType("caldav") == "cutting_garden-capture_receipt-caldav-v1".
// The kind names what is captured (caldav, web, git), not the plugin
// binary.
//
// Per #112 the canonical prefix is the underscore-bound `capture_receipt`
// (the underscore binds `capture`+`receipt` into one compound noun, which
// binds tighter than the hyphen segment separators). The pre-#112 kinds
// in frozenHyphenKinds keep the legacy hyphen `capture-receipt` prefix so
// their already-written, immutable receipts keep dispatching unchanged;
// every other (new) kind gets the converged underscore form.
var ReceiptType = internal.ReceiptType

// RegisterType installs def's type-blob and computes its signature.
// Intended for init() of the protocol package and each binding. Panics
// on a duplicate type-string or an empty/invalid definition — both are
// programmer errors caught at startup.
var RegisterType = internal.RegisterType

// SignatureFor returns the registered type's signature, and whether the
// type is known. Unknown types are sig-less (unlocked) per RFC 0002.
var SignatureFor = internal.SignatureFor

// VerifyRef checks a parsed reference's type lock against the registry.
// A sig-less reference is unlocked and always passes (RFC 0002). A
// signed reference to a registered type must match the registry's
// signature; a mismatch signals the reference was written against an
// incompatible type-definition version. References to types unknown to
// this binary pass (nothing to verify against).
var VerifyRef = internal.VerifyRef

// WriteNode is a convenience wrapper for writing a fully-materialized
// node (its bytes are already in memory). Streaming payloads (large git
// blobs, media files) should call WriteBlob with a reader instead.
var WriteNode = internal.WriteNode

// WriteReceipt assembles and writes the protocol merkle tree in
// post-order — every child before its parent, so each reference line
// carries a real digest — and returns the root receipt's markl id.
//
// Order: invocation, host, binary, plugin-env, environment,
// plugin-outcome (if any), outcome, identity, receipt. (Payload nodes
// were written by the caller before this call.)
var WriteReceipt = internal.WriteReceipt

// TypeBinary carries the plugin binary's name/version/digest (body).
const TypeBinary = internal.TypeBinary

// TypeEnvironment groups host/binary/plugin (metadata-only).
const TypeEnvironment = internal.TypeEnvironment

// TypeHost carries os/kernel/arch/libc (body).
const TypeHost = internal.TypeHost

// TypeIdentity is the identity subtree root (metadata-only).
const TypeIdentity = internal.TypeIdentity

// TypeInvocation carries the resolved request parameters (body).
const TypeInvocation = internal.TypeInvocation

// TypeOutcome carries per-run datetime + stripped residue (body).
const TypeOutcome = internal.TypeOutcome
