// Code generated by dagnabit (0.5.0+61aaadb); DO NOT EDIT.

package capture_receipt

import internal "code.linenisgreat.com/cutting-garden/internal/capture_receipt"

// Blob is the lowest-common-denominator return type for a parsed
// receipt across all wire versions. A successful parse returns a
// concrete *V1 (or *V2, etc.); the dispatcher narrows by type-id.
type Blob = internal.Blob

// EntryV1 is one filesystem entry in a cutting_garden-capture_receipt-fs-v1
// receipt body.
//
// Mode carries the lstat permission bits (only Mode.Perm() is rendered;
// type bits are dropped). Size and BlobId apply to regular files;
// Target applies to symlinks. The Root/Path split lets a single receipt
// describe entries from multiple capture-roots without path collisions.
type EntryV1 = internal.EntryV1

// StoreHint is the optional `- store/<id> < <markl-id>` metadata line
// per RFC 0001 §Producer Rules §Receipt Metadata: Store Hint.
// Consumers (restore) use it to auto-resolve the source store.
//
// The hint is wire-shape-shared across receipt versions: a v2 receipt
// would carry the same hint structure even if its Entries change.
type StoreHint = internal.StoreHint

// V1 is the parsed shape of a cutting_garden-capture_receipt-fs-v1 blob.
// Hint is non-nil iff the receipt's hyphence metadata block carried a
// store-hint line.
type V1 = internal.V1

// Coder decodes and encodes hyphence-wrapped receipts of any
// supported version. The metadata coder populates the typed-blob's
// Type and Hint; the Blob CoderTypeMapWithoutType then dispatches by
// Type to a version-specific body coder.
var Coder = internal.Coder

// ComputeStoreHint builds the RFC 0001 store-hint metadata for a
// receipt. Empty storeIdString returns (nil, nil), the MAY-omit path
// §Producer Rules §Receipt Metadata: Store Hint permits when the
// caller can't resolve a real id. A non-nil error is a soft failure
// — callers SHOULD surface it (sink notice on the capture side,
// FDR §Store-Hint Resolution §Hash-family fallback on the restore
// side) and treat the hint as absent.
//
// The hint's ConfigMarklId is computed in the store's default hash
// family so consumers can validate it under the same hash the store
// publishes blobs under.
//
// Phase 3 step 5 moved this here from internal/capture/store_hint.go
// so cutting-garden's restore cmd can run drift checks against the
// same compute path that capture wrote the hint with.
var ComputeStoreHint = internal.ComputeStoreHint

// Read fetches the blob named by id from blobStore, parses it via
// Coder, and returns the populated Blob (currently always *V1) plus
// its type-tag.
var Read = internal.Read

// TypeStructV1 is the wire type-id that appears on the `! ` line of a
// v1 receipt. Stored as ids.TypeStruct so it can compare directly
// with typedBlob.Type at dispatch time.
var TypeStructV1 = internal.TypeStructV1

// WriteV1 serializes entries as a hyphence-wrapped v1 receipt to w.
// Equivalent to WriteV1WithHint(w, entries, nil).
var WriteV1 = internal.WriteV1

// WriteV1ToStore encodes entries via WriteV1WithHint and writes the
// resulting blob into blobStore. Returns the blob's content-addressed
// markl id as a string. When hint is non-nil, the receipt's hyphence
// metadata block carries an RFC 0001 store-hint line; pass nil for
// hint to omit. Mirrors madder's writeReceiptBlob shape; shared by the
// capture and serve commands.
var WriteV1ToStore = internal.WriteV1ToStore

// WriteV1WithHint serializes entries as a hyphence-wrapped v1 receipt
// to w via the package's Coder, optionally prefixing a store-hint
// metadata line per RFC 0001 §Producer Rules §Receipt Metadata: Store
// Hint.
var WriteV1WithHint = internal.WriteV1WithHint

// HeaderV1 is the literal byte sequence that precedes the NDJSON body
// in every v1 receipt when no StoreHint is present. Derived from the
// hyphence boundary + type-tag line; exposed for tests that strip it
// to inspect just the body.
const HeaderV1 = internal.HeaderV1
const TypeDir = internal.TypeDir
const TypeFile = internal.TypeFile
const TypeOther = internal.TypeOther
const TypeSymlink = internal.TypeSymlink

// TypeTagV1 is the hyphence `! type-string` written at the top of
// every v1 receipt.
const TypeTagV1 = internal.TypeTagV1
