// Code generated by dagnabit (0.5.0+dirty); DO NOT EDIT.

package capture_events

import internal "code.linenisgreat.com/cutting-garden/internal/capture_events"

// Directive mirrors the tap-ndjson directive object {kind, reason}.
type Directive = internal.Directive

// Nop is a Stream whose methods do nothing. Embed it in partial
// implementations (test recorders, single-purpose consumers) so they
// only override what they handle.
type Nop = internal.Nop

// ReportPlan is the up-front work estimate for the live progress bar.
// Items == 0 means unknown (indeterminate display). Distinct from the
// TAP plan record (which counts phases and is renderer-derived).
type ReportPlan = internal.ReportPlan

// ReportProgress is one incremental advancement sample.
type ReportProgress = internal.ReportProgress

// Stream is the unified event contract. Phase events delimit TAP test
// points: events between PhaseStart and PhaseEnd attribute to that
// phase. Phases are flat (no nesting) in v1. Entry/Failure are the
// per-entry result events: plugins emit them here (Stage B); the
// pipe-path consumer is capture_render_legacy's bridge onto the
// legacy sinks until the unified renderers land.
type Stream = internal.Stream

// Verdict is the completion record of a phase — the in-process shape of
// a tap-ndjson `test` record's verdict-bearing fields. The phase number
// (`n`) is assigned renderer-side (tap text writers auto-number; the
// Stage-B ndjson renderer keeps its own counter), so it does not appear
// here.
type Verdict = internal.Verdict

// OrNop returns s, or a Nop when s is nil.
var OrNop = internal.OrNop

const DirectiveSkip = internal.DirectiveSkip
const DirectiveTodo = internal.DirectiveTodo
